/* frags-teoria/campi.js — teoria per l'orale: campi vettoriali e forme differenziali */
LAV.campi = [

{type:6, topic:"Lavoro di un campo lungo una curva",
 q:"Definisca il lavoro di un campo vettoriale lungo una curva. Da cosa dipende, e sotto quali ipotesi la definizione ha senso?",
 prov:"Programma ufficiale del corso, blocco «campi vettoriali e forme differenziali»",
 model:"<b>Definizione.</b> Sia $F:\\Omega\\subseteq\\mathbb{R}^n\\to\\mathbb{R}^n$ un campo continuo su un aperto $\\Omega$, e sia $\\gamma:[a,b]\\to\\Omega$ una curva regolare a tratti. Il lavoro di $F$ lungo $\\gamma$ e' l'integrale di linea di seconda specie $$L=\\int_\\gamma F\\cdot d\\mathbf{r}=\\int_a^b F(\\gamma(t))\\cdot\\gamma'(t)\\,dt.$$ <b>Perche' e' ben posto.</b> $F$ continuo e $\\gamma$ regolare a tratti rendono l'integranda $t\\mapsto F(\\gamma(t))\\cdot\\gamma'(t)$ continua a tratti, quindi integrabile secondo Riemann su $[a,b]$. <b>Da cosa dipende.</b> Il valore non dipende dalla parametrizzazione purche' se ne conservi il verso: un cambio di parametro $t=\\varphi(s)$ crescente lascia $L$ invariato per la formula di cambio di variabile, mentre invertire il verso cambia il segno, $L(-\\gamma)=-L(\\gamma)$. In generale $L$ dipende dall'intero sostegno percorso, non solo dagli estremi: e' proprio questa dipendenza a sparire per i campi conservativi. <b>Forma differenziale associata.</b> Scrivendo $F=(F_1,\\dots,F_n)$, l'integranda e' la forma differenziale lineare $\\omega=F_1\\,dx_1+\\dots+F_n\\,dx_n$; il lavoro e' $\\int_\\gamma\\omega$. Campo e forma sono lo stesso oggetto in due linguaggi: tutta la teoria che segue si puo' leggere in entrambi."},

{type:6, topic:"Rotore: definizione e significato",
 q:"Definisca il rotore di un campo in $\\mathbb{R}^3$ e in $\\mathbb{R}^2$. Che cosa misura, e perche' e' la condizione di chiusura naturale?",
 prov:"Programma ufficiale del corso, blocco «campi vettoriali e forme differenziali»",
 model:"<b>Definizione in $\\mathbb{R}^3$.</b> Per $F=(P,Q,R)$ di classe $C^1$, $$\\nabla\\times F=\\left(\\frac{\\partial R}{\\partial y}-\\frac{\\partial Q}{\\partial z},\\;\\frac{\\partial P}{\\partial z}-\\frac{\\partial R}{\\partial x},\\;\\frac{\\partial Q}{\\partial x}-\\frac{\\partial P}{\\partial y}\\right).$$ Il campo si dice <b>irrotazionale</b> se $\\nabla\\times F=0$ su tutto il dominio. <b>Definizione in $\\mathbb{R}^2$.</b> Per $F=(P,Q)$ il rotore si riduce alla componente scalare $\\partial_x Q-\\partial_y P$; irrotazionale significa $\\partial_x Q=\\partial_y P$. <b>Che cosa misura.</b> Per il teorema del rotore (Stokes/Green) la circuitazione infinitesima intorno a un punto e' governata dal rotore: $\\oint_{\\partial D}F\\cdot d\\mathbf{r}=\\iint_D(\\nabla\\times F)\\cdot\\mathbf{n}\\,dS$, quindi $\\nabla\\times F$ e' la densita' di circuitazione, la tendenza locale del campo a far ruotare. <b>Perche' e' la chiusura.</b> Nel linguaggio delle forme, $\\nabla\\times F=0$ equivale a $d\\omega=0$: la forma $\\omega=P\\,dx+Q\\,dy(+R\\,dz)$ e' chiusa. Le uguaglianze incrociate $\\partial_i F_j=\\partial_j F_i$ non sono altro che il teorema di Schwarz applicato a un ipotetico potenziale, ed e' esattamente il segnale di allarme: sono necessarie per l'esattezza, ma vedremo che da sole non bastano."},

{type:6, topic:"Campi conservativi: definizione ed equivalenze",
 q:"Che cos'e' un campo conservativo? Enunci le caratterizzazioni equivalenti e dica quali sono sempre vere e quali richiedono ipotesi sul dominio.",
 prov:"Programma ufficiale del corso, blocco «campi vettoriali e forme differenziali»",
 model:"<b>Definizione.</b> $F$ continuo su un aperto connesso $\\Omega$ e' <b>conservativo</b> se esiste $U\\in C^1(\\Omega)$, detto potenziale, con $F=\\nabla U$. Nel linguaggio delle forme: $\\omega=dU$ e' esatta. <b>Equivalenze SEMPRE valide</b> (nessuna ipotesi sul dominio oltre la connessione, e valgono per ogni aperto): sono equivalenti (i) $F$ e' conservativo; (ii) $\\int_\\gamma F\\cdot d\\mathbf{r}$ dipende solo dagli estremi di $\\gamma$ (indipendenza dal cammino); (iii) $\\oint_\\gamma F\\cdot d\\mathbf{r}=0$ per ogni cammino chiuso $\\gamma$ regolare a tratti. Questo triangolo e' un teorema puramente analitico, non chiede nulla alla topologia. <b>Implicazione SEMPRE valida in un senso solo.</b> Conservativo $\\Rightarrow$ irrotazionale ($\\nabla\\times F=0$), per Schwarz. <b>Il verso che RICHIEDE il dominio.</b> Irrotazionale $\\Rightarrow$ conservativo vale <b>solo</b> se $\\Omega$ e' semplicemente connesso. E' qui che la topologia entra e qui che nascono i controesempi. <b>Sintesi da tenere a mente.</b> Conservativo e' un concetto globale (chiede un potenziale su tutto $\\Omega$); irrotazionale e' locale (una condizione differenziale punto per punto). Il ponte fra locale e globale e' la forma del dominio."},

{type:6, topic:"Forme differenziali chiuse ed esatte",
 q:"Definisca forma differenziale lineare chiusa ed esatta. Che rapporto c'e' fra le due nozioni e con i campi conservativi e irrotazionali?",
 prov:"Programma ufficiale del corso, blocco «campi vettoriali e forme differenziali»",
 model:"<b>Forma lineare.</b> Una $1$-forma su $\\Omega\\subseteq\\mathbb{R}^n$ e' $\\omega=\\sum_i F_i\\,dx_i$ con $F_i$ funzioni su $\\Omega$; e' il duale del campo $F=(F_1,\\dots,F_n)$. <b>Esatta.</b> $\\omega$ e' esatta se esiste $U$ con $\\omega=dU$, cioe' $F_i=\\partial_i U$: e' il campo conservativo tradotto. <b>Chiusa.</b> $\\omega$ e' chiusa se $d\\omega=0$, cioe' se valgono tutte le uguaglianze incrociate $\\partial_j F_i=\\partial_i F_j$: e' il campo irrotazionale tradotto. <b>Il rapporto.</b> Esatta $\\Rightarrow$ chiusa sempre, perche' $d(dU)=0$ (Schwarz): $$\\omega=dU\\;\\Longrightarrow\\;d\\omega=d(dU)=0.$$ Il viceversa, chiusa $\\Rightarrow$ esatta, e' <b>falso in generale</b> e vero su domini semplicemente connessi (lemma di Poincare'). <b>Dizionario da recitare all'esaminatore.</b> esatta $\\leftrightarrow$ conservativo; chiusa $\\leftrightarrow$ irrotazionale; $d\\omega=0\\leftrightarrow\\nabla\\times F=0$. Lo scarto fra chiuse ed esatte misura, in un senso reso preciso dalla coomologia di de Rham, quante lacune ha il dominio."},

{type:6, topic:"Semplice connessione: l'ipotesi che non si toglie",
 q:"Enunci con precisione l'ipotesi di semplice connessione nel teorema «chiusa implica esatta». Perche' non basta la connessione? Cosa succede indebolendola?",
 prov:"Programma ufficiale del corso, blocco «campi vettoriali e forme differenziali»",
 model:"<b>L'enunciato.</b> Se $\\Omega\\subseteq\\mathbb{R}^n$ e' aperto e <b>semplicemente connesso</b> e $F\\in C^1(\\Omega)$ e' irrotazionale, allora $F$ e' conservativo. <b>Semplicemente connesso.</b> $\\Omega$ e' connesso per archi e ogni cammino chiuso in $\\Omega$ e' contraibile a un punto restando in $\\Omega$ (omotopia a cappio costante). Intuitivamente: connesso e senza buchi che un laccio possa cingere. <b>Perche' la sola connessione non basta.</b> Connessione garantisce solo che due punti si congiungono con un cammino, dunque che il potenziale, se esiste, e' unico a meno di costante. Ma per <b>costruire</b> $U$ si pone $U(x)=\\int_{x_0}^x F\\cdot d\\mathbf{r}$ e serve che questo integrale non dipenda dal cammino scelto: due cammini diversi da $x_0$ a $x$ formano un cappio, e la loro differenza di lavoro e' la circuitazione su quel cappio. Se il cappio si contrae (semplice connessione), il teorema di Stokes lo riempie con una superficie su cui $\\nabla\\times F=0$, e la circuitazione e' nulla; se il cappio cinge un buco, non c'e' superficie interna e il conto puo' fallire. <b>Indebolimento.</b> Togliere la semplice connessione lasciando la connessione (es. $\\mathbb{R}^2\\setminus\\{0\\}$) apre la porta a campi chiusi non esatti: e' esattamente il controesempio angolare. La connessione da sola controlla l'unicita' del potenziale, non la sua esistenza."},

{type:6, topic:"Dimostrazione: conservativo se e solo se circuitazione nulla",
 q:"Dimostri che $F$ e' conservativo se e solo se la sua circuitazione e' nulla lungo ogni cammino chiuso. Faccia tutti i passi.",
 prov:"Programma ufficiale del corso, blocco «campi vettoriali e forme differenziali»",
 model:"Sia $F$ continuo su un aperto connesso $\\Omega$. <b>Passo 1 — conservativo $\\Rightarrow$ circuitazione nulla.</b> Se $F=\\nabla U$ e $\\gamma:[a,b]\\to\\Omega$ e' chiuso ($\\gamma(a)=\\gamma(b)$), per il teorema fondamentale del calcolo lungo curve $$\\oint_\\gamma F\\cdot d\\mathbf{r}=\\int_a^b\\nabla U(\\gamma(t))\\cdot\\gamma'(t)\\,dt=\\int_a^b\\frac{d}{dt}U(\\gamma(t))\\,dt=U(\\gamma(b))-U(\\gamma(a))=0.$$ <b>Passo 2 — circuitazione nulla $\\Rightarrow$ indipendenza dal cammino.</b> Siano $\\gamma_1,\\gamma_2$ due cammini da $A$ a $B$. Il cammino $\\gamma_1$ seguito da $\\gamma_2$ percorso all'indietro e' chiuso, quindi $\\int_{\\gamma_1}F\\cdot d\\mathbf{r}-\\int_{\\gamma_2}F\\cdot d\\mathbf{r}=\\oint F\\cdot d\\mathbf{r}=0$, cioe' i due integrali coincidono. <b>Passo 3 — indipendenza $\\Rightarrow$ esistenza del potenziale.</b> Fissato $x_0\\in\\Omega$, ben definisco $$U(x)=\\int_{x_0}^{x}F\\cdot d\\mathbf{r}$$ scegliendo un qualunque cammino (il valore non dipende dalla scelta per il Passo 2; l'esistenza di un cammino e' garantita dalla connessione per archi degli aperti connessi). <b>Passo 4 — $\\nabla U=F$.</b> Fissato $i$, uso il segmento da $x$ a $x+he_i$, tutto in $\\Omega$ per $h$ piccolo (aperto): $$\\frac{U(x+he_i)-U(x)}{h}=\\frac1h\\int_0^h F_i(x+se_i)\\,ds\\xrightarrow[h\\to0]{}F_i(x)$$ per continuita' di $F_i$ (teorema della media integrale). Quindi $\\partial_i U=F_i$ per ogni $i$, cioe' $\\nabla U=F$ e $F$ e' conservativo. $\\;\\boxed{\\text{c.v.d.}}$ <b>Nota.</b> Nessuna ipotesi topologica oltre la connessione: e' un'equivalenza analitica pura."},

{type:6, topic:"Dimostrazione: conservativo implica irrotazionale",
 q:"Dimostri che ogni campo conservativo di classe $C^1$ e' irrotazionale. Dove usa le ipotesi? Vale il viceversa?",
 prov:"Programma ufficiale del corso, blocco «campi vettoriali e forme differenziali»",
 model:"<b>Ipotesi.</b> $F=\\nabla U$ su $\\Omega$ aperto, con $F\\in C^1$; allora $U\\in C^2$. <b>Conto (caso $\\mathbb{R}^2$).</b> $P=\\partial_x U$, $Q=\\partial_y U$. La componente del rotore e' $$\\partial_x Q-\\partial_y P=\\partial_x\\partial_y U-\\partial_y\\partial_x U=0$$ per il <b>teorema di Schwarz</b> sull'inversione delle derivate seconde miste, lecito perche' $U\\in C^2$. <b>Caso $\\mathbb{R}^3$.</b> Con $F=(P,Q,R)=(\\partial_x U,\\partial_y U,\\partial_z U)$, ogni componente di $\\nabla\\times F$ e' una differenza di miste, ad esempio $\\partial_x Q-\\partial_y P=\\partial_x\\partial_y U-\\partial_y\\partial_x U=0$, e cosi' le altre due: $\\nabla\\times(\\nabla U)=0$. <b>Dove mordono le ipotesi.</b> Serve $F\\in C^1$ (cioe' $U\\in C^2$) per invocare Schwarz; senza regolarita' l'uguaglianza delle miste puo' cadere. Nessuna ipotesi sul dominio: vale su qualunque aperto. <b>Viceversa.</b> FALSO in generale: irrotazionale non implica conservativo. Il viceversa richiede la semplice connessione del dominio (lemma di Poincare'), e il campo angolare su $\\mathbb{R}^2\\setminus\\{0\\}$ e' il controesempio standard. Quindi: conservativo $\\Rightarrow$ irrotazionale e' un'implicazione a senso unico, gratuita; l'inversione costa un'ipotesi topologica."},

{type:6, topic:"Dimostrazione: chiusa implica esatta su semplicemente connesso",
 q:"Dimostri, almeno su un dominio stellato, che una forma chiusa e' esatta (lemma di Poincare'). Perche' la stella e' la chiave?",
 prov:"Programma ufficiale del corso, blocco «campi vettoriali e forme differenziali»",
 model:"Dimostro il nucleo su un aperto <b>stellato</b> rispetto all'origine (ogni segmento $[0,x]\\subset\\Omega$); il caso semplicemente connesso segue con l'invarianza omotopica dell'integrale. <b>Costruzione del potenziale.</b> Data $\\omega=\\sum_i F_i\\,dx_i$ chiusa ($\\partial_j F_i=\\partial_i F_j$), definisco $$U(x)=\\int_0^1 F(tx)\\cdot x\\,dt=\\int_0^1\\sum_i F_i(tx)\\,x_i\\,dt,$$ cioe' il lavoro lungo il segmento da $0$ a $x$. <b>Verifica $\\partial_k U=F_k$.</b> Derivo sotto il segno (lecito, integranda $C^1$): $$\\partial_k U(x)=\\int_0^1\\Big(F_k(tx)+\\sum_i t\\,\\partial_k F_i(tx)\\,x_i\\Big)dt.$$ Uso la chiusura $\\partial_k F_i=\\partial_i F_k$ nel secondo addendo: $$\\partial_k U(x)=\\int_0^1\\Big(F_k(tx)+t\\sum_i x_i\\,\\partial_i F_k(tx)\\Big)dt.$$ Riconosco la derivata totale: $\\frac{d}{dt}\\big(t\\,F_k(tx)\\big)=F_k(tx)+t\\sum_i x_i\\partial_i F_k(tx)$. Dunque $$\\partial_k U(x)=\\int_0^1\\frac{d}{dt}\\big(t\\,F_k(tx)\\big)dt=\\big[t\\,F_k(tx)\\big]_0^1=F_k(x).$$ Quindi $\\nabla U=F$, la forma e' esatta. $\\;\\boxed{\\text{c.v.d.}}$ <b>Perche' la stella e' la chiave.</b> La formula usa che ogni $x$ e' raggiungibile dall'origine con un segmento <b>interno</b> a $\\Omega$; e' l'ipotesi geometrica che rimpiazza i buchi. Su un semplicemente connesso generico si sostituisce il segmento con un cammino qualunque e si dimostra l'indipendenza dal cammino contraendo i cappi (Stokes su una superficie interna dove $d\\omega=0$)."},

{type:6, topic:"Ricostruzione del potenziale per integrazione",
 q:"Dato un campo irrotazionale su un dominio buono, mostri la procedura per ricostruire il potenziale integrando componente per componente. Come si controlla la compatibilita'?",
 prov:"Programma ufficiale del corso, blocco «campi vettoriali e forme differenziali»",
 model:"E' la tecnica operativa (metodo delle primitive parziali), da saper eseguire alla lavagna. <b>Setup.</b> $F=(P,Q)$ irrotazionale su un aperto semplicemente connesso; cerco $U$ con $\\partial_x U=P$, $\\partial_y U=Q$. <b>Passo 1 — integro la prima.</b> $$U(x,y)=\\int P(x,y)\\,dx+g(y),$$ dove $g(y)$ e' la costante d'integrazione, funzione della sola $y$. <b>Passo 2 — impongo la seconda.</b> Derivo in $y$ e uguaglio a $Q$: $$\\partial_y U=\\partial_y\\!\\int P\\,dx+g'(y)=Q(x,y)\\;\\Rightarrow\\;g'(y)=Q-\\partial_y\\!\\int P\\,dx.$$ <b>Passo 3 — il controllo di compatibilita'.</b> Perche' il metodo chiuda, il membro di destra deve dipendere <b>solo da $y$</b>: la sua derivata in $x$ deve annullarsi, $$\\partial_x\\!\\Big(Q-\\partial_y\\!\\int P\\,dx\\Big)=\\partial_x Q-\\partial_y P=0,$$ che e' esattamente la condizione di irrotazionalita'. Se il campo non fosse chiuso, $g'$ dipenderebbe da $x$ e la ricostruzione fallirebbe: e' il controllo che smaschera un campo non conservativo. <b>Passo 4.</b> Integro $g'(y)$ in $y$ e ottengo $U$ a meno di una costante additiva. <b>Esempio.</b> $F=(2xy,\\,x^2+1)$: da $\\partial_x U=2xy$ segue $U=x^2y+g(y)$; imponendo $\\partial_y U=x^2+g'(y)=x^2+1$ trovo $g'(y)=1$, $g(y)=y$, dunque $U=x^2y+y+c$. In $\\mathbb{R}^3$ si ripete il ciclo su tre componenti, con una costante che via via diventa funzione delle variabili non ancora usate."},

{type:6, topic:"Controesempio: il campo angolare, circuitazione 2pi",
 q:"Esibisca un campo irrotazionale ma non conservativo e svolga per intero il conto della circuitazione. Perche' non contraddice il lemma di Poincare'?",
 prov:"Programma ufficiale del corso, blocco «campi vettoriali e forme differenziali»",
 model:"<b>Il campo.</b> Su $\\Omega=\\mathbb{R}^2\\setminus\\{0\\}$, $$F(x,y)=\\left(\\frac{-y}{x^2+y^2},\\;\\frac{x}{x^2+y^2}\\right).$$ Formalmente $F=\\nabla\\theta$, gradiente dell'angolo polare, che pero' non e' una funzione univoca su tutto $\\Omega$. <b>Passo 1 — e' irrotazionale.</b> Con $P=-y/(x^2+y^2)$, $Q=x/(x^2+y^2)$: $$\\partial_x Q=\\frac{(x^2+y^2)-x\\cdot2x}{(x^2+y^2)^2}=\\frac{y^2-x^2}{(x^2+y^2)^2},\\qquad \\partial_y P=\\frac{-(x^2+y^2)+y\\cdot2y}{(x^2+y^2)^2}=\\frac{y^2-x^2}{(x^2+y^2)^2}.$$ Quindi $\\partial_x Q-\\partial_y P=0$ su tutto $\\Omega$: chiuso. <b>Passo 2 — la circuitazione sul cerchio.</b> Parametrizzo $\\gamma(t)=(R\\cos t,R\\sin t)$, $t\\in[0,2\\pi]$, cosi' $dx=-R\\sin t\\,dt$, $dy=R\\cos t\\,dt$ e $x^2+y^2=R^2$: $$\\oint_\\gamma F\\cdot d\\mathbf{r}=\\int_0^{2\\pi}\\frac{-y\\,dx+x\\,dy}{x^2+y^2}=\\int_0^{2\\pi}\\frac{R^2\\sin^2 t+R^2\\cos^2 t}{R^2}\\,dt=\\int_0^{2\\pi}dt=2\\pi\\neq0.$$ <b>Passo 3 — conclusione.</b> Esiste un cammino chiuso con circuitazione non nulla, dunque $F$ NON e' conservativo, pur essendo irrotazionale. Il valore $2\\pi$ e' l'indice di avvolgimento della curva attorno al buco. <b>Perche' nessuna contraddizione.</b> Il lemma di Poincare' chiede la semplice connessione, e $\\mathbb{R}^2\\setminus\\{0\\}$ non lo e': il cerchio cinge il buco e non si contrae. Il rotore nullo e' un fatto locale che ignora il buco; la circuitazione e' un fatto globale che lo vede. <b>Osservazione.</b> Su un semipiano, o su $\\mathbb{R}^2$ meno una semiretta uscente dall'origine (dominio semplicemente connesso che evita il buco), lo stesso $F$ diventa conservativo, con potenziale la determinazione continua dell'angolo $\\theta$."},

{type:6, topic:"Domini con piu' lacune: come si decide",
 q:"In un dominio con piu' buchi, come si decide se un campo irrotazionale e' conservativo? Che ruolo hanno i periodi sui cappi?",
 prov:"Programma ufficiale del corso, blocco «campi vettoriali e forme differenziali»",
 model:"<b>Il criterio.</b> Sia $F$ irrotazionale su $\\Omega$ aperto connesso con $k$ lacune (es. $\\mathbb{R}^2$ meno $k$ punti). $F$ e' conservativo su $\\Omega$ se e solo se la circuitazione si annulla su <b>ogni</b> cammino chiuso; e per questo basta annullarla sui $k$ cappi indipendenti, uno per ciascuna lacuna. <b>Perche' bastano $k$ cappi.</b> Ogni cappio in $\\Omega$ e' omotopo a una combinazione (con molteplicita' e verso) dei cappi elementari $\\gamma_1,\\dots,\\gamma_k$ che cingono una lacuna ciascuno. Definiti i <b>periodi</b> $$p_j=\\oint_{\\gamma_j}F\\cdot d\\mathbf{r},$$ la circuitazione su un cappio generico $\\gamma=\\sum_j n_j\\gamma_j$ (con $n_j\\in\\mathbb{Z}$ indici di avvolgimento) vale $\\oint_\\gamma F\\cdot d\\mathbf{r}=\\sum_j n_j p_j$, perche' su regioni interne a $\\Omega$ vale Green e la parte senza buchi non contribuisce. <b>Decisione operativa.</b> Calcolo i $k$ periodi: se sono tutti nulli, $F$ e' conservativo; se anche uno solo e' non nullo, non lo e'. <b>Esempio a due buchi.</b> $\\mathbb{R}^2\\setminus\\{A,B\\}$ con $F=\\alpha\\,F_A+\\beta\\,F_B$, dove $F_A,F_B$ sono campi angolari centrati in $A$ e $B$: i periodi sono $p_A=2\\pi\\alpha$, $p_B=2\\pi\\beta$. $F$ e' conservativo se e solo se $\\alpha=\\beta=0$. Se $\\alpha=-\\beta$, la circuitazione su un cappio che cinge <b>entrambi</b> i buchi e' $2\\pi(\\alpha+\\beta)=0$, ma sul cappio attorno al solo $A$ vale $2\\pi\\alpha\\neq0$: quindi non conservativo, e si vede che non basta controllare un cappio grande, servono quelli elementari. <b>Lettura strutturale.</b> I periodi sono le coordinate della classe di $\\omega$ nel primo gruppo di coomologia $H^1_{dR}(\\Omega)\\cong\\mathbb{R}^k$; esatta $\\Leftrightarrow$ tutti i periodi nulli."},

{type:6, topic:"Da esaminatore: punto contro retta in R^3",
 q:"In $\\mathbb{R}^3$ che differenza c'e' fra togliere un punto e togliere una retta, per la conservativita' di un campo irrotazionale? E fra R^2 e R^3?",
 prov:"Programma ufficiale del corso, blocco «campi vettoriali e forme differenziali»",
 model:"E' la domanda che separa chi ha capito la topologia da chi ha memorizzato lo slogan dei buchi. <b>$\\mathbb{R}^3$ meno un punto: ancora semplicemente connesso.</b> $\\mathbb{R}^3\\setminus\\{0\\}$ e' connesso e ogni cappio si contrae: un laccio in $\\mathbb{R}^3$ puo' sempre scivolare via dal punto, perche' c'e' una dimensione libera in piu' per aggirarlo. Formalmente si retrae sulla sfera $S^2$, che e' semplicemente connessa ($\\pi_1(S^2)=0$). Quindi su $\\mathbb{R}^3\\setminus\\{0\\}$ ogni campo irrotazionale $C^1$ E' conservativo: togliere un punto in dimensione $3$ non crea ostruzione ai cappi. <b>$\\mathbb{R}^3$ meno una retta: NON semplicemente connesso.</b> $\\mathbb{R}^3\\setminus(\\text{asse }z)$ si retrae su $\\mathbb{R}^2\\setminus\\{0\\}$ (piano ortogonale meno un punto): un cappio che gira attorno alla retta non si contrae, la retta lo blocca come un chiodo. Qui vive il campo angolare tridimensionale $F=\\big(\\frac{-y}{x^2+y^2},\\frac{x}{x^2+y^2},0\\big)$: irrotazionale ma non conservativo, circuitazione $2\\pi$ attorno all'asse. <b>Il principio.</b> Cio' che ostruisce un $1$-cappio e' un oggetto di <b>codimensione $2$</b>: in $\\mathbb{R}^2$ e' un punto (codim $2$), in $\\mathbb{R}^3$ e' una retta (codim $2$). Un punto in $\\mathbb{R}^3$ ha codimensione $3$ e non ostruisce i cappi (ostruirebbe le sfere, cioe' la teoria dei campi solenoidali/monopolo, altra storia). <b>Confronto $\\mathbb{R}^2$ vs $\\mathbb{R}^3$.</b> In $\\mathbb{R}^2$ togliere un punto rompe la semplice connessione; in $\\mathbb{R}^3$ no. La stessa parola buco cambia peso con la dimensione: conta la codimensione, non la parola."}

];
