/* frags-teoria/differenziale.js — teoria per l orale: differenziabilita, Schwarz, Taylor, estremi liberi
   FUSIONE del 06-09: due versioni dello stesso blocco erano state scritte in parallelo — una dal
   ciclo notturno, una da un dispaccio mio — perche non ho guardato cosa stesse gia facendo il ciclo
   prima di dispacciare. Invece di sceglierne una si sono unite: dalla versione del ciclo restano le
   due unita che la mia non copriva, e la regola della catena era un buco vero (sta nel programma
   ufficiale del corso). Lo spreco era di monte, non di lavoro. */
LAV.differenziale = [

{type:6, topic:"Differenziabilita' in piu' variabili: definizione",
 q:"Dia la definizione di funzione differenziabile in un punto. In che senso e' piu' forte della sola esistenza delle derivate parziali?",
 prov:"Programma ufficiale del corso, blocco «calcolo differenziale»",
 model:"<b>Definizione.</b> Sia $f:A\\subseteq\\mathbb{R}^n\\to\\mathbb{R}$, $A$ aperto, $x_0\\in A$. $f$ e' differenziabile in $x_0$ se esiste un'applicazione lineare $L:\\mathbb{R}^n\\to\\mathbb{R}$ tale che $$f(x_0+h)=f(x_0)+L(h)+o(|h|)\\quad(h\\to 0).$$ <b>Il gradiente.</b> Se $L$ esiste e' unica e ha per matrice il gradiente: $L(h)=\\nabla f(x_0)\\cdot h=\\sum_{i}\\frac{\\partial f}{\\partial x_i}(x_0)\\,h_i$. Il resto $o(|h|)$ significa $$\\lim_{h\\to0}\\frac{f(x_0+h)-f(x_0)-\\nabla f(x_0)\\cdot h}{|h|}=0.$$ <b>Perche' e' piu' forte.</b> Le parziali sono derivate lungo i soli assi: catturano il comportamento su $n$ rette. La differenziabilita' chiede che l'incremento sia approssimato dallo STESSO piano (la mappa lineare $L$) in OGNI direzione, con errore che va a zero piu' in fretta di $|h|$ — un controllo uniforme su tutte le direzioni contemporaneamente. Esistono funzioni con tutte le parziali (perfino tutte le direzionali) che NON sono differenziabili, perche' quelle derivate non si incollano in una mappa lineare che approssimi $f$. La differenziabilita' e' la vera nozione di 'derivabilita'' in piu' variabili; le parziali sono soltanto le sue componenti candidate."},

{type:6, topic:"Teorema del differenziale totale (condizione sufficiente)",
 q:"Enunci una condizione sufficiente per la differenziabilita'. Vale il viceversa?",
 prov:"Programma ufficiale del corso, blocco «calcolo differenziale»",
 model:"<b>Enunciato.</b> Se le derivate parziali $\\frac{\\partial f}{\\partial x_1},\\dots,\\frac{\\partial f}{\\partial x_n}$ esistono in un intorno di $x_0$ e sono continue in $x_0$, allora $f$ e' differenziabile in $x_0$. <b>Ipotesi da non tagliare.</b> Non basta che le parziali esistano nel solo $x_0$: servono in tutto un intorno ed essere continue nel punto. E' la continuita' che permette di 'trasportare' il valore delle parziali dal punto ai punti vicini con errore infinitesimo. <b>Le classi.</b> $f\\in C^1(A)$ (parziali continue su $A$) $\\Rightarrow$ $f$ differenziabile in ogni punto di $A$. <b>Non si inverte.</b> Differenziabile NON implica $C^1$: la funzione $$f(x,y)=(x^2+y^2)\\sin\\!\\frac{1}{\\sqrt{x^2+y^2}},\\qquad f(0,0)=0,$$ e' differenziabile in $(0,0)$ con $\\nabla f(0,0)=(0,0)$ (il resto e' $|h|^2\\cdot(\\text{limitato})=o(|h|)$), ma le parziali non sono continue in $(0,0)$: contengono un termine $\\cos\\frac{1}{\\sqrt{x^2+y^2}}$ che oscilla senza limite avvicinandosi all'origine. Lo schema esatto e' dunque $$C^1\\ \\Rightarrow\\ \\text{differenziabile}\\ \\Rightarrow\\ \\text{parziali esistono},$$ e nessuna delle due frecce si inverte."},

{type:6, topic:"Teorema di Schwarz sulle derivate miste",
 q:"Enunci il teorema di Schwarz. Qual e' l'ipotesi che non si puo' togliere?",
 prov:"Programma ufficiale del corso, blocco «calcolo differenziale»",
 model:"<b>Enunciato.</b> Sia $f:A\\subseteq\\mathbb{R}^n\\to\\mathbb{R}$, $A$ aperto. Se in un intorno di $x_0$ esistono le derivate seconde miste $\\frac{\\partial^2 f}{\\partial x_i\\partial x_j}$ e $\\frac{\\partial^2 f}{\\partial x_j\\partial x_i}$ e sono continue in $x_0$, allora coincidono: $$\\frac{\\partial^2 f}{\\partial x_i\\partial x_j}(x_0)=\\frac{\\partial^2 f}{\\partial x_j\\partial x_i}(x_0).$$ <b>Conseguenza.</b> Se $f\\in C^2(A)$ la matrice hessiana $H_f(x_0)=\\big(\\frac{\\partial^2 f}{\\partial x_i\\partial x_j}\\big)$ e' SIMMETRICA in ogni punto. <b>L'ipotesi cruciale.</b> E' la continuita' delle miste (equivalentemente $f\\in C^2$). Senza di essa le miste possono esistere entrambe e differire: il controesempio classico e' $f(x,y)=\\frac{xy(x^2-y^2)}{x^2+y^2}$ (prolungata con $0$), dove in origine una mista vale $-1$ e l'altra $+1$. <b>Perche' la simmetria conta.</b> Su di essa poggia il teorema spettrale applicato all'hessiana: solo perche' $H_f$ e' simmetrica reale essa e' diagonalizzabile con autovalori reali, e il segno di quegli autovalori decide gli estremi. Togli Schwarz e la forma quadratica del secondo ordine perde senso."},

{type:6, topic:"Formula di Taylor al secondo ordine",
 q:"Scriva la formula di Taylor al secondo ordine per una funzione di piu' variabili, con il resto.",
 prov:"Programma ufficiale del corso, blocco «calcolo differenziale»",
 model:"<b>Enunciato (resto di Peano).</b> Se $f\\in C^2$ in un intorno di $x_0$, allora $$f(x_0+h)=f(x_0)+\\nabla f(x_0)\\cdot h+\\tfrac12\\,h^{T}H_f(x_0)\\,h+o(|h|^2),$$ dove $H_f(x_0)$ e' l'hessiana e $h^{T}H_f h=\\sum_{i,j}\\frac{\\partial^2 f}{\\partial x_i\\partial x_j}(x_0)\\,h_i h_j$. <b>Lettura dei tre pezzi.</b> Termine zero $f(x_0)$: il valore. Termine primo $\\nabla f(x_0)\\cdot h$: la parte lineare, il piano tangente. Termine secondo $\\tfrac12 h^{T}H h$: la forma quadratica che porta la curvatura. <b>Resto di Lagrange.</b> Esiste $\\xi$ sul segmento $[x_0,x_0+h]$ con $$f(x_0+h)=f(x_0)+\\nabla f(x_0)\\cdot h+\\tfrac12\\,h^{T}H_f(\\xi)\\,h,$$ senza resto infinitesimo ma con l'hessiana valutata in un punto intermedio. <b>A cosa serve.</b> Nei punti critici ($\\nabla f=0$) il termine lineare sparisce e il segno di $f(x_0+h)-f(x_0)$ e' deciso, al primo ordine non banale, dalla forma quadratica hessiana: e' la radice della classificazione degli estremi liberi."},

{type:6, topic:"Differenziabile implica continua e derivabile in ogni direzione",
 q:"Dimostri che se f e' differenziabile in x0 allora e' continua in x0 e ammette tutte le derivate direzionali, con la formula del gradiente.",
 prov:"Programma ufficiale del corso, blocco «calcolo differenziale»",
 model:"<b>Ipotesi.</b> $f(x_0+h)=f(x_0)+\\nabla f(x_0)\\cdot h+o(|h|)$. <b>(1) Continuita'.</b> Passando al limite $h\\to0$: $\\nabla f(x_0)\\cdot h\\to0$ (e' lineare) e $o(|h|)\\to0$, quindi $f(x_0+h)\\to f(x_0)$, cioe' $f$ e' continua in $x_0$. <b>(2) Derivate direzionali.</b> Sia $v$ con $|v|=1$. Poniamo $h=tv$, $t\\to0$: $$\\frac{f(x_0+tv)-f(x_0)}{t}=\\frac{\\nabla f(x_0)\\cdot(tv)+o(|tv|)}{t}=\\nabla f(x_0)\\cdot v+\\frac{o(|t|)}{t}.$$ Poiche' $\\frac{o(|t|)}{t}\\to0$, il limite esiste e $$D_vf(x_0)=\\nabla f(x_0)\\cdot v.$$ <b>Cosa si e' guadagnato.</b> Non solo esistono TUTTE le direzionali (non solo le parziali), ma dipendono LINEARMENTE da $v$ tramite un unico vettore, il gradiente. Questa linearita' in $v$ e' la firma della differenziabilita': e' cio' che manca ai controesempi in cui le direzionali esistono ma $v\\mapsto D_vf$ non e' lineare. <b>Corollario.</b> $|D_vf(x_0)|\\le|\\nabla f(x_0)|$ per Cauchy-Schwarz, con massimo raggiunto per $v$ parallelo a $\\nabla f$: il gradiente punta nella direzione di massima crescita."},

{type:6, topic:"Dimostrazione del teorema del differenziale totale (n=2)",
 q:"Dimostri che se le parziali esistono in un intorno di (x0,y0) e sono continue nel punto, allora f e' differenziabile.",
 prov:"Programma ufficiale del corso, blocco «calcolo differenziale»",
 model:"<b>Strategia.</b> Spezzare l'incremento in due passi, uno per variabile, e applicare a ciascuno il teorema di Lagrange (valor medio) in una variabile; la continuita' delle parziali converte il valore in un punto intermedio nel valore in $(x_0,y_0)$ a meno di infinitesimi. <b>Passo 1 — decomposizione.</b> $$f(x_0+h,y_0+k)-f(x_0,y_0)=\\underbrace{[f(x_0+h,y_0+k)-f(x_0,y_0+k)]}_{\\text{varia }x}+\\underbrace{[f(x_0,y_0+k)-f(x_0,y_0)]}_{\\text{varia }y}.$$ <b>Passo 2 — Lagrange.</b> Sul primo blocco, a $y=y_0+k$ fissato, esiste $\\theta_1\\in(0,1)$: $$f(x_0+h,y_0+k)-f(x_0,y_0+k)=\\frac{\\partial f}{\\partial x}(x_0+\\theta_1 h,\\,y_0+k)\\,h.$$ Sul secondo, esiste $\\theta_2\\in(0,1)$: $$f(x_0,y_0+k)-f(x_0,y_0)=\\frac{\\partial f}{\\partial y}(x_0,\\,y_0+\\theta_2 k)\\,k.$$ <b>Passo 3 — continuita'.</b> Poiche' $f_x,f_y$ sono continue in $(x_0,y_0)$: $$\\frac{\\partial f}{\\partial x}(x_0+\\theta_1 h,y_0+k)=f_x(x_0,y_0)+\\varepsilon_1,\\qquad\\frac{\\partial f}{\\partial y}(x_0,y_0+\\theta_2 k)=f_y(x_0,y_0)+\\varepsilon_2,$$ con $\\varepsilon_1,\\varepsilon_2\\to0$ quando $(h,k)\\to(0,0)$. <b>Passo 4 — chiusura.</b> Sommando: $$\\Delta f=f_x(x_0,y_0)\\,h+f_y(x_0,y_0)\\,k+\\varepsilon_1 h+\\varepsilon_2 k,$$ e $|\\varepsilon_1 h+\\varepsilon_2 k|\\le(|\\varepsilon_1|+|\\varepsilon_2|)\\,|(h,k)|=o(|(h,k)|)$. E' esattamente la definizione di differenziabilita' con $\\nabla f(x_0,y_0)=(f_x,f_y)$. $\\blacksquare$"},

{type:6, topic:"Condizione del secondo ordine per estremi liberi",
 q:"Sia x0 un punto critico. Dimostri il criterio dell'hessiana per distinguere minimo, massimo, sella.",
 prov:"Programma ufficiale del corso, blocco «calcolo differenziale»",
 model:"<b>Contesto.</b> $x_0$ interno, $f\\in C^2$, $\\nabla f(x_0)=0$ (condizione necessaria del primo ordine: se $\\nabla f\\ne0$, lungo $-\\nabla f$ la funzione decresce e non c'e' estremo). Da Taylor: $$f(x_0+h)-f(x_0)=\\tfrac12\\,h^{T}H\\,h+o(|h|^2),\\qquad H=H_f(x_0).$$ <b>Idea.</b> Il segno dell'incremento e' governato dalla forma quadratica $Q(h)=h^{T}Hh$; $H$ e' simmetrica (Schwarz), quindi per il teorema spettrale ha autovalori reali $\\lambda_1\\le\\dots\\le\\lambda_n$ e vale $\\lambda_1|h|^2\\le Q(h)\\le\\lambda_n|h|^2$. <b>Definita positiva</b> ($\\lambda_1>0$): $Q(h)\\ge\\lambda_1|h|^2$, e per $|h|$ piccolo $\\tfrac12\\lambda_1|h|^2$ domina l'$o(|h|^2)$, dunque $f(x_0+h)>f(x_0)$: minimo locale stretto. <b>Definita negativa</b> ($\\lambda_n<0$): per simmetria, massimo locale stretto. <b>Indefinita</b> ($\\lambda_1<0<\\lambda_n$): lungo l'autovettore di $\\lambda_n$ cresce, lungo quello di $\\lambda_1$ decresce: sella, nessun estremo. <b>In due variabili.</b> Con $\\det H=\\lambda_1\\lambda_2$ e $\\operatorname{tr}H=f_{xx}+f_{yy}$: $\\det H>0,\\ f_{xx}>0\\Rightarrow$ minimo; $\\det H>0,\\ f_{xx}<0\\Rightarrow$ massimo; $\\det H<0\\Rightarrow$ sella. <b>Caso semidefinito</b> ($\\det H=0$, qualche $\\lambda=0$): il termine quadratico si annulla lungo il nucleo e l'$o(|h|^2)$ decide — il criterio del secondo ordine NON conclude, servono ordini superiori."},

{type:6, topic:"Controesempio: parziali esistono, funzione non continua",
 q:"Esibisca una funzione che ha entrambe le derivate parziali in (0,0) ma non e' continua in (0,0). Faccia i conti.",
 prov:"Programma ufficiale del corso, blocco «calcolo differenziale»",
 model:"<b>La funzione.</b> $$f(x,y)=\\frac{xy}{x^2+y^2}\\ \\text{per }(x,y)\\ne(0,0),\\qquad f(0,0)=0.$$ <b>Parziali in origine.</b> $$f_x(0,0)=\\lim_{t\\to0}\\frac{f(t,0)-0}{t}=\\lim_{t\\to0}\\frac{0}{t}=0,$$ perche' $f(t,0)=\\frac{t\\cdot0}{t^2}=0$; per simmetria $f_y(0,0)=0$. Entrambe esistono e valgono $0$. <b>Non continua.</b> Lungo la retta $y=mx$: $$f(x,mx)=\\frac{x\\cdot mx}{x^2+m^2x^2}=\\frac{m}{1+m^2},$$ costante ma DIPENDENTE da $m$: lungo $y=x$ vale $\\tfrac12$, lungo $y=0$ vale $0$. Il limite in $(0,0)$ non esiste, quindi $f$ non e' continua in $(0,0)$. <b>Morale.</b> L'esistenza delle parziali guarda solo lungo gli assi $y=0$ e $x=0$, dove $f\\equiv0$; e' cieca a cio' che accade sulle altre rette. Poiche' differenziabile $\\Rightarrow$ continua, questa $f$ non e' differenziabile pur avendo tutte le parziali. E' il controesempio che smonta l'equazione ingenua 'parziali $=$ derivabilita''."},

{type:6, topic:"Controesempio: tutte le direzionali, ma non differenziabile",
 q:"Esibisca una funzione con tutte le derivate direzionali in (0,0) che non e' differenziabile. Perche' fallisce?",
 prov:"Programma ufficiale del corso, blocco «calcolo differenziale»",
 model:"<b>La funzione.</b> $$f(x,y)=\\frac{x^2y}{x^4+y^2}\\ \\text{per }(x,y)\\ne(0,0),\\qquad f(0,0)=0.$$ <b>Tutte le direzionali.</b> Per $v=(a,b)$, $|v|=1$: $$D_vf(0,0)=\\lim_{t\\to0}\\frac{f(ta,tb)}{t}=\\lim_{t\\to0}\\frac{1}{t}\\cdot\\frac{t^2a^2\\cdot tb}{t^4a^4+t^2b^2}=\\lim_{t\\to0}\\frac{a^2b}{t^2a^4+b^2}.$$ Se $b\\ne0$ vale $\\frac{a^2b}{b^2}=\\frac{a^2}{b}$; se $b=0$ vale $0$. In ogni caso il limite ESISTE: tutte le derivate direzionali esistono. In particolare $f_x(0,0)=f_y(0,0)=0$, quindi $\\nabla f(0,0)=(0,0)$. <b>Perche' non e' differenziabile — due argomenti.</b> (i) Se lo fosse, dovrebbe valere $D_vf=\\nabla f\\cdot v=0$ per ogni $v$; ma $D_{(1,1)/\\sqrt2}f\\ne0$ (la formula $\\frac{a^2}{b}$ con $a=b$ da' $\\frac{\\sqrt2}{2}$): la mappa $v\\mapsto D_vf$ NON e' lineare in $v$. Contraddizione. (ii) Ancora piu' forte: lungo la parabola $y=x^2$, $$f(x,x^2)=\\frac{x^2\\cdot x^2}{x^4+x^4}=\\frac12,$$ mentre $f(0,0)=0$: $f$ non e' nemmeno continua in $(0,0)$. <b>Morale.</b> Anche l'esistenza di TUTTE le direzionali non basta: la differenziabilita' richiede che $v\\mapsto D_vf$ sia lineare (e il resto uniformemente $o(|h|)$), non solo che ogni limite direzionale esista."},

{type:6, topic:"Controesempio di Schwarz: derivate miste diverse",
 q:"Mostri con i conti una funzione le cui derivate seconde miste in (0,0) sono diverse.",
 prov:"Programma ufficiale del corso, blocco «calcolo differenziale»",
 model:"<b>La funzione.</b> $$f(x,y)=\\frac{xy(x^2-y^2)}{x^2+y^2}\\ \\text{per }(x,y)\\ne(0,0),\\qquad f(0,0)=0.$$ <b>Prime parziali sugli assi.</b> Servono $f_x(0,y)$ e $f_y(x,0)$. Per $y\\ne0$: $$f_x(0,y)=\\lim_{t\\to0}\\frac{f(t,y)-f(0,y)}{t}=\\lim_{t\\to0}\\frac{y(t^2-y^2)}{t^2+y^2}=\\frac{y(-y^2)}{y^2}=-y.$$ Per $x\\ne0$: $$f_y(x,0)=\\lim_{t\\to0}\\frac{f(x,t)-f(x,0)}{t}=\\lim_{t\\to0}\\frac{x(x^2-t^2)}{x^2+t^2}=\\frac{x\\cdot x^2}{x^2}=x.$$ (E $f_x(0,0)=0=f_y(0,0)$ dagli assi.) <b>Miste in origine.</b> Derivo $f_x(0,y)=-y$ rispetto a $y$: $$\\frac{\\partial^2 f}{\\partial y\\partial x}(0,0)=\\frac{\\partial}{\\partial y}(-y)\\Big|_{0}=-1.$$ Derivo $f_y(x,0)=x$ rispetto a $x$: $$\\frac{\\partial^2 f}{\\partial x\\partial y}(0,0)=\\frac{\\partial}{\\partial x}(x)\\Big|_{0}=+1.$$ Dunque le due miste in origine valgono $-1$ e $+1$: sono diverse. <b>Perche' non contraddice Schwarz.</b> Le miste esistono ovunque ma NON sono continue in $(0,0)$: manca l'ipotesi del teorema. Schwarz non e' violato, e' semplicemente inapplicabile — ed e' proprio questo che il controesempio deve mostrare."},

{type:6, topic:"La gerarchia delle implicazioni",
 q:"Metta in ordine le nozioni — parziali, direzionali, differenziabile, continua, C1 — dicendo quali frecce valgono e quali no, con un controesempio per ogni freccia mancante.",
 prov:"Programma ufficiale del corso, blocco «calcolo differenziale»",
 model:"<b>La catena che VALE.</b> $$f\\in C^1\\ \\Rightarrow\\ \\text{differenziabile}\\ \\Rightarrow\\ \\begin{cases}\\text{continua}\\\\ \\text{tutte le direzionali, con }D_vf=\\nabla f\\cdot v\\end{cases}\\ \\Rightarrow\\ \\text{esistono le parziali.}$$ <b>Le frecce che NON si invertono.</b> <b>(a) Parziali $\\not\\Rightarrow$ continua/differenziabile:</b> $\\frac{xy}{x^2+y^2}$ ha le parziali in $(0,0)$ ma non e' continua. <b>(b) Direzionali tutte $\\not\\Rightarrow$ differenziabile:</b> $\\frac{x^2y}{x^4+y^2}$ ha tutte le direzionali ma non e' continua (ne' differenziabile) in $(0,0)$. <b>(c) Continua $+$ parziali $\\not\\Rightarrow$ differenziabile:</b> serve la linearita' di $v\\mapsto D_vf$, che puo' mancare anche con $f$ continua. <b>(d) Differenziabile $\\not\\Rightarrow C^1$:</b> $(x^2+y^2)\\sin\\frac{1}{\\sqrt{x^2+y^2}}$ e' differenziabile in $(0,0)$ ma le parziali non sono continue li'. <b>Ordine mnemonico.</b> $C^1$ e' la piu' forte, poi differenziabile, poi il ventaglio {continua, direzionali}, infine le parziali (la piu' debole). Un esaminatore chiede quasi sempre di ESIBIRE il controesempio della freccia mancante: enunciare la gerarchia senza i controesempi vale meta'."},

{type:6, topic:"Hessiana semidefinita, gradiente e piano tangente: le domande-trabocchetto",
 q:"Perche' un'hessiana semidefinita non decide l'estremo? Cosa dice il gradiente sulla direzione di crescita? Un grafico puo' avere un piano tangente 'visivo' senza essere differenziabile?",
 prov:"Programma ufficiale del corso, blocco «calcolo differenziale»",
 model:"<b>(1) Hessiana semidefinita.</b> Se $H$ e' semidefinita positiva ($\\lambda_i\\ge0$, qualcuno $=0$), lungo il nucleo di $H$ la forma quadratica $Q(h)=h^{T}Hh$ si annulla e l'incremento $f(x_0+h)-f(x_0)=\\tfrac12 Q(h)+o(|h|^2)$ resta governato dall'$o(|h|^2)$, cioe' da termini di ordine $\\ge3$ che il secondo ordine non vede. Le tre funzioni $x^2+y^4$ (minimo), $x^2-y^4$ (sella), $x^2$ (minimo non stretto) hanno TUTTE la stessa hessiana $\\operatorname{diag}(2,0)$ in $(0,0)$ ma esiti diversi: percio' il criterio del secondo ordine tace e bisogna studiare $f$ direttamente (segno lungo il nucleo, ordini superiori). <b>(2) Il gradiente.</b> Da $D_vf=\\nabla f\\cdot v$ e Cauchy-Schwarz, $|D_vf|\\le|\\nabla f|$ con uguaglianza per $v=\\nabla f/|\\nabla f|$: il gradiente indica la direzione di MASSIMA crescita e il suo modulo e' la pendenza massima. E' inoltre ortogonale agli insiemi di livello $\\{f=c\\}$, perche' lungo un livello $D_vf=0$, cioe' $v\\perp\\nabla f$. <b>(3) Piano tangente 'visivo'.</b> No: un grafico puo' avere lungo ogni direzione una retta tangente (tutte le direzionali esistono) e tuttavia NON un vero piano tangente. Il piano $z=f(x_0)+\\nabla f(x_0)\\cdot(x-x_0)$ e' tangente nel senso forte solo se $f$ e' differenziabile — cioe' se approssima $f$ con errore $o(|h|)$ in TUTTE le direzioni simultaneamente. Nei controesempi (es. $\\frac{x^2y}{x^4+y^2}$) le rette tangenti direzionali esistono ma non si saldano in un piano: l'occhio vede tangenza lungo ogni raggio, la definizione la nega perche' l'errore non e' uniformemente $o(|h|)$. Differenziabilita' $=$ esistenza di un vero piano tangente, non di infinite rette tangenti scoordinate."},

{type:6, topic:"Enunciato e dimostrazione: regola della catena",
 q:"Enunci la regola di derivazione delle funzioni composte, dal caso $f(\\gamma(t))$ al caso generale con prodotto di jacobiane, e dimostri il caso della curva.",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>Enunciato (caso generale).</b> Se $g:\\mathbb{R}^n\\to\\mathbb{R}^m$ e' differenziabile in $x_0$ e $f:\\mathbb{R}^m\\to\\mathbb{R}^k$ e' differenziabile in $g(x_0)$, allora $f\\circ g$ e' differenziabile in $x_0$ e la sua jacobiana e' il PRODOTTO delle jacobiane: $$J_{f\\circ g}(x_0)=J_f(g(x_0))\\,J_g(x_0).$$ <b>Caso curva.</b> Per $f:\\mathbb{R}^n\\to\\mathbb{R}$ e $\\gamma:\\mathbb{R}\\to\\mathbb{R}^n$: $\\frac{d}{dt}f(\\gamma(t))=\\nabla f(\\gamma(t))\\cdot\\gamma'(t)$. <b>Dimostrazione del caso curva.</b> Poni $x_0=\\gamma(t)$, incremento $h=\\gamma(t+s)-\\gamma(t)$. Per la differenziabilita' di $f$: $$f(\\gamma(t+s))-f(\\gamma(t))=\\nabla f(x_0)\\cdot h+o(|h|).$$ Divido per $s$: $$\\frac{f(\\gamma(t+s))-f(\\gamma(t))}{s}=\\nabla f(x_0)\\cdot\\frac{\\gamma(t+s)-\\gamma(t)}{s}+\\frac{o(|h|)}{s}.$$ <b>Dove morde la differenziabilita'.</b> Il primo termine tende a $\\nabla f(x_0)\\cdot\\gamma'(t)$ (derivabilita' di $\\gamma$). Per il resto: $|h|=|\\gamma(t+s)-\\gamma(t)|\\sim|\\gamma'(t)|\\,|s|$, dunque $\\frac{o(|h|)}{s}=\\frac{o(|h|)}{|h|}\\cdot\\frac{|h|}{s}\\to0\\cdot|\\gamma'(t)|=0$. Serve proprio la differenziabilita' di $f$ (non le sole direzionali): garantisce l'o-piccolo uniforme. Passando al limite si ottiene la tesi. $\\boxed{\\text{c.v.d.}}$"},

{type:6, topic:"Dimostrazione: Taylor al secondo ordine per restrizione",
 q:"Dimostri la formula di Taylor al secondo ordine restringendo $f$ al segmento. Perche' serve $f\\in C^2$?",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>Idea.</b> Riportare tutto a una variabile lungo il segmento $x_0+th$, $t\\in[0,1]$. Poni $\\varphi(t)=f(x_0+th)$. <b>Passo 1 (derivate di $\\varphi$ via chain rule).</b> $$\\varphi'(t)=\\nabla f(x_0+th)\\cdot h=\\sum_i \\partial_i f\\,h_i.$$ Derivando di nuovo (chain rule applicata a ciascun $\\partial_i f$): $$\\varphi''(t)=\\sum_{i,j}\\partial_j\\partial_i f(x_0+th)\\,h_i h_j=h^T H(x_0+th)\\,h.$$ <b>Passo 2 (Taylor in una variabile).</b> Per $\\varphi$ su $[0,1]$, resto di Lagrange: esiste $\\theta\\in(0,1)$ con $$\\varphi(1)=\\varphi(0)+\\varphi'(0)+\\tfrac12\\varphi''(\\theta).$$ <b>Passo 3 (tradurre).</b> $\\varphi(1)=f(x_0+h)$, $\\varphi(0)=f(x_0)$, $\\varphi'(0)=\\nabla f(x_0)\\cdot h$, $\\varphi''(\\theta)=h^T H(x_0+\\theta h)h$: si ottiene la forma di Lagrange. La forma di Peano segue dalla continuita' di $H$: $H(x_0+\\theta h)=H(x_0)+o(1)$ per $h\\to0$, e $h^T o(1)\\,h=o(|h|^2)$. <b>Dove morde $C^2$.</b> Serve $f\\in C^2$ per due motivi: (i) l'esistenza e continuita' di $\\varphi''$, cioe' delle parziali seconde, per poter applicare Taylor a $\\varphi$; (ii) la SIMMETRIA dell'hessiana (Schwarz) affinche' $h^T H h$ sia ben definita e la forma quadratica sia quella attesa. $\\boxed{\\text{c.v.d.}}$"}

];
