// Lavagne di teoria — blocco «differenziale, Taylor, massimi e minimi» — orale Analisi Vettoriale
LAV.differenziale = [

{type:6, topic:"Enunciato: differenziabilita', gradiente e o-piccolo",
 q:"Enunci la definizione di differenziabilita' per $f:\\mathbb{R}^n\\to\\mathbb{R}$ in un punto e ne deduca i rapporti con la continuita' e con le derivate direzionali. Quali implicazioni sono strette?",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>Definizione.</b> $f$ e' differenziabile in $x_0$ se esiste un vettore $L\\in\\mathbb{R}^n$ tale che $$f(x_0+h)=f(x_0)+L\\cdot h+o(|h|)\\qquad(h\\to0),$$ cioe' $\\lim_{h\\to0}\\frac{f(x_0+h)-f(x_0)-L\\cdot h}{|h|}=0$. Il funzionale lineare $h\\mapsto L\\cdot h$ e' il <b>differenziale</b> $df_{x_0}$; il vettore $L$ e' unico e coincide col <b>gradiente</b> $\\nabla f(x_0)=(\\partial_1 f,\\dots,\\partial_n f)$. <b>Perche' unico.</b> Prendendo $h=t e_i$ e mandando $t\\to0$ si isola $L_i=\\partial_i f(x_0)$: le componenti di $L$ sono forzate ad essere le parziali. <b>Conseguenze.</b> (i) differenziabile $\\Longrightarrow$ continua, perche' il secondo membro tende a $f(x_0)$; (ii) differenziabile $\\Longrightarrow$ per ogni versore $v$ esiste $D_v f(x_0)=\\nabla f(x_0)\\cdot v$ (formula del gradiente). <b>Implicazioni strette.</b> Nessuna delle due inverse vale: l'esistenza di tutte le derivate direzionali NON basta per la differenziabilita' (ne' per la continuita'). La differenziabilita' e' propriamente piu' forte dell'insieme di tutte le direzionali."},

{type:6, topic:"Dimostrazione: differenziabile implica continua e direzionali",
 q:"Dimostri che se $f$ e' differenziabile in $x_0$ allora e' continua in $x_0$ ed esistono tutte le derivate direzionali con $D_v f(x_0)=\\nabla f(x_0)\\cdot v$.",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>Ipotesi.</b> $f(x_0+h)=f(x_0)+\\nabla f(x_0)\\cdot h+R(h)$ con $R(h)=o(|h|)$. <b>Passo 1 (continuita').</b> $|f(x_0+h)-f(x_0)|\\le|\\nabla f(x_0)|\\,|h|+|R(h)|$ per Cauchy-Schwarz. Il primo addendo tende a $0$; il secondo e' $o(|h|)$, dunque anch'esso $\\to0$. Quindi $f(x_0+h)\\to f(x_0)$, cioe' continuita'. <b>Passo 2 (direzionali).</b> Fissato un versore $v$, poni $h=tv$ con $t\\to0$: $$\\frac{f(x_0+tv)-f(x_0)}{t}=\\frac{\\nabla f(x_0)\\cdot(tv)+R(tv)}{t}=\\nabla f(x_0)\\cdot v+\\frac{R(tv)}{t}.$$ <b>Dove morde l'ipotesi.</b> Poiche' $R(tv)=o(|tv|)=o(|t|)$ e $|v|=1$, si ha $\\frac{R(tv)}{t}\\to0$. Passando al limite $t\\to0$ esiste il rapporto e vale $D_v f(x_0)=\\nabla f(x_0)\\cdot v$. <b>Osservazione.</b> Senza l'o-piccolo uniforme in direzione (cioe' con la sola esistenza delle direzionali) il resto non si controlla e la formula del gradiente puo' cadere. $\\boxed{\\text{c.v.d.}}$"},

{type:6, topic:"Controesempio: tutte le direzionali ma non differenziabile",
 q:"Esibisca una funzione con tutte le derivate direzionali in $(0,0)$ che non sia differenziabile la'. Faccia il conto e spieghi perche' non contraddice il teorema.",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>La funzione.</b> $f(x,y)=\\dfrac{xy^2}{x^2+y^2}$ per $(x,y)\\neq(0,0)$, $f(0,0)=0$. E' continua in $0$ (in polari $|f|=|r\\cos\\theta\\sin^2\\theta|\\le r\\to0$). <b>Direzionali.</b> Lungo $v=(a,b)$, $|v|=1$: $$\\frac{f(ta,tb)-0}{t}=\\frac{t^3 ab^2/(t^2)}{t}=ab^2.$$ Esiste per ogni $v$: $D_v f(0)=ab^2$. In particolare $\\partial_x f=\\partial_y f=0$ (poni $b=0$ e poi $a=0$), quindi $\\nabla f(0)=0$. <b>Test di differenziabilita'.</b> Se lo fosse, dovrebbe valere $f(h,k)=\\nabla f\\cdot(h,k)+o(|(h,k)|)=o(\\rho)$, con $\\rho=\\sqrt{h^2+k^2}$. Ma $$\\frac{f(h,k)}{\\rho}=\\frac{hk^2}{(h^2+k^2)^{3/2}}$$ lungo $h=k$ vale $\\frac{h^3}{(2h^2)^{3/2}}=\\frac{1}{2\\sqrt2}\\neq0$: il limite non e' $0$. Non differenziabile. <b>Perche' non contraddice nulla.</b> La formula $D_v f=\\nabla f\\cdot v$ dovrebbe dare $D_v f=0$ per ogni $v$, mentre $D_v f=ab^2$: proprio il fatto che $v\\mapsto D_v f$ NON sia lineare in $v$ certifica la non differenziabilita'. L'esistenza delle direzionali e' condizione necessaria ma non sufficiente."},

{type:6, topic:"Enunciato: teorema del differenziale totale",
 q:"Enunci il teorema del differenziale totale. Perche' e' il criterio operativo per la differenziabilita', e in che senso l'implicazione e' stretta?",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>Enunciato.</b> Sia $f:\\Omega\\subseteq\\mathbb{R}^n\\to\\mathbb{R}$, $\\Omega$ aperto, $x_0\\in\\Omega$. Se tutte le derivate parziali $\\partial_i f$ esistono in un intorno di $x_0$ e sono continue in $x_0$, allora $f$ e' differenziabile in $x_0$. <b>Perche' e' operativo.</b> Verificare la definizione richiede di stimare un limite in due (o $n$) variabili, spesso scomodo; il teorema riduce tutto a un controllo per una variabile alla volta: si calcolano le parziali (conto meccanico) e se ne verifica la continuita'. In pratica: ogni funzione $C^1$ e' differenziabile. <b>Ipotesi che mordono.</b> Servono le parziali in un INTORNO (non solo nel punto) per poter applicare Lagrange lungo i lati del cammino a gradini, e la continuita' NEL punto per chiudere l'o-piccolo. <b>Implicazione stretta.</b> Il viceversa e' falso: esistono funzioni differenziabili con parziali discontinue nel punto. Prototipo: $g(x,y)=(x^2+y^2)\\sin\\!\\frac{1}{\\sqrt{x^2+y^2}}$ (con $g(0,0)=0$), differenziabile in $0$ con $\\nabla g(0)=0$, ma le sue parziali oscillano e non tendono a $0$ per $(x,y)\\to0$. Dunque «$C^1$» implica «differenziabile» ma non e' equivalente."},

{type:6, topic:"Dimostrazione: teorema del differenziale totale in R^2",
 q:"Dimostri il teorema del differenziale totale in $\\mathbb{R}^2$. Indichi esattamente dove usa l'esistenza in un intorno e dove la continuita' nel punto.",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>Setup.</b> $f_x,f_y$ esistono in un intorno di $(x_0,y_0)$ e sono continue in $(x_0,y_0)$. Incremento $h=(h_1,h_2)$ piccolo. <b>Passo 1 (cammino a gradini).</b> Spezzo: $$f(x_0+h_1,y_0+h_2)-f(x_0,y_0)=\\underbrace{[f(x_0+h_1,y_0+h_2)-f(x_0,y_0+h_2)]}_{A}+\\underbrace{[f(x_0,y_0+h_2)-f(x_0,y_0)]}_{B}.$$ <b>Passo 2 (Lagrange su ciascun tratto).</b> Su $A$, a $y=y_0+h_2$ fissato, $x\\mapsto f(x,y_0+h_2)$ e' derivabile (parziali esistono nell'intorno): $A=f_x(\\xi,y_0+h_2)\\,h_1$ con $\\xi$ fra $x_0$ e $x_0+h_1$. Su $B$: $B=f_y(x_0,\\eta)\\,h_2$ con $\\eta$ fra $y_0$ e $y_0+h_2$. <b>Passo 3 (continuita' per chiudere).</b> Scrivo $f_x(\\xi,y_0+h_2)=f_x(x_0,y_0)+\\varepsilon_1(h)$ e $f_y(x_0,\\eta)=f_y(x_0,y_0)+\\varepsilon_2(h)$; per la continuita' delle parziali in $(x_0,y_0)$, essendo $\\xi\\to x_0$, $\\eta\\to y_0$ quando $h\\to0$, si ha $\\varepsilon_1,\\varepsilon_2\\to0$. Allora $$f(x_0+h)-f(x_0)=f_x h_1+f_y h_2+\\varepsilon_1 h_1+\\varepsilon_2 h_2,$$ e $|\\varepsilon_1 h_1+\\varepsilon_2 h_2|\\le(|\\varepsilon_1|+|\\varepsilon_2|)|h|=o(|h|)$. Questo e' esattamente il differenziale. <b>Dove mordono.</b> L'esistenza in un intorno serve al Passo 2 (Lagrange lungo i lati); la continuita' nel punto serve al Passo 3 (l'o-piccolo). $\\boxed{\\text{c.v.d.}}$"},

{type:6, topic:"Enunciato e dimostrazione: regola della catena",
 q:"Enunci la regola di derivazione delle funzioni composte, dal caso $f(\\gamma(t))$ al caso generale con prodotto di jacobiane, e dimostri il caso della curva.",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>Enunciato (caso generale).</b> Se $g:\\mathbb{R}^n\\to\\mathbb{R}^m$ e' differenziabile in $x_0$ e $f:\\mathbb{R}^m\\to\\mathbb{R}^k$ e' differenziabile in $g(x_0)$, allora $f\\circ g$ e' differenziabile in $x_0$ e la sua jacobiana e' il PRODOTTO delle jacobiane: $$J_{f\\circ g}(x_0)=J_f(g(x_0))\\,J_g(x_0).$$ <b>Caso curva.</b> Per $f:\\mathbb{R}^n\\to\\mathbb{R}$ e $\\gamma:\\mathbb{R}\\to\\mathbb{R}^n$: $\\frac{d}{dt}f(\\gamma(t))=\\nabla f(\\gamma(t))\\cdot\\gamma'(t)$. <b>Dimostrazione del caso curva.</b> Poni $x_0=\\gamma(t)$, incremento $h=\\gamma(t+s)-\\gamma(t)$. Per la differenziabilita' di $f$: $$f(\\gamma(t+s))-f(\\gamma(t))=\\nabla f(x_0)\\cdot h+o(|h|).$$ Divido per $s$: $$\\frac{f(\\gamma(t+s))-f(\\gamma(t))}{s}=\\nabla f(x_0)\\cdot\\frac{\\gamma(t+s)-\\gamma(t)}{s}+\\frac{o(|h|)}{s}.$$ <b>Dove morde la differenziabilita'.</b> Il primo termine tende a $\\nabla f(x_0)\\cdot\\gamma'(t)$ (derivabilita' di $\\gamma$). Per il resto: $|h|=|\\gamma(t+s)-\\gamma(t)|\\sim|\\gamma'(t)|\\,|s|$, dunque $\\frac{o(|h|)}{s}=\\frac{o(|h|)}{|h|}\\cdot\\frac{|h|}{s}\\to0\\cdot|\\gamma'(t)|=0$. Serve proprio la differenziabilita' di $f$ (non le sole direzionali): garantisce l'o-piccolo uniforme. Passando al limite si ottiene la tesi. $\\boxed{\\text{c.v.d.}}$"},

{type:6, topic:"Enunciato: teorema di Schwarz",
 q:"Enunci il teorema di Schwarz sulle derivate seconde miste con le ipotesi esatte. Perche' la continuita' delle miste non e' una clausola decorativa?",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>Enunciato.</b> Sia $f:\\Omega\\to\\mathbb{R}$, $\\Omega\\subseteq\\mathbb{R}^2$ aperto. Se le derivate parziali miste $f_{xy}$ e $f_{yx}$ esistono in un intorno di $(x_0,y_0)$ e almeno una delle due e' continua in $(x_0,y_0)$ (in particolare se $f\\in C^2$), allora $$f_{xy}(x_0,y_0)=f_{yx}(x_0,y_0).$$ <b>Idea della prova.</b> Si considera il rapporto incrementale secondo $$\\Delta=f(x_0+h,y_0+k)-f(x_0+h,y_0)-f(x_0,y_0+k)+f(x_0,y_0),$$ simmetrico in $(h,k)$; applicando Lagrange in un ordine si ottiene $\\approx f_{xy}\\,hk$, nell'altro $\\approx f_{yx}\\,hk$, e la continuita' fa collassare i due valori. <b>Perche' la continuita' non e' decorativa.</b> Le due parziali seconde miste sono a priori limiti CALCOLATI IN ORDINE DIVERSO (prima in $x$ poi in $y$, o viceversa) di rapporti incrementali doppi: scambiare l'ordine di due limiti non e' lecito senza un'ipotesi di uniformita'. La continuita' delle miste e' proprio l'ipotesi che rende lecito lo scambio. Toltala, i due valori possono differire: esiste il controesempio classico con $f_{xy}(0,0)=-1\\neq1=f_{yx}(0,0)$. Non e' un caso patologico raro: e' la regola non appena si perde la continuita'."},

{type:6, topic:"Controesempio: Schwarz senza continuita' delle miste",
 q:"Esibisca il controesempio classico al teorema di Schwarz e calcoli per intero $f_{xy}(0,0)$ e $f_{yx}(0,0)$, mostrando che differiscono.",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>La funzione.</b> $f(x,y)=\\dfrac{xy(x^2-y^2)}{x^2+y^2}$ per $(x,y)\\neq(0,0)$, $f(0,0)=0$. <b>Passo 1 (parziali prime fuori dall'origine).</b> Con conto diretto: $$f_x(x,y)=\\frac{y(x^4+4x^2y^2-y^4)}{(x^2+y^2)^2},\\qquad f_y(x,y)=\\frac{x(x^4-4x^2y^2-y^4)}{(x^2+y^2)^2}.$$ <b>Passo 2 (parziali prime sugli assi).</b> Per $y\\neq0$: $f_x(0,y)=\\frac{y(-y^4)}{y^4}=-y$. Per $x\\neq0$: $f_y(x,0)=\\frac{x\\cdot x^4}{x^4}=x$. (In $0$ entrambe valgono $0$.) <b>Passo 3 (miste in $0$ per definizione).</b> $$f_{xy}(0,0)=\\lim_{k\\to0}\\frac{f_x(0,k)-f_x(0,0)}{k}=\\lim_{k\\to0}\\frac{-k-0}{k}=-1.$$ $$f_{yx}(0,0)=\\lim_{h\\to0}\\frac{f_y(h,0)-f_y(0,0)}{h}=\\lim_{h\\to0}\\frac{h-0}{h}=+1.$$ <b>Conclusione.</b> $f_{xy}(0,0)=-1\\neq1=f_{yx}(0,0)$. <b>Perche' non contraddice Schwarz.</b> Le miste esistono ovunque ma NON sono continue in $(0,0)$ (i loro limiti dipendono dalla direzione d'avvicinamento): manca esattamente l'ipotesi del teorema. Il controesempio non falsifica Schwarz, ne certifica la necessita' dell'ipotesi di continuita'."},

{type:6, topic:"Enunciato: formula di Taylor in piu' variabili",
 q:"Enunci la formula di Taylor al primo e al secondo ordine per $f:\\mathbb{R}^n\\to\\mathbb{R}$, con resto di Peano e di Lagrange, in notazione gradiente-hessiana.",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>Notazione.</b> $\\nabla f$ gradiente; $H=Hf$ matrice hessiana, $H_{ij}=\\partial_i\\partial_j f$, simmetrica quando $f\\in C^2$ (Schwarz). Incremento $h\\in\\mathbb{R}^n$. <b>Ordine 1 (Peano).</b> Se $f$ e' differenziabile in $x_0$: $$f(x_0+h)=f(x_0)+\\nabla f(x_0)\\cdot h+o(|h|).$$ <b>Ordine 2 (Peano).</b> Se $f\\in C^2$ in un intorno di $x_0$: $$f(x_0+h)=f(x_0)+\\nabla f(x_0)\\cdot h+\\tfrac12\\,h^T H(x_0)\\,h+o(|h|^2).$$ <b>Resto di Lagrange (ordine 2).</b> Esiste $\\theta\\in(0,1)$ tale che $$f(x_0+h)=f(x_0)+\\nabla f(x_0)\\cdot h+\\tfrac12\\,h^T H(x_0+\\theta h)\\,h,$$ con l'hessiana valutata in un punto intermedio del segmento. <b>Lettura fisica.</b> $\\nabla f\\cdot h$ e' l'approssimazione lineare (il piano tangente); $\\frac12 h^T H h$ e' la forma quadratica che governa la CURVATURA locale, ed e' esattamente il termine che decide massimi, minimi e selle. La forma di Peano serve per gli sviluppi asintotici e i test di estremo; quella di Lagrange per le stime quantitative con controllo esplicito del resto."},

{type:6, topic:"Dimostrazione: Taylor al secondo ordine per restrizione",
 q:"Dimostri la formula di Taylor al secondo ordine restringendo $f$ al segmento. Perche' serve $f\\in C^2$?",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>Idea.</b> Riportare tutto a una variabile lungo il segmento $x_0+th$, $t\\in[0,1]$. Poni $\\varphi(t)=f(x_0+th)$. <b>Passo 1 (derivate di $\\varphi$ via chain rule).</b> $$\\varphi'(t)=\\nabla f(x_0+th)\\cdot h=\\sum_i \\partial_i f\\,h_i.$$ Derivando di nuovo (chain rule applicata a ciascun $\\partial_i f$): $$\\varphi''(t)=\\sum_{i,j}\\partial_j\\partial_i f(x_0+th)\\,h_i h_j=h^T H(x_0+th)\\,h.$$ <b>Passo 2 (Taylor in una variabile).</b> Per $\\varphi$ su $[0,1]$, resto di Lagrange: esiste $\\theta\\in(0,1)$ con $$\\varphi(1)=\\varphi(0)+\\varphi'(0)+\\tfrac12\\varphi''(\\theta).$$ <b>Passo 3 (tradurre).</b> $\\varphi(1)=f(x_0+h)$, $\\varphi(0)=f(x_0)$, $\\varphi'(0)=\\nabla f(x_0)\\cdot h$, $\\varphi''(\\theta)=h^T H(x_0+\\theta h)h$: si ottiene la forma di Lagrange. La forma di Peano segue dalla continuita' di $H$: $H(x_0+\\theta h)=H(x_0)+o(1)$ per $h\\to0$, e $h^T o(1)\\,h=o(|h|^2)$. <b>Dove morde $C^2$.</b> Serve $f\\in C^2$ per due motivi: (i) l'esistenza e continuita' di $\\varphi''$, cioe' delle parziali seconde, per poter applicare Taylor a $\\varphi$; (ii) la SIMMETRIA dell'hessiana (Schwarz) affinche' $h^T H h$ sia ben definita e la forma quadratica sia quella attesa. $\\boxed{\\text{c.v.d.}}$"},

{type:6, topic:"Estremi liberi: Fermat e test dell'hessiana",
 q:"Enunci e dimostri la condizione necessaria del primo ordine per un estremo interno, e dia la condizione sufficiente del secondo ordine via hessiana, con i criteri operativi.",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>Necessaria (Fermat).</b> Se $x_0$ e' interno a $\\Omega$, punto di estremo locale, e $f$ e' differenziabile in $x_0$, allora $\\nabla f(x_0)=0$. <b>Dimostrazione via restrizione.</b> Fissato $v$, la funzione di una variabile $g(t)=f(x_0+tv)$ ha estremo interno in $t=0$; per Fermat scalare $g'(0)=0$, cioe' $\\nabla f(x_0)\\cdot v=0$. Vale per ogni $v$, quindi $\\nabla f(x_0)=0$. I punti con gradiente nullo sono i <b>critici</b> (candidati). <b>Sufficiente (secondo ordine).</b> Sia $x_0$ critico e $f\\in C^2$. Da Taylor: $f(x_0+h)-f(x_0)=\\tfrac12 h^T H h+o(|h|^2)$. Il segno e' dettato dalla forma quadratica $Q(h)=h^T H(x_0)h$: se $H$ e' <b>definita positiva</b> $\\Rightarrow$ minimo stretto; <b>definita negativa</b> $\\Rightarrow$ massimo stretto; <b>indefinita</b> $\\Rightarrow$ sella. <b>Criteri operativi.</b> Segno di $H$ via <b>minori principali di testa</b> (criterio di Sylvester): tutti $>0$ $\\Rightarrow$ def. positiva; segni alternati $-,+,-,\\dots$ $\\Rightarrow$ def. negativa. In $\\mathbb{R}^2$, con $\\det H=f_{xx}f_{yy}-f_{xy}^2$: se $\\det H>0$ e $f_{xx}>0$ minimo; $\\det H>0$ e $f_{xx}<0$ massimo; $\\det H<0$ sella. <b>Dove morde l'o-piccolo.</b> Con $H$ definita, $Q(h)\\ge c|h|^2$ domina il resto $o(|h|^2)$ in un intorno, fissando il segno; se $H$ e' solo semidefinita il resto NON e' dominato e il test tace."},

{type:6, topic:"Da esaminatore: hessiana semidefinita, il test tace",
 q:"Che cosa fa quando l'hessiana in un punto critico e' semidefinita (o nulla)? Perche' il test del secondo ordine non decide, e come discrimina i casi?",
 prov:"Programma ufficiale del corso, blocco «differenziale, Taylor, massimi e minimi»",
 model:"<b>Perche' tace.</b> Se $H(x_0)$ e' semidefinita (autovalore nullo) o nulla, la forma $Q(h)=h^T H h$ si annulla in qualche direzione: in quella direzione il termine quadratico non domina piu' il resto $o(|h|^2)$ e il segno di $f(x_0+h)-f(x_0)$ e' deciso dagli ordini superiori, che Taylor-2 non vede. Il test del secondo ordine e' quindi INCONCLUSIVO: bisogna guardare piu' in alto. <b>Tre esempi in $(0,0)$ con $H=0$.</b> $f=x^4+y^4$: $f>0$ fuori dall'origine, minimo. $f=-x^4-y^4$: massimo. $f=x^4-y^4$ (oppure $f=x^2 y$): cambia segno vicino a $0$, sella. Stessa hessiana nulla, tre destini diversi: prova che il test tace. <b>L'insidia.</b> $f(x,y)=(y-x^2)(y-2x^2)=y^2-3x^2y+2x^4$. Punto critico in $0$, $H$ semidefinita. Su ogni retta $y=mx$: $f=m^2x^2-3mx^3+2x^4$, per $x\\to0$ domina $m^2x^2\\ge0$ (e su $y=0$, $x\\neq0$: $f=2x^4>0$): lungo OGNI retta c'e' minimo. Ma nella regione $x^2<y<2x^2$ i due fattori hanno segno opposto, quindi $f<0$: avvicinandosi lungo la parabola $y=\\tfrac32 x^2$ si ha $f=-\\tfrac14 x^4<0$. Dunque NON e' minimo in $0$. <b>Cosa si risponde.</b> «Il test dell'hessiana e' inconcluso: passo agli ordini superiori o studio il segno di $f-f(x_0)$ direttamente su curve; il controllo retta-per-retta NON basta, perche' l'estremo puo' rompersi lungo cammini parabolici.»"}

];
