/* frags-teoria/dini.js — teoria per l'orale: Dini, funzioni implicite, Lagrange */
LAV.dini = [

{type:6, topic:"Dini in due variabili: ipotesi ed enunciato",
 q:"Enunci il teorema di Dini (delle funzioni implicite) per $f(x,y)=0$: quali ipotesi servono, cosa afferma la tesi, e da dove esce la formula per $g'$?",
 prov:"Programma ufficiale del corso, blocco «Dini ed estremi vincolati»",
 model:"<b>Ipotesi.</b> Sia $f:A\\subseteq\\mathbb R^2\\to\\mathbb R$ di classe $C^1$ su un aperto $A$ e $P_0=(x_0,y_0)\\in A$ con $f(x_0,y_0)=0$ e $\\partial_y f(x_0,y_0)\\neq0$. <b>Tesi.</b> Esistono un intorno $I$ di $x_0$, un intorno $J$ di $y_0$ e un'unica $g:I\\to J$ di classe $C^1$ con $g(x_0)=y_0$ tale che, in $I\\times J$, $$f(x,y)=0\\iff y=g(x),$$ e inoltre $$g'(x)=-\\frac{\\partial_x f(x,g(x))}{\\partial_y f(x,g(x))}.$$ <b>Perche' ciascuna ipotesi.</b> $f\\in C^1$ garantisce il differenziale e la continuita' delle derivate, da cui la regolarita' $C^1$ di $g$; la condizione $f(P_0)=0$ ci mette SUL luogo di livello zero (senza, non c'e' nulla da risolvere in quel punto); $\\partial_y f(P_0)\\neq0$ e' la condizione portante: geometricamente il gradiente $\\nabla f=(\\partial_x f,\\partial_y f)$ ha componente non nulla lungo $y$, cioe' la retta tangente al luogo non e' verticale, e questo permette di esplicitare $y$ in funzione di $x$. <b>Locale.</b> La tesi e' SOLO locale: fuori dall'intorno il luogo puo' ripiegare e non essere piu' un grafico."},

{type:6, topic:"Dini generale: sistemi e jacobiano parziale",
 q:"Come si generalizza Dini a un sistema $F(\\mathbf x,\\mathbf y)=\\mathbf 0$ con $F$ a valori in $\\mathbb R^m$? Qual e' la condizione che sostituisce $\\partial_y f\\neq0$?",
 prov:"Programma ufficiale del corso, blocco «Dini ed estremi vincolati»",
 model:"<b>Enunciato.</b> Sia $F:A\\subseteq\\mathbb R^n\\times\\mathbb R^m\\to\\mathbb R^m$ di classe $C^1$, con $F(\\mathbf x_0,\\mathbf y_0)=\\mathbf 0$. Si spezza il differenziale in blocchi $D F=[\\,D_{\\mathbf x}F\\mid D_{\\mathbf y}F\\,]$, dove $D_{\\mathbf y}F$ e' la matrice $m\\times m$ delle derivate rispetto alle $m$ variabili da esplicitare. <b>Condizione.</b> $\\det D_{\\mathbf y}F(\\mathbf x_0,\\mathbf y_0)\\neq0$, cioe' il blocco $D_{\\mathbf y}F$ e' invertibile. <b>Tesi.</b> Esiste un'unica $\\mathbf g:I\\subseteq\\mathbb R^n\\to\\mathbb R^m$ di classe $C^1$ con $\\mathbf g(\\mathbf x_0)=\\mathbf y_0$ e $F(\\mathbf x,\\mathbf g(\\mathbf x))=\\mathbf 0$, e $$D\\mathbf g(\\mathbf x)=-\\big(D_{\\mathbf y}F\\big)^{-1}\\,D_{\\mathbf x}F.$$ <b>Perche' il determinante.</b> $\\partial_y f\\neq0$ era il caso scalare $m=1$: chiedere l'invertibilita' di $D_{\\mathbf y}F$ e' l'esatta traduzione — solo cosi' si puo' isolare $\\mathbf y$ risolvendo il sistema linearizzato $D_{\\mathbf x}F\\,d\\mathbf x+D_{\\mathbf y}F\\,d\\mathbf y=\\mathbf 0$. E' la stessa condizione del teorema della funzione inversa applicato alla mappa $(\\mathbf x,\\mathbf y)\\mapsto(\\mathbf x,F)$."},

{type:6, topic:"Derivazione di $g'=-f_x/f_y$",
 q:"Dimostri la formula della derivata della funzione implicita a partire dall'identita' $f(x,g(x))=0$.",
 prov:"Programma ufficiale del corso, blocco «Dini ed estremi vincolati»",
 model:"<b>Punto di partenza.</b> Dini garantisce che $g\\in C^1$ e che vale l'identita' su tutto $I$: $$f(x,g(x))=0\\qquad\\forall x\\in I.$$ Il trucco e' che il primo membro e' la funzione COSTANTE nulla, quindi ogni sua derivata e' nulla. <b>Regola della catena.</b> Derivo rispetto a $x$ la funzione composta $x\\mapsto f(x,g(x))$: $$\\frac{d}{dx}f(x,g(x))=\\partial_x f(x,g(x))\\cdot1+\\partial_y f(x,g(x))\\cdot g'(x)=0.$$ <b>Isolamento.</b> Nell'intorno $\\partial_y f\\neq0$ (per continuita', poiche' e' non nullo in $P_0$ ed $f\\in C^1$), quindi posso dividere: $$g'(x)=-\\frac{\\partial_x f(x,g(x))}{\\partial_y f(x,g(x))}.$$ <b>Lettura.</b> Il segno meno dice che per restare sul livello zero uno spostamento in $x$ va compensato in $y$; la formula e' la pendenza della tangente al luogo $f=0$, coerente col fatto che $\\nabla f$ e' ortogonale alla curva di livello e $g'$ e' l'opposto del rapporto delle componenti del gradiente."},

{type:6, topic:"Derivata seconda della funzione implicita",
 q:"Come si ottiene $g''$? E cosa diventa la formula in un punto critico $g'=0$, utile per classificare un estremo vincolato?",
 prov:"Programma ufficiale del corso, blocco «Dini ed estremi vincolati»",
 model:"<b>Ipotesi in piu'.</b> Se $f\\in C^2$, allora $g\\in C^2$ e posso derivare una seconda volta l'identita' gia' derivata $\\partial_x f+\\partial_y f\\,g'=0$. <b>Seconda derivazione.</b> Ogni parziale e' composta con $(x,g(x))$; applico ancora la catena: $$\\big(f_{xx}+f_{xy}g'\\big)+\\big(f_{yx}+f_{yy}g'\\big)g'+f_y\\,g''=0.$$ Con Schwarz ($f_{xy}=f_{yx}$) e isolando: $$g''(x)=-\\frac{f_{xx}+2f_{xy}\\,g'+f_{yy}\\,(g')^2}{f_y}.$$ <b>Nel punto critico.</b> Se $x_*$ e' un punto critico della funzione implicita, cioe' $g'(x_*)=0$ (equivalente a $f_x=0$ li'), la formula collassa a $$g''(x_*)=-\\frac{f_{xx}}{f_y}.$$ <b>Uso.</b> Il segno di $g''(x_*)$ ne classifica la natura: $g''>0$ minimo, $g''<0$ massimo. Attenzione: la classificazione richiede PRIMA $g'=0$; leggere $g''$ senza aver annullato $g'$ e' l'errore tipico. E la formula ridotta $-f_{xx}/f_y$ vale SOLO nel punto critico, non lungo tutta $I$."},

{type:6, topic:"Moltiplicatori di Lagrange: enunciato",
 q:"Enunci il teorema dei moltiplicatori di Lagrange per un vincolo $g=0$ e per piu' vincoli. Qual e' la condizione di regolarita' sul vincolo?",
 prov:"Programma ufficiale del corso, blocco «Dini ed estremi vincolati»",
 model:"<b>Un vincolo.</b> Siano $f,g\\in C^1$ su un aperto $A\\subseteq\\mathbb R^n$ e $M=\\{g=0\\}$. Se $P_0\\in M$ e' un estremo LOCALE di $f$ ristretta a $M$, e se $\\nabla g(P_0)\\neq\\mathbf 0$, allora esiste $\\lambda\\in\\mathbb R$ tale che $$\\nabla f(P_0)=\\lambda\\,\\nabla g(P_0).$$ <b>Piu' vincoli.</b> Con $g_1,\\dots,g_k$ e $M=\\{g_1=\\dots=g_k=0\\}$, la condizione di regolarita' diventa: i gradienti $\\nabla g_1(P_0),\\dots,\\nabla g_k(P_0)$ sono linearmente indipendenti, cioe' la jacobiana dei vincoli ha rango massimo $k$. Allora esistono $\\lambda_1,\\dots,\\lambda_k$ con $$\\nabla f(P_0)=\\sum_{i=1}^k\\lambda_i\\,\\nabla g_i(P_0).$$ <b>Perche' il rango.</b> La condizione di rango pieno e' cio' che (via Dini) rende $M$ una sottovarieta' liscia di dimensione $n-k$ vicino a $P_0$, con spazio tangente ben definito $T_{P_0}M=\\ker Dg$. E' l'analogo vettoriale di $\\nabla g\\neq0$: senza, il vincolo puo' avere spigoli o autointersezioni e il teorema salta."},

{type:6, topic:"Dimostrazione di Lagrange via Dini",
 q:"Perche' in un estremo vincolato $\\nabla f$ e' parallelo a $\\nabla g$? Dimostri la condizione usando lo spazio tangente al vincolo.",
 prov:"Programma ufficiale del corso, blocco «Dini ed estremi vincolati»",
 model:"<b>Idea.</b> In un estremo vincolato $f$ non puo' variare al primo ordine lungo il vincolo; quindi $\\nabla f$ non ha componente tangente a $M$, cioe' e' tutto ortogonale a $M$, come lo e' $\\nabla g$. <b>Passo 1 (tangente).</b> Poiche' $\\nabla g(P_0)\\neq0$, Dini rende $M$ localmente un grafico liscio; sia $\\gamma:(-\\varepsilon,\\varepsilon)\\to M$ una curva $C^1$ qualunque con $\\gamma(0)=P_0$ e $\\gamma'(0)=\\mathbf v$ vettore tangente arbitrario in $T_{P_0}M$. <b>Passo 2 (stazionarieta').</b> La funzione $h(t)=f(\\gamma(t))$ ha un estremo in $t=0$, quindi $h'(0)=\\nabla f(P_0)\\cdot\\mathbf v=0$. Vale per ogni $\\mathbf v\\in T_{P_0}M$: dunque $\\nabla f(P_0)\\perp T_{P_0}M$. <b>Passo 3 (vincolo).</b> Derivando $g(\\gamma(t))=0$ si ha $\\nabla g(P_0)\\cdot\\mathbf v=0$ per ogni $\\mathbf v$ tangente: dunque anche $\\nabla g(P_0)\\perp T_{P_0}M$. <b>Chiusura.</b> Lo spazio ortogonale a $T_{P_0}M$ (di dimensione $n-1$) e' una retta; $\\nabla f$ e $\\nabla g$ vi appartengono entrambi e $\\nabla g\\neq0$, quindi $\\nabla f=\\lambda\\nabla g$. Il moltiplicatore $\\lambda$ e' il fattore di proporzionalita' fra i due vettori normali."},

{type:6, topic:"Necessaria e non sufficiente",
 q:"Perche' $\\nabla f=\\lambda\\nabla g$ e' condizione solo NECESSARIA per un estremo vincolato? Cosa vi cade dentro oltre agli estremi?",
 prov:"Programma ufficiale del corso, blocco «Dini ed estremi vincolati»",
 model:"<b>Cosa dice davvero.</b> La dimostrazione usa solo $h'(0)=0$: e' una condizione di STAZIONARIETA' di $f$ lungo il vincolo, non di estremalita'. Come $\\nabla f=0$ nel caso libero cattura massimi, minimi E selle, cosi' $\\nabla f=\\lambda\\nabla g$ cattura tutti i punti stazionari vincolati, inclusi selle e flessi ristretti al vincolo. <b>Controesempio pulito.</b> Massimizzare $f(x,y)=x^3$ sul cerchio $g=x^2+y^2-1=0$. Sistema: $\\nabla f=(3x^2,0)$, $\\nabla g=(2x,2y)$, quindi $3x^2=2\\lambda x$, $0=2\\lambda y$, piu' il vincolo. Dalla seconda: $\\lambda=0$ oppure $y=0$. Si trovano i punti stazionari $(\\pm1,0)$ e $(0,\\pm1)$. <b>Verifica.</b> Parametrizzo $x=\\cos t,\\,y=\\sin t$: $f=\\cos^3 t$. In $t=\\tfrac\\pi2$ (punto $(0,1)$) $f=\\cos^3 t$ ha derivata $-3\\cos^2 t\\sin t=0$ ma $\\cos^3 t\\approx -(t-\\tfrac\\pi2)^3$: e' un FLESSO, non un estremo. I veri estremi sono solo $(\\pm1,0)$, con $f=\\pm1$. <b>Morale.</b> Lagrange sputa candidati; la selezione degli estremi veri richiede un test ulteriore (segno, hessiano orlato, o compattezza e confronto dei valori)."},

{type:6, topic:"Controesempio a Dini: il cerchio nei poli",
 q:"Sul cerchio $x^2+y^2=1$ mostri dove Dini in $y$ fallisce e perche' il luogo resta comunque una curva regolare. Che lezione se ne trae?",
 prov:"Programma ufficiale del corso, blocco «Dini ed estremi vincolati»",
 model:"<b>Setup.</b> $f(x,y)=x^2+y^2-1$, luogo $f=0$. Le parziali: $\\partial_x f=2x$, $\\partial_y f=2y$. <b>Dove Dini in $y$ tace.</b> Nei punti $(\\pm1,0)$ si ha $\\partial_y f=0$: l'ipotesi cade, non posso scrivere $y=g(x)$ vicino a quei punti. Il motivo geometrico e' che li' la tangente al cerchio e' VERTICALE, quindi $y$ non e' funzione di $x$ (a destra di $x=1$ non esistono punti, a sinistra ce ne sono due, $\\pm\\sqrt{1-x^2}$). <b>Ma il luogo e' regolare.</b> In quegli stessi punti $\\partial_x f=\\pm2\\neq0$, quindi Dini si applica nell'ALTRA variabile: $x=h(y)=\\pm\\sqrt{1-y^2}$ e' liscia li'. Il cerchio e' ovunque una curva $C^\\infty$ perche' $\\nabla f\\neq\\mathbf 0$ su tutto il luogo. <b>Lezione.</b> Il fallimento di Dini in una variabile NON significa che la curva sia singolare: significa solo che ho scelto la variabile sbagliata da esplicitare. La singolarita' vera arriva solo quando $\\nabla f=\\mathbf 0$, cioe' quando entrambe le parziali si annullano contemporaneamente sul luogo — e sul cerchio non accade mai."},

{type:6, topic:"Controesempio a Dini: il nodo $y^2-x^2=0$",
 q:"Perche' nell'origine il luogo $y^2-x^2=0$ non ammette alcuna funzione implicita, in nessuna variabile? Colleghi la cosa a $\\nabla f$.",
 prov:"Programma ufficiale del corso, blocco «Dini ed estremi vincolati»",
 model:"<b>Il luogo.</b> $f(x,y)=y^2-x^2=(y-x)(y+x)$, quindi $f=0$ e' l'unione delle due rette $y=x$ e $y=-x$: si incrociano nell'origine (un NODO). <b>Le parziali nell'origine.</b> $\\partial_x f=-2x$, $\\partial_y f=2y$; in $(0,0)$ entrambe valgono $0$, dunque $\\nabla f(0,0)=\\mathbf 0$. Nessuna delle due ipotesi di Dini ($\\partial_y f\\neq0$ oppure $\\partial_x f\\neq0$) e' verificata: Dini e' muto in TUTTE le direzioni. <b>Perche' non esiste $g$.</b> In ogni intorno dell'origine per un'ascissa $x_0\\neq0$ ci sono DUE ordinate sul luogo ($y=x_0$ e $y=-x_0$): il grafico di una funzione ammette un solo valore, quindi $y=g(x)$ e' impossibile; per simmetria neanche $x=h(y)$. <b>Il punto profondo.</b> Qui $\\nabla f=\\mathbf 0$ segnala una singolarita' AUTENTICA del luogo: non c'e' una retta tangente, ce ne sono due. E' la differenza rispetto al cerchio nei poli: li' $\\nabla f\\neq0$ e la curva era liscia; qui $\\nabla f=0$ e la curva ha un incrocio. Il gradiente nullo e' la spia della perdita di regolarita'."},

{type:6, topic:"Il vincolo va preso con gradiente non nullo",
 q:"Perche' Lagrange richiede $\\nabla g\\neq0$? Mostri con un esempio che sui punti critici del vincolo un estremo puo' sfuggire al metodo.",
 prov:"Programma ufficiale del corso, blocco «Dini ed estremi vincolati»",
 model:"<b>Ruolo di $\\nabla g\\neq0$.</b> Serve due volte: (i) rende $M=\\{g=0\\}$ una curva/superficie liscia con spazio tangente ben definito (via Dini); (ii) rende sensata l'equazione $\\nabla f=\\lambda\\nabla g$, perche' se $\\nabla g=0$ il secondo membro e' nullo per ogni $\\lambda$ e la condizione degenera in $\\nabla f=0$, che in genere e' falsa. <b>Esempio (cuspide).</b> Minimizzare $f(x,y)=x$ sul vincolo $g(x,y)=y^2-x^3=0$. Il vincolo e' una cuspide con vertice nell'origine, e sul luogo $x=y^{2/3}\\geq0$: dunque $f=x$ ha minimo assoluto in $(0,0)$. <b>Lagrange lo manca.</b> $\\nabla g=(-3x^2,2y)$ si annulla proprio in $(0,0)$; li' $\\nabla f=(1,0)\\neq\\mathbf 0$ e non esiste alcun $\\lambda$ con $(1,0)=\\lambda(0,0)$. Il vero estremo NON soddisfa la condizione dei moltiplicatori. <b>Regola operativa.</b> All'esame: i punti dove $\\nabla g=\\mathbf 0$ (punti critici/singolari del vincolo) vanno cercati ed esaminati A PARTE, uno per uno, perche' Lagrange non li vede. La lista dei candidati e': soluzioni del sistema $\\nabla f=\\lambda\\nabla g$ PIU' i punti singolari del vincolo PIU', se il vincolo ha bordo, il bordo."},

{type:6, topic:"Estremi liberi contro estremi vincolati",
 q:"Sulla stessa $f$, che differenza c'e' fra cercarne gli estremi liberi e quelli su un vincolo? Faccia un esempio dove i due insiemi non coincidono.",
 prov:"Programma ufficiale del corso, blocco «Dini ed estremi vincolati»",
 model:"<b>Libero.</b> Estremo interno di $f$ su un aperto: condizione necessaria $\\nabla f=\\mathbf 0$ (punto critico), natura dal segno dell'Hessiana $H_f$ (definita positiva $\\Rightarrow$ minimo, negativa $\\Rightarrow$ massimo, indefinita $\\Rightarrow$ sella). Si cercano punti dove $f$ e' piatta in OGNI direzione di $\\mathbb R^n$. <b>Vincolato.</b> Estremo di $f$ ristretta a $M=\\{g=0\\}$: condizione $\\nabla f=\\lambda\\nabla g$, cioe' $f$ piatta solo nelle direzioni TANGENTI a $M$. Il gradiente non deve annullarsi, deve solo diventare normale al vincolo. <b>Esempio.</b> $f(x,y)=x^2+y^2$. Libero: unico estremo, il minimo in $(0,0)$ con $\\nabla f=0$. Sul vincolo $x+y=1$: $\\nabla f=(2x,2y)=\\lambda(1,1)$ da' $x=y=\\tfrac12$, punto $(\\tfrac12,\\tfrac12)$ con $f=\\tfrac12$; qui $\\nabla f=(1,1)\\neq\\mathbf 0$. <b>Morale.</b> Gli insiemi di candidati sono diversi: $(0,0)$ non sta sul vincolo, $(\\tfrac12,\\tfrac12)$ non e' critico libero. Il vincolo puo' creare estremi dove $f$ non era piatta e cancellarne dove lo era; l'unico caso in cui un punto e' entrambe le cose e' quando $\\nabla f=0$ E il punto giace su $M$ (allora $\\lambda=0$)."},

{type:6, topic:"Riconoscere la natura del punto senza hessiano orlato",
 q:"Trovati i candidati con Lagrange, come si stabilisce quale e' massimo e quale minimo se l'hessiano orlato non e' in programma?",
 prov:"Programma ufficiale del corso, blocco «Dini ed estremi vincolati»",
 model:"<b>Arma principale: Weierstrass.</b> Se $f$ e' continua e il vincolo $M$ e' CHIUSO e LIMITATO (compatto), $f$ ristretta a $M$ ammette massimo e minimo assoluti, e questi cadono fra i candidati (Lagrange $+$ punti singolari del vincolo $+$ eventuale bordo). Allora basta VALUTARE $f$ sui candidati e confrontare i numeri: il valore piu' grande e' il massimo, il piu' piccolo il minimo. Nessun test di secondo ordine. <b>Esempio.</b> $f=x^3$ sul cerchio (compatto): candidati $(\\pm1,0),(0,\\pm1)$ con valori $f=1,-1,0,0$; dunque max $=1$ in $(1,0)$, min $=-1$ in $(-1,0)$, e i due punti a valore $0$ non sono estremi assoluti — coerente col fatto che erano flessi. <b>Se $M$ non e' compatto.</b> Weierstrass non si applica: bisogna studiare il comportamento di $f$ all'infinito lungo $M$ (o sul bordo) per capire se il candidato e' un estremo globale o solo locale; un candidato puo' essere l'unico punto stazionario e comunque non essere estremo se $f$ e' illimitata sul vincolo. <b>Locale.</b> Per la sola natura LOCALE, in mancanza dell'hessiano orlato, si parametrizza il vincolo vicino al punto (via Dini) e si studia $h(t)=f(\\gamma(t))$ con il test di segno di $h''(0)$, esattamente come per una funzione di una variabile."}

];
