// Lavagne di teoria — blocco «equazioni differenziali ordinarie» — Analisi Vettoriale
LAV.edo = [

{type:6, topic:"Problema di Cauchy e forma integrale equivalente",
 q:"Definisca cosa e' una soluzione del problema di Cauchy $y'=f(t,y)$, $y(t_0)=y_0$, e dimostri l'equivalenza con l'equazione integrale. Perche' si passa alla forma integrale?",
 prov:"Programma ufficiale del corso, blocco «equazioni differenziali ordinarie»",
 model:"<b>Soluzione.</b> Una $y:I\\to\\mathbb{R}$ con $I$ intervallo aperto, $t_0\\in I$, $y\\in C^1(I)$, tale che $(t,y(t))\\in\\operatorname{dom}f$ per ogni $t\\in I$ (il grafico sta dentro il dominio di $f$), $y'(t)=f(t,y(t))$ su $I$ e $y(t_0)=y_0$. <b>Equazione integrale.</b> $$y(t)=y_0+\\int_{t_0}^t f(s,y(s))\\,ds.$$ <b>($\\Rightarrow$).</b> Sia $y\\in C^1$ soluzione del Cauchy. Allora $s\\mapsto f(s,y(s))$ e' continua; integrando $y'(s)=f(s,y(s))$ fra $t_0$ e $t$ e usando il <b>teorema fondamentale del calcolo</b> ($\\int_{t_0}^t y'=y(t)-y(t_0)$) si ottiene la forma integrale, e in $t=t_0$ da' $y(t_0)=y_0$. <b>($\\Leftarrow$).</b> Se $y$ e' continua e soddisfa l'equazione integrale, l'integrando $f(s,y(s))$ e' continuo, quindi per il teorema fondamentale il secondo membro e' $C^1$ con derivata $f(t,y(t))$: dunque $y\\in C^1$, $y'=f(t,y)$, e valutando in $t_0$ l'integrale si annulla e $y(t_0)=y_0$. <b>Perche'.</b> La forma integrale abbassa la richiesta di regolarita' (basta $y$ continua per scriverla) e trasforma il problema in un <b>punto fisso</b> $y=Ty$, l'aggancio a Banach-Caccioppoli. $\\boxed{\\text{c.v.d.}}$"},

{type:6, topic:"Esistenza e unicita' locale (Cauchy-Lipschitz)",
 q:"Enunci il teorema di esistenza e unicita' locale con le ipotesi precise, spieghi il significato di $\\delta=\\min\\{a,b/M\\}$ e perche' e' un risultato in piccolo.",
 prov:"Programma ufficiale del corso, blocco «equazioni differenziali ordinarie»",
 model:"<b>Ipotesi.</b> Sul rettangolo $R=[t_0-a,t_0+a]\\times[y_0-b,y_0+b]$ sia $f$ continua (quindi $|f|\\leq M=\\max_R|f|$) e <b>lipschitziana in $y$ uniformemente in $t$</b>: esiste $L\\geq0$ con $|f(t,y_1)-f(t,y_2)|\\leq L|y_1-y_2|$ per ogni $t$ e $y_1,y_2$. <b>Tesi.</b> Esiste un'unica soluzione $y$ del problema di Cauchy definita su $[t_0-\\delta,t_0+\\delta]$ con $$\\delta=\\min\\Big\\{a,\\tfrac{b}{M}\\Big\\}.$$ <b>Geometria di $b/M$.</b> La soluzione ha pendenza $|y'|=|f|\\leq M$, quindi il suo grafico e' racchiuso nel <b>cono</b> di vertice $(t_0,y_0)$ e pendenze $\\pm M$. Perche' resti dentro $R$ (dove valgono le ipotesi) il cono non deve uscire dai lati orizzontali $y=y_0\\pm b$: questo accade fintanto che $M|t-t_0|\\leq b$, cioe' $|t-t_0|\\leq b/M$; il vincolo $a$ e' la larghezza del rettangolo. <b>In piccolo.</b> $\\delta$ dipende da $M$ e $b$ locali: il teorema garantisce la soluzione solo su un intorno, non su tutto l'asse dei tempi (una soluzione puo' esplodere prima). <b>Nota.</b> Se $f\\in C^1$ in $y$, per il teorema del valor medio $|f(t,y_1)-f(t,y_2)|\\leq(\\max|\\partial_y f|)|y_1-y_2|$ sui compatti: $C^1\\Rightarrow$ localmente lipschitziana."},

{type:6, topic:"Dimostrazione di Picard per punto fisso",
 q:"Dimostri il teorema di esistenza e unicita' locale col metodo delle contrazioni di Picard, indicando dove mordono continuita' e lipschitzianita'.",
 prov:"Programma ufficiale del corso, blocco «equazioni differenziali ordinarie»",
 model:"Si cerca il punto fisso di $(Ty)(t)=y_0+\\int_{t_0}^t f(s,y(s))\\,ds$ su $[t_0-\\delta,t_0+\\delta]$. <b>Passo 1 (spazio completo).</b> Sia $X=\\{y\\in C([t_0-\\delta,t_0+\\delta]):|y(t)-y_0|\\leq b\\}$ con la norma del sup $\\|\\cdot\\|_\\infty$. $C(I)$ con $\\|\\cdot\\|_\\infty$ e' di Banach e $X$ e' un suo sottoinsieme chiuso (limite uniforme di funzioni in $X$ resta in $X$): dunque $X$ e' completo. <b>Passo 2 ($T:X\\to X$).</b> Se $y\\in X$ allora $(s,y(s))\\in R$ e $|(Ty)(t)-y_0|\\leq\\int_{t_0}^t|f|\\,ds\\leq M|t-t_0|\\leq M\\delta\\leq b$ perche' $\\delta\\leq b/M$: qui serve la <b>continuita'</b> di $f$ (limitatezza $M$). <b>Passo 3 (contrazione).</b> $$|(Ty_1)(t)-(Ty_2)(t)|\\leq\\int_{t_0}^t|f(s,y_1)-f(s,y_2)|\\,ds\\leq L\\delta\\,\\|y_1-y_2\\|_\\infty,$$ dove morde la <b>lipschitzianita'</b>. Scegliendo $\\delta$ anche $<1/L$ si ha costante $L\\delta<1$: $T$ e' una contrazione. <b>Passo 4 (Banach-Caccioppoli).</b> Il <b>teorema delle contrazioni</b> su $X$ completo da' esistenza e unicita' del punto fisso $y=Ty$, che per l'equivalenza integrale e' l'unica soluzione del Cauchy. <b>Costruzione.</b> Le <b>iterate di Picard</b> $y_{n+1}=Ty_n$, $y_0(t)\\equiv y_0$, convergono uniformemente alla soluzione. $\\boxed{\\text{c.v.d.}}$"},

{type:6, topic:"Controesempio: senza Lipschitz cade l'unicita'",
 q:"Esibisca un problema di Cauchy con $f$ continua ma non lipschitziana che abbia infinite soluzioni. Perche' cio' non contraddice Cauchy-Lipschitz e in che senso Peano e' ottimale?",
 prov:"Programma ufficiale del corso, blocco «equazioni differenziali ordinarie»",
 model:"<b>Problema.</b> $y'=3y^{2/3}$, $y(0)=0$. Qui $f(y)=3y^{2/3}$ e' continua su $\\mathbb{R}$. <b>Non lipschitziana in $0$.</b> $\\frac{|f(y)-f(0)|}{|y-0|}=\\frac{3|y|^{2/3}}{|y|}=3|y|^{-1/3}\\to+\\infty$ per $y\\to0$: il rapporto incrementale esplode, nessun $L$ lo limita in un intorno di $0$. <b>Le soluzioni.</b> Verifica diretta: $y\\equiv0$ da' $y'=0=3\\cdot0$, ok; $y=t^3$ da' $y'=3t^2$ e $3y^{2/3}=3(t^3)^{2/3}=3t^2$, ok. Piu' in generale, per ogni $c\\geq0$ la funzione $$y_c(t)=\\begin{cases}0,&t\\leq c\\\\(t-c)^3,&t>c\\end{cases}$$ e' $C^1$ (si raccorda con derivata $0$ in $c$) e risolve lo stesso Cauchy: <b>infinite</b> soluzioni. <b>Nessuna contraddizione.</b> Cauchy-Lipschitz richiede la lipschitzianita' in $y$, qui violata proprio in $y=0$: l'unicita' non e' garantita e infatti cade. <b>Peano e' ottimale.</b> Il <b>teorema di Peano</b> ($f$ solo continua $\\Rightarrow$ esiste almeno una soluzione locale) qui garantisce l'esistenza — e infatti soluzioni ce ne sono — ma non l'unicita'; il controesempio mostra che con la sola continuita' non si puo' pretendere di piu': l'unicita' e' esattamente il di piu' che compra la lipschitzianita'."},

{type:6, topic:"Soluzione massimale e fuga dai compatti",
 q:"Definisca soluzione massimale e intervallo massimale di esistenza; enunci il teorema di fuga dai compatti e descriva le modalita' con cui una soluzione «scompare» a tempo finito.",
 prov:"Programma ufficiale del corso, blocco «equazioni differenziali ordinarie»",
 model:"<b>Prolungamento.</b> Una soluzione $\\tilde y$ su $\\tilde I\\supsetneq I$ che coincide con $y$ su $I$ e' un prolungamento di $y$. Una soluzione e' <b>massimale</b> se non ammette prolungamenti propri; il suo dominio $(\\alpha,\\beta)$ e' l'<b>intervallo massimale di esistenza</b> ed e' aperto. <b>Esistenza e unicita' della massimale.</b> Sotto le ipotesi di Cauchy-Lipschitz (f continua e localmente lipschitziana in $y$ sull'aperto $\\Omega=\\operatorname{dom}f$) ogni dato iniziale determina un'<b>unica</b> soluzione massimale: si incollano tutte le soluzioni locali, che per unicita' coincidono sulle intersezioni. <b>Fuga dai compatti.</b> Se $\\beta<+\\infty$, allora per ogni compatto $K\\subset\\Omega$ esiste $t<\\beta$ oltre il quale $(t,y(t))\\notin K$: il grafico <b>esce definitivamente da ogni compatto</b>. Equivalentemente $(t,y(t))$ tende alla frontiera di $\\Omega$ (in senso lato, comprendente l'infinito) per $t\\to\\beta^-$. <b>Due modalita' di fuga.</b> (i) <b>Esplosione in modulo</b>: $|y(t)|\\to+\\infty$ per $t\\to\\beta^-$ (blow-up). (ii) <b>Avvicinamento alla frontiera</b>: $(t,y(t))$ si avvicina a $\\partial\\Omega$ dove $f$ smette di essere definita, pur restando limitato. Simmetricamente in $\\alpha$. La morale: se $\\beta$ e' finito, qualcosa di brutto succede, e la fuga dice esattamente cosa cercare."},

{type:6, topic:"Controesempio: esistenza solo in piccolo con $f\\in C^\\infty$",
 q:"Mostri che anche con $f$ regolarissima l'esistenza puo' essere solo locale. Risolva $y'=y^2$, $y(0)=y_0>0$, e spieghi cosa manca perche' la soluzione sia globale.",
 prov:"Programma ufficiale del corso, blocco «equazioni differenziali ordinarie»",
 model:"<b>Equazione.</b> $y'=y^2$, $y(0)=y_0>0$. Il campo $f(t,y)=y^2$ e' di classe $C^\\infty$ su tutto $\\mathbb{R}^2$: Cauchy-Lipschitz vale ovunque, la soluzione massimale esiste ed e' unica. <b>Separazione.</b> Per $y\\neq0$, $\\frac{y'}{y^2}=1$, cioe' $-\\frac{d}{dt}\\frac1y=1$; integrando da $0$ a $t$: $-\\frac1{y(t)}+\\frac1{y_0}=t$, da cui $$y(t)=\\frac{y_0}{1-y_0 t}.$$ <b>Intervallo massimale.</b> Per $y_0>0$ il denominatore si annulla in $t=1/y_0$ e la soluzione (che parte in $t=0$) vive su $(-\\infty,\\,1/y_0)$; per $t\\to(1/y_0)^-$ si ha $y(t)\\to+\\infty$: <b>esplosione in tempo finito</b> $T=1/y_0$, coerente con la fuga dai compatti. <b>Nessuna contraddizione.</b> Cauchy-Lipschitz e' un teorema locale: non promette mai esistenza globale, solo su un intorno di $t_0$. Qui $\\beta=1/y_0$ e' finito e il blow-up e' proprio il modo previsto di terminare. <b>Cosa manca.</b> La crescita di $f$ in $y$ e' <b>superlineare</b> ($\\sim y^2$): l'integrale $\\int^{\\infty}dy/y^2$ converge, e questo permette al tempo di raggiungere l'infinito in un tempo finito. L'ipotesi che compra la globalita' e' la <b>sublinearita'</b> $|f|\\leq A+B|y|$, qui violata."},

{type:6, topic:"Esistenza globale sotto crescita sublineare",
 q:"Enunci e dimostri che, se $f$ e' continua e $|f(t,y)|\\leq A(t)+B(t)|y|$ con $A,B$ continue, ogni soluzione massimale e' globale nei tempi.",
 prov:"Programma ufficiale del corso, blocco «equazioni differenziali ordinarie»",
 model:"<b>Enunciato.</b> Sia $f$ continua su $J\\times\\mathbb{R}$ ($J$ intervallo dei tempi), localmente lipschitziana in $y$, con la <b>stima sublineare</b> $|f(t,y)|\\leq A(t)+B(t)|y|$, $A,B\\in C(J)$, $A,B\\geq0$. Allora ogni soluzione massimale e' definita su tutto $J$. <b>Dimostrazione.</b> Sia $y$ massimale su $(\\alpha,\\beta)$; mostro $\\beta=\\sup J$ (analogo a sinistra). Dalla forma integrale, per $t\\geq t_0$, $$|y(t)|\\leq|y_0|+\\int_{t_0}^t\\big(A(s)+B(s)|y(s)|\\big)ds.$$ Su un compatto $[t_0,\\tau]\\subset J$ pongo $\\bar A=\\int_{t_0}^\\tau A$, $\\bar B=\\max B$; allora $|y(t)|\\leq(|y_0|+\\bar A)+\\int_{t_0}^t\\bar B\\,|y(s)|\\,ds$. Per il <b>lemma di Gronwall</b> $$|y(t)|\\leq(|y_0|+\\bar A)\\,e^{\\bar B(t-t_0)}\\leq(|y_0|+\\bar A)\\,e^{\\bar B(\\tau-t_0)},$$ una <b>stima a priori</b> finita su $[t_0,\\tau]$. <b>Conclusione.</b> Se fosse $\\beta<\\sup J$, prendendo $\\tau=\\beta$ la soluzione resterebbe limitata, dunque $(t,y(t))$ starebbe in un compatto di $J\\times\\mathbb{R}$ fino a $\\beta$: contraddice il <b>teorema di fuga dai compatti</b>, che impone la fuga se $\\beta$ e' interno a $J$. Quindi $\\beta=\\sup J$ e la soluzione e' globale. $\\boxed{\\text{c.v.d.}}$"},

{type:6, topic:"Lemma di Gronwall, unicita' e dipendenza continua",
 q:"Dimostri il lemma di Gronwall e lo usi per provare unicita' e dipendenza continua dal dato iniziale.",
 prov:"Programma ufficiale del corso, blocco «equazioni differenziali ordinarie»",
 model:"<b>Enunciato.</b> $u\\geq0$ continua, $K\\geq0$ continua, e $u(t)\\leq C+\\int_{t_0}^t K(s)u(s)\\,ds$ per $t\\geq t_0$; allora $$u(t)\\leq C\\,\\exp\\Big(\\int_{t_0}^t K(s)\\,ds\\Big).$$ <b>Dimostrazione.</b> Sia $v(t)=C+\\int_{t_0}^t Ku$. Allora $v'=Ku\\leq Kv$ (perche' $u\\leq v$ e $K\\geq0$), cioe' $v'-Kv\\leq0$. Moltiplico per il <b>fattore integrante</b> $e^{-\\int_{t_0}^t K}>0$: $\\frac{d}{dt}\\big(v(t)e^{-\\int_{t_0}^t K}\\big)\\leq0$. Integrando da $t_0$ a $t$ (con $v(t_0)=C$): $v(t)e^{-\\int_{t_0}^t K}\\leq C$, cioe' $v(t)\\leq Ce^{\\int_{t_0}^t K}$; poiche' $u\\leq v$, la tesi. <b>Unicita'.</b> Siano $y_1,y_2$ soluzioni dello stesso Cauchy con $f$ $L$-lipschitziana. Posto $u=|y_1-y_2|$, dalla forma integrale $u(t)\\leq\\int_{t_0}^t L\\,u(s)\\,ds$, cioe' Gronwall con $C=0$: $u(t)\\leq0$, dunque $y_1\\equiv y_2$. <b>Dipendenza continua.</b> Con dati $y_1(t_0),y_2(t_0)$ diversi, $u(t)\\leq|y_1(t_0)-y_2(t_0)|+\\int_{t_0}^t L\\,u$; Gronwall da' $$|y_1(t)-y_2(t)|\\leq|y_1(t_0)-y_2(t_0)|\\,e^{L|t-t_0|}:$$ la soluzione dipende con continuita' (anzi lipschitzianamente sui compatti) dal dato iniziale, con crescita al piu' esponenziale della discrepanza."},

{type:6, topic:"Equazioni risolubili elementarmente",
 q:"Elenchi e giustifichi i metodi risolutivi per: separabili, lineari del primo ordine, Bernoulli, Eulero.",
 prov:"Programma ufficiale del corso, blocco «equazioni differenziali ordinarie»",
 model:"<b>(a) Separabili $y'=g(t)h(y)$.</b> Dove $h(y)\\neq0$ scrivo $\\frac{y'}{h(y)}=g(t)$ e integro: $\\int\\frac{dy}{h(y)}=\\int g(t)\\,dt+c$. <b>Avvertenza:</b> gli zeri $h(y^*)=0$ danno le soluzioni costanti $y\\equiv y^*$, che la divisione per $h$ <b>perde</b>: vanno aggiunte a mano. <b>(b) Lineare $y'+a(t)y=b(t)$.</b> Fattore integrante $\\mu=e^{A(t)}$, $A'=a$: $(\\mu y)'=\\mu(y'+ay)=\\mu b$, quindi $$y(t)=e^{-A(t)}\\Big(\\int e^{A(t)}b(t)\\,dt+c\\Big).$$ <b>(c) Bernoulli $y'+a(t)y=b(t)y^\\alpha$, $\\alpha\\neq0,1$.</b> Divido per $y^\\alpha$ e pongo $z=y^{1-\\alpha}$, cosi' $z'=(1-\\alpha)y^{-\\alpha}y'$; l'equazione diventa <b>lineare</b>: $z'+(1-\\alpha)a(t)z=(1-\\alpha)b(t)$, risolubile con (b). <b>(d) Eulero $t^2y''+aty'+by=0$.</b> Cerco $y=t^\\lambda$ ($t>0$): $t^2\\lambda(\\lambda-1)t^{\\lambda-2}+at\\lambda t^{\\lambda-1}+bt^\\lambda=0$ da' l'<b>equazione indiciale</b> $\\lambda(\\lambda-1)+a\\lambda+b=0$. Radici reali distinte $\\lambda_1,\\lambda_2$: base $t^{\\lambda_1},t^{\\lambda_2}$; radice doppia: $t^\\lambda,t^\\lambda\\ln t$; complesse $\\alpha\\pm i\\beta$: $t^\\alpha\\cos(\\beta\\ln t),t^\\alpha\\sin(\\beta\\ln t)$. Equivalente alla sostituzione $t=e^s$, che la trasforma in lineare a coefficienti costanti in $s$."},

{type:6, topic:"Lineari a coefficienti costanti di ordine $n$",
 q:"Enunci la struttura dello spazio delle soluzioni di un'equazione lineare a coefficienti costanti, la base per i vari tipi di radici, il metodo di somiglianza e il caso di risonanza.",
 prov:"Programma ufficiale del corso, blocco «equazioni differenziali ordinarie»",
 model:"<b>Struttura.</b> Per $L y=y^{(n)}+a_{n-1}y^{(n-1)}+\\dots+a_0 y=g(t)$: le soluzioni dell'<b>omogenea</b> $Ly=0$ formano uno spazio vettoriale di dimensione $n$ (l'operatore evoluzione fissa $n$ costanti d'integrazione); quelle della completa formano lo <b>spazio affine</b> $y_p+\\ker L$, con $y_p$ una particolare. <b>Polinomio caratteristico.</b> $p(\\lambda)=\\lambda^n+\\dots+a_0$; ogni radice contribuisce alla base. Radice <b>reale semplice</b> $\\lambda$: $e^{\\lambda t}$. Radice reale di <b>molteplicita'</b> $m$: $e^{\\lambda t},te^{\\lambda t},\\dots,t^{m-1}e^{\\lambda t}$. Coppia <b>complessa</b> $\\alpha\\pm i\\beta$ (semplice): $e^{\\alpha t}\\cos\\beta t,\\;e^{\\alpha t}\\sin\\beta t$ (parte reale e immaginaria di $e^{(\\alpha+i\\beta)t}$). <b>Somiglianza.</b> Se $g(t)=e^{\\mu t}(P(t)\\cos\\nu t+Q(t)\\sin\\nu t)$ si cerca $y_p$ della stessa forma con polinomi indeterminati di grado $\\max(\\deg P,\\deg Q)$. <b>Risonanza.</b> Se $\\mu+i\\nu$ e' radice di $p$ con molteplicita' $m$, il tentativo va <b>moltiplicato per $t^m$</b> (altrimenti $Ly_p=0$, non $g$). <b>Fisica.</b> L'oscillatore forzato $\\ddot x+\\omega_0^2 x=F\\cos\\omega t$ e' esattamente questo: se $\\omega=\\omega_0$ il termine noto e' gia' soluzione dell'omogenea (radici $\\pm i\\omega_0$), scatta la risonanza, la particolare cresce come $t\\sin\\omega_0 t$ — ampiezza illimitata nel tempo."},

{type:6, topic:"Equazioni autonome ed equilibri",
 q:"Per $y'=f(y)$ con $f$ localmente lipschitziana, dimostri che una soluzione non costante non raggiunge un equilibrio in tempo finito, deducendone monotonia e limiti; discuta la stabilita'.",
 prov:"Programma ufficiale del corso, blocco «equazioni differenziali ordinarie»",
 model:"<b>Equilibri.</b> Gli zeri $f(y^*)=0$ danno le soluzioni costanti $y\\equiv y^*$ (equilibri). <b>Non raggiungibilita' in tempo finito.</b> Sia $y$ non costante e supponiamo per assurdo $y(t_1)=y^*$ per un $t_1$ finito. Allora $y$ e $y\\equiv y^*$ sono due soluzioni dello stesso Cauchy con dato $(t_1,y^*)$; poiche' $f$ e' localmente lipschitziana vale l'<b>unicita' di Cauchy-Lipschitz</b>, dunque coincidono ovunque: $y\\equiv y^*$, contro l'ipotesi. Quindi una soluzione non costante <b>non tocca mai</b> un equilibrio. <b>Confinamento e monotonia.</b> Percio' $y(t)$ resta in un intervallo aperto fra due equilibri consecutivi, dove $f$ non si annulla e per continuita' ha <b>segno costante</b>: $y'=f(y)$ ha segno costante, dunque $y$ e' strettamente <b>monotona</b>. <b>Limiti.</b> Monotona e limitata (fra i due equilibri) $\\Rightarrow$ ha limite $\\ell$ agli estremi del suo intervallo temporale; passando al limite in $y'=f(y)$ si trova $f(\\ell)=0$, cioe' il limite e' un <b>equilibrio</b>. <b>Stabilita'.</b> Dal segno di $f$ attorno a $y^*$: se $f>0$ sotto e $f<0$ sopra, le soluzioni convergono a $y^*$ (asintoticamente stabile); segno opposto, instabile. Criterio infinitesimale: $f'(y^*)<0\\Rightarrow$ asintoticamente stabile, $f'(y^*)>0\\Rightarrow$ instabile. <b>Invarianza temporale:</b> se $y(t)$ e' soluzione, lo e' $y(t+c)$."},

{type:6, topic:"Studio qualitativo: metodo ed esempio logistico",
 q:"Studi qualitativamente $y'=y(1-y)$, $y(0)=y_0$, senza risolverla: illustri prima la sequenza generale di domande, poi la svolga nei tre regimi.",
 prov:"Programma ufficiale del corso, blocco «equazioni differenziali ordinarie»",
 model:"<b>Sequenza generale.</b> (1) Dominio di $f$ e verifica di Cauchy-Lipschitz (esistenza/unicita' locale, i grafici non si incrociano). (2) <b>Soluzioni costanti</b>: zeri di $f$. (3) <b>Segno di $y'=f</b>$ per la monotonia in ogni banda fra equilibri. (4) <b>Segno di $y''$</b> derivando l'equazione: $y''=f_t+f_y\\,y'=f_t+f_y f$ (qui autonoma: $y''=f'(y)f(y)$) per la convessita' e i flessi. (5) <b>Barriere e teorema del confronto</b> per incasellare la soluzione fra sopra/sotto-soluzioni. (6) Comportamento agli estremi dell'intervallo massimale (limiti, blow-up). <b>Logistica $f(y)=y(1-y)$.</b> $f\\in C^\\infty$: ipotesi ok ovunque. Equilibri $y=0,\\,y=1$. Segno: $f>0$ per $0<y<1$ (crescente), $f<0$ per $y<0$ e $y>1$ (decrescente). Convessita': $y''=f'(y)f(y)=(1-2y)\\,y(1-y)$, flesso a $y=1/2$. <b>Tre regimi.</b> $\\;0<y_0<1$: crescente e confinata fra $0$ e $1$, $y\\to1$ per $t\\to+\\infty$ e $y\\to0$ per $t\\to-\\infty$, flesso quando attraversa $1/2$; <b>globale</b> a destra. $\\;y_0>1$: decrescente verso $1$ per $t\\to+\\infty$ (globale a destra), convessa; all'indietro cresce e <b>esplode in tempo finito</b> ($\\alpha$ finito). $\\;y_0<0$: decrescente, $y\\to0^-$ per $t\\to-\\infty$ e <b>blow-up a $-\\infty$</b> in tempo finito a destra. Coerente con la sublinearita' violata ($f\\sim-y^2$ per $|y|$ grande)."}

];
