/* frags-teoria/fondamenti.js — teoria per l'orale: topologia in R^n, continuita', differenziabilita' */
LAV.fondamenti = [

{type:6, topic:"Topologia di $\\mathbb{R}^n$: aperti, chiusi e il fatto che non sono opposti",
 q:"Definisca palla, intorno, punto interno, di frontiera e di accumulazione. Aperto e chiuso sono uno il contrario dell'altro?",
 prov:"Programma ufficiale del corso, blocco «topologia, continuita' e differenziabilita'»",
 model:"<b>Metrica di base.</b> Norma euclidea $\\|x\\|=\\sqrt{\\sum_{i=1}^n x_i^2}$; palla aperta $B_r(x_0)=\\{x:\\|x-x_0\\|<r\\}$. Un <b>intorno</b> di $x_0$ e' un insieme che contiene una $B_r(x_0)$. <b>Classificazione dei punti</b> rispetto a $A\\subseteq\\mathbb{R}^n$: $x$ e' <b>interno</b> se $\\exists r>0:\\,B_r(x)\\subseteq A$; <b>esterno</b> se e' interno al complementare; <b>di frontiera</b> se ogni $B_r(x)$ incontra sia $A$ sia $A^c$. $x$ e' <b>di accumulazione</b> se ogni $B_r(x)$ contiene un punto di $A$ diverso da $x$ (nota: non serve che $x\\in A$). <b>Definizioni.</b> $A$ e' <b>aperto</b> se ogni suo punto e' interno; <b>chiuso</b> se contiene tutti i suoi punti di accumulazione, equivalentemente se $A^c$ e' aperto. <b>Perche' non sono opposti.</b> Aperto e chiuso non sono negazioni l'uno dell'altro: sono proprieta' distinte. $\\mathbb{R}^n$ e $\\emptyset$ sono <b>entrambi</b> aperti e chiusi (i soli due, per connessione di $\\mathbb{R}^n$); $[0,1)\\subset\\mathbb{R}$ non e' <b>ne'</b> aperto (il punto $0$ non e' interno) <b>ne'</b> chiuso (il punto di accumulazione $1$ manca). <b>Da esaminatore.</b> \\\"Il singoletto $\\{0\\}$?\\\" Chiuso e non aperto. \\\"$\\mathbb{Q}$?\\\" Ne' aperto ne' chiuso, e la sua chiusura e' tutto $\\mathbb{R}$: la distinzione aperto/chiuso e' la grammatica di tutto il resto."},

{type:6, topic:"Equivalenza delle norme in $\\mathbb{R}^n$",
 q:"Enunci il teorema di equivalenza delle norme in $\\mathbb{R}^n$. Cosa garantisce in concreto, e perche' in dimensione infinita e' falso?",
 prov:"Programma ufficiale del corso, blocco «topologia, continuita' e differenziabilita'»",
 model:"<b>Enunciato.</b> In $\\mathbb{R}^n$ tutte le norme sono equivalenti: date due norme $\\|\\cdot\\|_a,\\|\\cdot\\|_b$ esistono $0<c\\le C$ con $$c\\,\\|x\\|_a\\le\\|x\\|_b\\le C\\,\\|x\\|_a\\qquad\\forall x.$$ <b>Cosa significa.</b> Le due norme inducono la <b>stessa topologia</b>: gli stessi aperti, gli stessi intorni, quindi gli stessi limiti, le stesse successioni convergenti e di Cauchy, gli stessi insiemi compatti e continui le stesse funzioni. In pratica: convergenza in $\\|\\cdot\\|_2$, in $\\|\\cdot\\|_1$ e in $\\|\\cdot\\|_\\infty$ sono la <b>stessa</b> cosa. <b>Perche' e' vero.</b> La sfera unitaria $\\{\\|x\\|_2=1\\}$ e' compatta (Heine-Borel), ogni norma e' una funzione continua e per Weierstrass ha su di essa minimo $c>0$ e massimo $C$: da qui le disuguaglianze per omogeneita'. La <b>compattezza della sfera</b> e' il motore. <b>Perche' cade in dimensione infinita.</b> In uno spazio di funzioni, es. $C[0,1]$, la sfera unitaria NON e' compatta, e $\\|\\cdot\\|_\\infty$ e $\\|\\cdot\\|_1$ non sono equivalenti: $f_n(t)=t^n$ ha $\\|f_n\\|_1\\to0$ ma $\\|f_n\\|_\\infty=1$. <b>Conseguenza operativa.</b> In $\\mathbb{R}^n$ per studiare limiti e continuita' si sceglie la norma comoda (spesso $\\|\\cdot\\|_\\infty$ per stimare componente per componente) senza cambiare nessuna conclusione."},

{type:6, topic:"Compattezza: Heine-Borel e Weierstrass",
 q:"Definisca compatto per ricoprimenti, enunci Heine-Borel, e dimostri Weierstrass sui compatti.",
 prov:"Programma ufficiale del corso, blocco «topologia, continuita' e differenziabilita'»",
 model:"<b>Definizione (ricoprimenti).</b> $K$ e' <b>compatto</b> se da ogni ricoprimento aperto $\\{A_i\\}$, $K\\subseteq\\bigcup_i A_i$, si estrae un sottoricoprimento finito. <b>Heine-Borel.</b> In $\\mathbb{R}^n$: $K$ compatto $\\Leftrightarrow$ $K$ chiuso e limitato. (In dimensione infinita $\\Leftarrow$ e' falso: la sfera unitaria e' chiusa, limitata, non compatta — stessa radice del blocco sulle norme.) In $\\mathbb{R}^n$ vale anche la <b>compattezza sequenziale</b>: da ogni successione in $K$ si estrae una sottosuccessione convergente in $K$ (Bolzano-Weierstrass). <b>Weierstrass.</b> Se $f:K\\to\\mathbb{R}$ e' continua e $K$ compatto (non vuoto), $f$ ha massimo e minimo. <b>Dimostrazione (via successioni).</b> Passo 1: $f(K)$ e' limitato. Se no, esiste $x_n\\in K$ con $f(x_n)\\to+\\infty$; per compattezza sequenziale $x_{n_k}\\to x^*\\in K$, e per continuita' $f(x_{n_k})\\to f(x^*)$ finito, assurdo. Passo 2: sia $M=\\sup f(K)$, finito. Prendo $x_n\\in K$ con $f(x_n)\\to M$; estraggo $x_{n_k}\\to x^*\\in K$; per continuita' $f(x^*)=\\lim f(x_{n_k})=M$, dunque il sup e' un <b>massimo</b> raggiunto. Analogo per il minimo. $\\;\\boxed{\\text{c.v.d.}}$ <b>Dove mordono le ipotesi.</b> Serve $K$ <b>chiuso</b> (per avere $x^*\\in K$) e <b>limitato</b> (per estrarre): togliere l'una o l'altra fa cadere tutto — $f(x)=x$ su $[0,+\\infty)$ o su $(0,1)$ non ha massimo. Serve la <b>continuita'</b> per passare al limite dentro $f$."},

{type:6, topic:"Connessi e connessi per archi: dove coincidono e dove no",
 q:"Definisca connesso e connesso per archi. Per gli aperti di $\\mathbb{R}^n$ coincidono? Mi dia il controesempio che li separa.",
 prov:"Programma ufficiale del corso, blocco «topologia, continuita' e differenziabilita'»",
 model:"<b>Definizioni.</b> $A$ e' <b>connesso</b> se non si spezza in due aperti (relativi) non vuoti e disgiunti; equivalentemente le sole funzioni continue $A\\to\\{0,1\\}$ sono le costanti. $A$ e' <b>connesso per archi</b> se ogni coppia di punti e' unita da un cammino continuo $\\gamma:[0,1]\\to A$. <b>Implicazione facile.</b> Connesso per archi $\\Rightarrow$ connesso, sempre (un cammino e' immagine continua di un intervallo, che e' connesso). <b>Il viceversa in generale e' FALSO.</b> <b>Controesempio (seno del topologo).</b> $S=\\{(x,\\sin(1/x)):0<x\\le1\\}\\cup(\\{0\\}\\times[-1,1])$. E' <b>connesso</b>: e' la chiusura del grafico connesso, e la chiusura di un connesso e' connessa. NON e' <b>connesso per archi</b>: nessun cammino continuo puo' raggiungere il segmento limite $\\{0\\}\\times[-1,1]$ partendo dal grafico, perche' avvicinandosi a $x=0$ l'ordinata oscilla fra $-1$ e $1$ senza stabilizzarsi, violando la continuita'. <b>Perche' non e' una contraddizione.</b> Le due nozioni sono diverse; l'implicazione vale solo in un verso. <b>Ma per gli APERTI.</b> Se $A\\subseteq\\mathbb{R}^n$ e' <b>aperto</b> e connesso, allora e' connesso per archi (anzi per poligonali). Idea: fissato $x_0$, l'insieme dei punti raggiungibili da $x_0$ con una poligonale in $A$ e' aperto E chiuso in $A$ (le palle sono convesse), quindi per connessione e' tutto $A$. <b>Perche' importa in fisica.</b> Un aperto connesso e' un <b>dominio</b>: e' li' che ha senso il potenziale di un campo conservativo, e la connessione per archi e' cio' che rende ben definito l'integrale di linea fra due punti."},

{type:6, topic:"Limite di funzione di piu' variabili: la definizione e perche' e' piu' forte",
 q:"Definisca $\\lim_{x\\to x_0}f(x)$ per $f:\\mathbb{R}^n\\to\\mathbb{R}$. Perche' e' molto piu' rigido che in una variabile? Come si nega un limite?",
 prov:"Programma ufficiale del corso, blocco «topologia, continuita' e differenziabilita'»",
 model:"<b>Definizione.</b> $\\lim_{x\\to x_0}f(x)=L$ se $$\\forall\\varepsilon>0\\ \\exists\\delta>0:\\ 0<\\|x-x_0\\|<\\delta\\ \\Rightarrow\\ |f(x)-L|<\\varepsilon.$$ <b>Il punto cruciale.</b> In una variabile ci si avvicina a $x_0$ solo da <b>due</b> lati (destra, sinistra). In $\\mathbb{R}^n$ la palla forata $0<\\|x-x_0\\|<\\delta$ contiene <b>infinite direzioni e infiniti cammini</b>: perche' il limite esista e valga $L$, $f$ deve tendere a $L$ lungo OGNI possibile modo di avvicinarsi. Molto piu' facile che fallisca. <b>Tecnica per NEGARE (restrizioni).</b> Se lungo due cammini $\\gamma_1,\\gamma_2$ verso $x_0$ ottengo due valori diversi, il limite non esiste. Basta trovarne due discordanti: rette $y=mx$, o curve $y=x^2$, ecc. <b>Tecnica per PROVARE (coordinate polari).</b> Posto $x=x_0+\\rho(\\cos\\theta,\\sin\\theta)$, se riesco a maggiorare $$|f-L|\\le g(\\rho)\\ \\text{con}\\ g(\\rho)\\to0,\\ \\text{uniformemente in}\\ \\theta,$$ allora il limite e' $L$. <b>Attenzione da esaminatore.</b> Le polari <b>provano</b> solo se la stima e' uniforme in $\\theta$: se la maggiorante dipende ancora da $\\theta$ e non si controlla, non ho concluso nulla — e' l'errore classico. <b>Aggancio.</b> Questa rigidita' e' la ragione per cui continuita' e differenziabilita' in piu' variabili nascondono i controesempi dei blocchi seguenti."},

{type:6, topic:"Controesempio principe: limiti lungo le rette non bastano",
 q:"Studi $\\lim_{(x,y)\\to(0,0)}\\frac{xy}{x^2+y^2}$ e poi $\\frac{x^2y}{x^4+y^2}$. Cosa insegnano insieme?",
 prov:"Programma ufficiale del corso, blocco «topologia, continuita' e differenziabilita'»",
 model:"<b>Primo: $f(x,y)=\\frac{xy}{x^2+y^2}$.</b> Lungo la retta $y=mx$: $$f(x,mx)=\\frac{m x^2}{x^2(1+m^2)}=\\frac{m}{1+m^2},$$ costante lungo ogni retta ma <b>dipendente da $m$</b>: $0$ sull'asse ($m=0$), $\\tfrac12$ sulla bisettrice ($m=1$). Valori diversi lungo cammini diversi $\\Rightarrow$ il limite <b>non esiste</b>. In polari: $f=\\cos\\theta\\sin\\theta=\\tfrac12\\sin2\\theta$, indipendente da $\\rho$ ma funzione di $\\theta$: nessun limite. <b>Secondo: $g(x,y)=\\frac{x^2y}{x^4+y^2}$.</b> Lungo <b>ogni retta</b> $y=mx$: $$g=\\frac{m x^3}{x^4+m^2x^2}=\\frac{m x}{x^2+m^2}\\xrightarrow[x\\to0]{}0,$$ e anche lungo l'asse $y$ ($x=0$) da' $0$. Sembra $0$ lungo tutte le rette. Ma lungo la <b>parabola</b> $y=x^2$: $$g(x,x^2)=\\frac{x^2\\cdot x^2}{x^4+x^4}=\\frac{x^4}{2x^4}=\\frac12\\neq0.$$ Due valori ($0$ e $\\tfrac12$) $\\Rightarrow$ limite inesistente. <b>La morale.</b> Nel primo caso gia' le rette bastano a negare; nel secondo <b>le rette non bastano</b>: la funzione e' costante-nulla lungo tutte le rette eppure non ha limite. Provare il limite lungo le sole rette e' un errore logico. <b>Perche' non contraddice nulla.</b> Non esiste teorema che deduca l'esistenza del limite dal comportamento sulle rette; anticipa il blocco su derivate direzionali (esistono lungo ogni retta ma non implicano continuita')."},

{type:6, topic:"Continuita' vs continuita' separata",
 q:"Definisca continuita' in $\\mathbb{R}^n$ e continuita' separata. La seconda implica la prima?",
 prov:"Programma ufficiale del corso, blocco «topologia, continuita' e differenziabilita'»",
 model:"<b>Continuita' (globale, in $x_0$).</b> $f$ e' continua in $x_0$ se $\\lim_{x\\to x_0}f(x)=f(x_0)$, cioe' avvicinandosi da <b>qualunque direzione</b> nel piano il valore tende a $f(x_0)$. <b>Continuita' separata.</b> $f$ e' continua separatamente in $x_0=(a,b)$ se le due funzioni di una variabile $x\\mapsto f(x,b)$ e $y\\mapsto f(a,y)$ sono continue in $a$ e $b$ rispettivamente: si guarda solo lungo gli assi coordinati passanti per il punto. <b>La separata NON implica la globale.</b> Controesempio: $$f(x,y)=\\frac{xy}{x^2+y^2}\\ ((x,y)\\neq0),\\quad f(0,0)=0.$$ Separatamente in $0$: $f(x,0)=0$ per ogni $x$ e $f(0,y)=0$ per ogni $y$, funzioni costanti nulle, <b>continue</b>. Ma dal blocco precedente $\\lim_{(x,y)\\to0}f=$ inesistente, quindi $f$ <b>non</b> e' continua in $0$. <b>Perche'.</b> La separata controlla solo <b>due</b> cammini (gli assi); la continuita' vera chiede <b>tutti</b> i cammini. La rigidita' del limite multivariato (blocco 5) e' esattamente cio' che separa le due nozioni. <b>Da esaminatore.</b> \\\"Se $f$ e' continua e' separatamente continua?\\\" Si', banalmente: la restrizione di una funzione continua a una retta e' continua. L'implicazione vale solo in questo verso."},

{type:6, topic:"Derivate parziali, direzionali e gradiente: cosa NON garantiscono",
 q:"Definisca derivata parziale e direzionale come limiti. L'esistenza di tutte le direzionali in un punto garantisce continuita' o differenziabilita'?",
 prov:"Programma ufficiale del corso, blocco «topologia, continuita' e differenziabilita'»",
 model:"<b>Definizioni (rapporti incrementali).</b> Derivata parziale $i$-esima: $$\\partial_{x_i}f(x_0)=\\lim_{t\\to0}\\frac{f(x_0+t e_i)-f(x_0)}{t}.$$ Derivata direzionale lungo $v$ (di solito $\\|v\\|=1$): $$D_v f(x_0)=\\lim_{t\\to0}\\frac{f(x_0+t v)-f(x_0)}{t}.$$ Le parziali sono le direzionali lungo gli assi. Il <b>gradiente</b> e' $\\nabla f(x_0)=(\\partial_{x_1}f,\\dots,\\partial_{x_n}f)$. <b>Osservazione chiave.</b> $D_v f(x_0)$ e' la derivata in $t=0$ della funzione di UNA variabile $t\\mapsto f(x_0+tv)$: guarda $f$ solo lungo la <b>retta</b> per $x_0$ in direzione $v$. <b>Cosa NON garantisce.</b> Anche se esistono TUTTE le direzionali in $x_0$ (per ogni $v$), $f$ puo' <b>non essere continua</b> in $x_0$ e a maggior ragione <b>non differenziabile</b>. Ragione: ogni direzionale e' un'informazione lungo una singola retta, ma continuita' e differenziabilita' chiedono un controllo <b>uniforme in tutte le direzioni insieme</b> (cammini non rettilinei compresi). L'esistenza puntuale lungo ogni retta non si assembla in una proprieta' bidimensionale. <b>Ponte al blocco 10.</b> Il controesempio $\\frac{x^2y}{x^4+y^2}$ realizza esattamente questo: tutte le direzionali esistono, la funzione non e' continua. <b>Il verso giusto.</b> E' la differenziabilita' a dare le direzionali gratis, non viceversa (blocco 9)."},

{type:6, topic:"Differenziabilita': definizione, geometria e le tre implicazioni gratuite",
 q:"Definisca la differenziabilita' con il resto $o(\\|h\\|)$. Dimostri che differenziabile implica continua, l'esistenza di tutte le direzionali e la formula $D_v f=\\nabla f\\cdot v$.",
 prov:"Programma ufficiale del corso, blocco «topologia, continuita' e differenziabilita'»",
 model:"<b>Definizione.</b> $f$ e' differenziabile in $x_0$ se esiste un vettore $L$ (che risultera' $=\\nabla f(x_0)$) tale che $$f(x_0+h)=f(x_0)+L\\cdot h+o(\\|h\\|)\\quad(h\\to0),$$ cioe' $\\frac{f(x_0+h)-f(x_0)-L\\cdot h}{\\|h\\|}\\to0$. <b>Geometria.</b> Il grafico ammette in $x_0$ un <b>piano tangente</b> $z=f(x_0)+\\nabla f(x_0)\\cdot(x-x_0)$: l'approssimazione affine sbaglia di un ordine inferiore a $\\|h\\|$. <b>1) Differenziabile $\\Rightarrow$ continua.</b> $f(x_0+h)-f(x_0)=L\\cdot h+o(\\|h\\|)$; entrambi i termini $\\to0$ per $h\\to0$ ($|L\\cdot h|\\le\\|L\\|\\|h\\|$ per Cauchy-Schwarz), dunque $f(x_0+h)\\to f(x_0)$. <b>2) Esistono tutte le direzionali e vale $D_v f=\\nabla f\\cdot v$.</b> Poni $h=tv$ ($\\|v\\|=1$): $$\\frac{f(x_0+tv)-f(x_0)}{t}=\\frac{L\\cdot(tv)+o(|t|)}{t}=L\\cdot v+\\frac{o(|t|)}{t}\\xrightarrow[t\\to0]{}L\\cdot v.$$ Quindi $D_v f(x_0)=L\\cdot v$; in particolare per $v=e_i$ si ha $L_i=\\partial_{x_i}f$, cioe' $L=\\nabla f(x_0)$, e $D_v f=\\nabla f\\cdot v$. $\\;\\boxed{\\text{c.v.d.}}$ <b>Perche' e' potente.</b> Un solo oggetto lineare $\\nabla f$ codifica TUTTE le derivate direzionali (linearita' in $v$), e ne segue che la direzione di massima crescita e' $\\nabla f/\\|\\nabla f\\|$. <b>Cosa NON e' vero al contrario.</b> Esistenza delle parziali (o di tutte le direzionali) $\\not\\Rightarrow$ differenziabilita' (blocco 10). <b>Fisica.</b> $o(\\|h\\|)$ e' l'ordine di ogni sviluppo al primo ordine: e' il linguaggio del lavoro infinitesimo $\\delta W=F\\cdot dr$."},

{type:6, topic:"Controesempio: tutte le direzionali, ma non differenziabile ne' continua",
 q:"Esibisca una funzione con tutte le derivate direzionali in $0$ eppure non differenziabile. Mostri dove salta la formula del gradiente.",
 prov:"Programma ufficiale del corso, blocco «topologia, continuita' e differenziabilita'»",
 model:"<b>La funzione.</b> $$f(x,y)=\\frac{x^2y}{x^4+y^2}\\ ((x,y)\\neq0),\\qquad f(0,0)=0.$$ <b>Direzionali in $0$.</b> Lungo $v=(a,b)$, $\\|v\\|=1$: $$\\frac{f(ta,tb)-0}{t}=\\frac1t\\cdot\\frac{t^2a^2\\,tb}{t^4a^4+t^2b^2}=\\frac{a^2 b}{t^2a^4+b^2}\\xrightarrow[t\\to0]{}\\begin{cases}\\dfrac{a^2}{b}&b\\neq0\\\\[4pt]0&b=0\\end{cases}$$ Il limite esiste per ogni direzione: <b>tutte</b> le direzionali esistono. In particolare le parziali sono $\\partial_x f(0)=0$ (direzione $b=0$) e $\\partial_y f(0)=0$ (direzione $a=0$), quindi $\\nabla f(0)=(0,0)$. <b>La formula del gradiente NON vale.</b> Se $f$ fosse differenziabile dovrebbe essere $D_v f(0)=\\nabla f(0)\\cdot v=0$ per ogni $v$; ma per $b\\neq0$ abbiamo $D_v f(0)=a^2/b\\neq0$. Contraddizione $\\Rightarrow$ $f$ <b>non</b> e' differenziabile in $0$. <b>Non e' nemmeno continua.</b> Lungo $y=x^2$: $f(x,x^2)=\\frac{x^4}{2x^4}=\\tfrac12\\neq0=f(0)$ (stesso conto del blocco 6). <b>Perche' e' coerente.</b> Nessun teorema promette differenziabilita' dalle direzionali; anzi, non essendo continua, non poteva essere differenziabile (per il blocco 9, contronominale della implicazione 1). <b>Da esaminatore.</b> \\\"Le direzionali qui sono lineari in $v$?\\\" No: $D_v f=a^2/b$ non e' della forma $\\nabla f\\cdot v$ — la <b>non-linearita' in $v$</b> e' la firma diagnostica della non-differenziabilita'."},

{type:6, topic:"Dimostrazione: teorema del differenziale totale (condizione sufficiente)",
 q:"Dimostri che se le parziali esistono in un intorno e sono continue in $x_0$ allora $f$ e' differenziabile in $x_0$. Poi mi convinca che la condizione e' solo sufficiente.",
 prov:"Programma ufficiale del corso, blocco «topologia, continuita' e differenziabilita'»",
 model:"<b>Ipotesi.</b> $f:\\mathbb{R}^2\\to\\mathbb{R}$, $\\partial_x f,\\partial_y f$ esistono in un intorno di $x_0=(a,b)$ e sono <b>continue in $x_0$</b>. Tesi: $f$ differenziabile in $x_0$. <b>Idea.</b> Spezzare l'incremento variando una coordinata alla volta e applicare Lagrange su ciascun tratto. <b>Passo 1 (incremento a gradini).</b> Con $h=(h_1,h_2)$: $$f(a+h_1,b+h_2)-f(a,b)=\\underbrace{[f(a+h_1,b+h_2)-f(a,b+h_2)]}_{\\text{vario }x}+\\underbrace{[f(a,b+h_2)-f(a,b)]}_{\\text{vario }y}.$$ <b>Passo 2 (Lagrange su ogni tratto).</b> Fissato $b+h_2$, la funzione $x\\mapsto f(x,b+h_2)$ e' derivabile: esiste $\\xi_1$ fra $a$ e $a+h_1$ con primo tratto $=\\partial_x f(\\xi_1,b+h_2)\\,h_1$. Analogamente esiste $\\xi_2$ fra $b$ e $b+h_2$ con secondo tratto $=\\partial_y f(a,\\xi_2)\\,h_2$. <b>Passo 3 (continuita' delle parziali).</b> Scrivo $\\partial_x f(\\xi_1,b+h_2)=\\partial_x f(x_0)+\\epsilon_1(h)$ e $\\partial_y f(a,\\xi_2)=\\partial_y f(x_0)+\\epsilon_2(h)$, con $\\epsilon_1,\\epsilon_2\\to0$ per $h\\to0$ perche' $(\\xi_1,b+h_2)\\to x_0$, $(a,\\xi_2)\\to x_0$ e le parziali sono <b>continue in $x_0$</b>. Allora $$f(x_0+h)-f(x_0)=\\nabla f(x_0)\\cdot h+\\epsilon_1 h_1+\\epsilon_2 h_2,$$ e $|\\epsilon_1 h_1+\\epsilon_2 h_2|\\le(|\\epsilon_1|+|\\epsilon_2|)\\|h\\|=o(\\|h\\|)$. Questa e' la definizione di differenziabilita'. $\\;\\boxed{\\text{c.v.d.}}$ <b>Dove entra ogni ipotesi.</b> L'esistenza in un <b>intorno</b> serve per applicare Lagrange su tratti interi; la <b>continuita' in $x_0$</b> serve per rendere infinitesimi gli $\\epsilon_i$. <b>Solo sufficiente.</b> $f(x,y)=(x^2+y^2)\\sin\\frac{1}{\\sqrt{x^2+y^2}}$ (e $f(0)=0$) e' <b>differenziabile in $0$</b> con $\\nabla f(0)=0$ (il resto e' $\\rho^2\\sin(1/\\rho)=o(\\rho)$), eppure le parziali <b>non sono continue</b> in $0$ (oscillano). Dunque parziali continue $\\Rightarrow$ differenziabile, ma non il contrario: la classe $C^1$ e' piu' piccola dei differenziabili. <b>Nome.</b> Le funzioni con questa ipotesi si dicono $C^1$; e' l'ipotesi che poi si usa per Schwarz e Taylor nei blocchi successivi."},

{type:6, topic:"Da esaminatore: regola della catena e perche' serve la differenziabilita'",
 q:"Enunci la chain rule con le ipotesi precise, la forma matriciale, il caso $\\frac{d}{dt}f(\\gamma(t))$. Perche' non basta l'esistenza delle parziali?",
 prov:"Programma ufficiale del corso, blocco «topologia, continuita' e differenziabilita'»",
 model:"<b>Enunciato (forma matriciale).</b> Siano $f:\\mathbb{R}^n\\to\\mathbb{R}^m$ <b>differenziabile</b> in $x_0$ e $g:\\mathbb{R}^m\\to\\mathbb{R}^k$ <b>differenziabile</b> in $y_0=f(x_0)$. Allora $g\\circ f$ e' differenziabile in $x_0$ e $$D(g\\circ f)(x_0)=Dg(f(x_0))\\,Df(x_0),$$ prodotto delle matrici jacobiane. Le ipotesi cruciali: differenziabilita' di <b>entrambe</b> nei punti giusti. <b>Caso fisico (curva).</b> Con $\\gamma:\\mathbb{R}\\to\\mathbb{R}^n$ derivabile e $f:\\mathbb{R}^n\\to\\mathbb{R}$ differenziabile: $$\\frac{d}{dt}f(\\gamma(t))=\\nabla f(\\gamma(t))\\cdot\\gamma'(t).$$ E' il conto onnipresente in fisica: la derivata di un'energia lungo una traiettoria, $\\frac{d}{dt}U(\\gamma)=\\nabla U\\cdot\\dot\\gamma$, cioe' potenza $=$ forza per velocita' (a meno di segno); e ogni bilancio energetico lungo un moto. <b>Perche' serve la DIFFERENZIABILITA', non le sole parziali.</b> La dimostrazione usa che $f(y_0+\\eta)-f(y_0)=\\nabla f(y_0)\\cdot\\eta+o(\\|\\eta\\|)$ con $\\eta=f(x_0+h)-f(x_0)$: solo il termine $o(\\|\\eta\\|)$ garantisce che l'errore sia trascurabile, e questo termine <b>esiste solo se $f$ e' differenziabile</b>. <b>Controesempio se si indebolisce.</b> Prendi $f=\\frac{x^2y}{x^4+y^2}$ (blocco 10): ha tutte le parziali in $0$ ma non e' differenziabile. Componendo con $\\gamma(t)=(t,t^2)$ si ha $f(\\gamma(t))=\\tfrac12$ per $t\\neq0$ e $f(\\gamma(0))=0$: la composta non e' nemmeno continua in $0$, quindi $\\frac{d}{dt}f(\\gamma)$ NON esiste, mentre la formula ingenua $\\nabla f(0)\\cdot\\gamma'(0)=0$ darebbe un valore. La sola esistenza delle parziali <b>non</b> autorizza la chain rule. <b>Morale.</b> La chain rule e' il motivo pratico per cui in fisica si pretende $C^1$: e' l'ipotesi che rende lecito derivare lungo le traiettorie."}

];
