/* frags-teoria/integrali.js — teoria per l'orale: Gauss-Green, divergenza, Stokes */
LAV.integrali = [

{type:6, topic:"Gauss-Green nel piano: enunciato e ruolo delle ipotesi",
 q:"Enunci il teorema di Gauss-Green nel piano. Cosa fa ciascuna ipotesi e cosa crolla se cade?",
 prov:"Programma ufficiale del corso, blocco «teoremi integrali»",
 model:"<b>Enunciato.</b> Sia $D\\subset\\mathbb{R}^2$ un <i>dominio regolare</i>: compatto, con frontiera $\\partial D$ unione finita di curve semplici, chiuse, regolari a tratti, orientata <i>positivamente</i> (il dominio resta a sinistra di chi percorre il bordo). Sia $F=(F_1,F_2)$ di classe $C^1$ su un aperto $A$ che contiene $D$, chiusura inclusa. Allora $$\\oint_{\\partial D}F_1\\,dx+F_2\\,dy=\\iint_D\\Big(\\frac{\\partial F_2}{\\partial x}-\\frac{\\partial F_1}{\\partial y}\\Big)\\,dx\\,dy.$$ <b>Ipotesi $C^1$ fino al bordo.</b> Le derivate $\\partial_xF_2,\\partial_yF_1$ devono essere integrabili su tutto $D$. Se il campo fosse $C^1$ solo nell'interno, le derivate potrebbero divergere avvicinandosi a $\\partial D$ e l'integrale doppio perdere senso: per questo si chiede $C^1$ su un aperto che contiene la <i>chiusura</i>, non solo l'interno. <b>Regolarita del bordo.</b> Serve a dare senso a $\\oint_{\\partial D}$ (curva rettificabile con tangente q.o.) e a poter decomporre $D$ in domini normali. <b>Orientazione positiva.</b> Fissa il segno dell'identita: invertire il verso di percorrenza cambia segno al primo membro ma non al secondo, e l'uguaglianza si rompe. E la traccia scalare del teorema di Stokes con normale $\\hat z$: $(\\operatorname{rot}F)\\cdot\\hat z=\\partial_xF_2-\\partial_yF_1$."},

{type:6, topic:"Teorema della divergenza in R^2 e R^3: enunciato",
 q:"Enunci il teorema della divergenza nel piano e nello spazio. Che ruolo ha la normale esterna?",
 prov:"Programma ufficiale del corso, blocco «teoremi integrali»",
 model:"<b>In $\\mathbb{R}^2$.</b> Con $D$ dominio regolare, $\\nu$ normale esterna unitaria su $\\partial D$ e $F=(F_1,F_2)\\in C^1(A)$, $A\\supset D$: $$\\iint_D\\operatorname{div}F\\,dx\\,dy=\\oint_{\\partial D}F\\cdot\\nu\\,ds,\\qquad \\operatorname{div}F=\\partial_xF_1+\\partial_yF_2.$$ <b>In $\\mathbb{R}^3$.</b> Sia $V\\subset\\mathbb{R}^3$ un dominio regolare (compatto, con bordo $\\partial V$ superficie chiusa regolare a tratti, orientata con normale esterna $\\nu$) e $F\\in C^1(A)$, $A\\supset V$. Allora $$\\iiint_V\\operatorname{div}F\\,dV=\\iint_{\\partial V}F\\cdot\\nu\\,dS.$$ <b>Lettura.</b> Il flusso uscente dal bordo eguaglia l'integrale della sorgente $\\operatorname{div}F$; anzi la divergenza <i>e</i> la densita di flusso per unita di volume, $\\operatorname{div}F(p)=\\lim_{V\\to p}\\frac{1}{|V|}\\iint_{\\partial V}F\\cdot\\nu\\,dS$. <b>Ruolo della normale esterna.</b> Sceglierla interna cambia segno al flusso: il segno del teorema e legato univocamente alla scelta <i>esterna</i>. <b>Ruolo di $C^1$.</b> Se $\\operatorname{div}F$ non e integrabile su $V$ (singolarita interna, es. campo coulombiano nell'origine), il primo membro non e definito e il teorema non vale come scritto: la singolarita va isolata."},

{type:6, topic:"Teorema di Stokes: enunciato e orientazione coerente",
 q:"Enunci il teorema di Stokes. Cosa significa che bordo e normale sono orientati coerentemente?",
 prov:"Programma ufficiale del corso, blocco «teoremi integrali»",
 model:"<b>Enunciato.</b> Sia $\\Sigma\\subset\\mathbb{R}^3$ una superficie regolare orientata con normale unitaria $n$, il cui bordo $\\partial\\Sigma$ e una curva regolare a tratti orientata <i>coerentemente</i> con $n$ (regola della mano destra). Sia $F\\in C^1(A)$, con $A$ aperto contenente $\\Sigma$. Allora $$\\oint_{\\partial\\Sigma}F\\cdot dr=\\iint_\\Sigma(\\operatorname{rot}F)\\cdot n\\,dS.$$ <b>Cosa dice.</b> La circuitazione di $F$ lungo il bordo eguaglia il flusso del rotore attraverso una qualsiasi superficie che ha quel bordo. <b>Orientazione coerente.</b> Fissa il segno dei due membri: rovesciare $n$ obbliga a rovesciare il verso di $\\partial\\Sigma$, altrimenti l'uguaglianza cade. <b>Ruolo di $C^1$.</b> $\\operatorname{rot}F$ deve essere continuo su $\\Sigma$; una singolarita del campo sulla superficie invalida il membro di destra. <b>Caso piano.</b> Se $\\Sigma$ giace nel piano $xy$ con $n=\\hat z$, allora $(\\operatorname{rot}F)\\cdot\\hat z=\\partial_xF_2-\\partial_yF_1$ e Stokes si riduce esattamente a Gauss-Green: e la stessa identita vista in dimensioni diverse."},

{type:6, topic:"Dimostrazione di Gauss-Green su un dominio normale",
 q:"Dimostri Gauss-Green su un dominio semplice rispetto a un asse e spieghi come si estende.",
 prov:"Programma ufficiale del corso, blocco «teoremi integrali»",
 model:"<b>Passo 1: mezza identita su dominio $y$-semplice.</b> Sia $D=\\{(x,y):a\\le x\\le b,\\ \\varphi(x)\\le y\\le\\psi(x)\\}$ con $\\varphi,\\psi\\in C^1$. Per Fubini e il teorema fondamentale del calcolo $$\\iint_D\\frac{\\partial F_1}{\\partial y}\\,dx\\,dy=\\int_a^b\\!\\Big[F_1(x,\\psi(x))-F_1(x,\\varphi(x))\\Big]dx.$$ <b>Passo 2: il bordo, orientato positivamente.</b> Percorro il tratto inferiore $y=\\varphi(x)$ da $x=a$ a $x=b$ e quello superiore $y=\\psi(x)$ da $x=b$ a $x=a$; i lati verticali danno $dx=0$. Quindi $$\\oint_{\\partial D}F_1\\,dx=\\int_a^b F_1(x,\\varphi(x))\\,dx+\\int_b^a F_1(x,\\psi(x))\\,dx=\\int_a^b\\!\\Big[F_1(x,\\varphi(x))-F_1(x,\\psi(x))\\Big]dx.$$ Confrontando: $\\oint_{\\partial D}F_1\\,dx=-\\iint_D\\partial_yF_1\\,dx\\,dy$. <b>Passo 3: l'altra meta.</b> Su un dominio $x$-semplice, in modo speculare, $\\oint_{\\partial D}F_2\\,dy=+\\iint_D\\partial_xF_2\\,dx\\,dy$. Su un dominio regolare (normale rispetto a entrambi gli assi) valgono entrambe; sommandole si ottiene Gauss-Green. <b>Passo 4: estensione per decomposizione.</b> Un dominio generale si taglia in un numero finito di pezzi normali. Gli integrali doppi si sommano; gli integrali di linea sui tagli <i>interni</i> si cancellano perche ogni taglio e percorso <b>due volte in versi opposti</b> dai bordi dei due pezzi adiacenti. Sopravvive solo $\\oint_{\\partial D}$, e l'identita si estende."},

{type:6, topic:"Da Gauss-Green alla forma della divergenza (campo ruotato)",
 q:"Come si ricava il teorema della divergenza nel piano da Gauss-Green?",
 prov:"Programma ufficiale del corso, blocco «teoremi integrali»",
 model:"<b>Idea.</b> La forma della divergenza e Gauss-Green applicato al <i>campo ruotato di 90 gradi</i>. <b>Geometria del bordo.</b> Parametrizzo $\\partial D$ per lunghezza d'arco con tangente $T=(x',y')$; per l'orientazione positiva la normale <i>esterna</i> e $T$ ruotata di $-90^\\circ$, cioe $\\nu=(y',-x')$. Dunque $\\nu\\,ds=(dy,-dx)$ e $$F\\cdot\\nu\\,ds=F_1\\,dy-F_2\\,dx.$$ <b>Applico Gauss-Green</b> nella forma $\\oint_{\\partial D}P\\,dx+Q\\,dy=\\iint_D(\\partial_xQ-\\partial_yP)$ con la scelta $P=-F_2$, $Q=F_1$: $$\\oint_{\\partial D}(-F_2\\,dx+F_1\\,dy)=\\iint_D\\big(\\partial_xF_1-\\partial_y(-F_2)\\big)=\\iint_D(\\partial_xF_1+\\partial_yF_2)=\\iint_D\\operatorname{div}F.$$ Il primo membro e proprio $\\oint_{\\partial D}F\\cdot\\nu\\,ds$. <b>Conclusione.</b> $\\iint_D\\operatorname{div}F\\,dx\\,dy=\\oint_{\\partial D}F\\cdot\\nu\\,ds$. La circuitazione della forma tangenziale (rotore, Gauss-Green) e il flusso della forma normale (divergenza) sono la stessa identita letta con il campo ruotato: $\\operatorname{div}F=\\operatorname{rot}_{\\!z}(RF)$ con $R$ rotazione di $90^\\circ$."},

{type:6, topic:"Stokes come Gauss-Green trasportato dalla parametrizzazione",
 q:"Perche il teorema di Stokes e Gauss-Green trasportato sulla superficie? Ne indichi i passi.",
 prov:"Programma ufficiale del corso, blocco «teoremi integrali»",
 model:"<b>Impostazione.</b> Sia $\\Sigma$ l'immagine di $r(u,v)$, $(u,v)\\in D\\subset\\mathbb{R}^2$ dominio regolare, con $n\\,dS=(r_u\\times r_v)\\,du\\,dv$. <b>Passo 1: pull-back della circuitazione.</b> Sul bordo, $dr=r_u\\,du+r_v\\,dv$, quindi $$F\\cdot dr=(F\\cdot r_u)\\,du+(F\\cdot r_v)\\,dv=:P\\,du+Q\\,dv,\\qquad P=F\\cdot r_u,\\ Q=F\\cdot r_v.$$ La circuitazione su $\\partial\\Sigma$ diventa un integrale di linea su $\\partial D$ nel piano dei parametri. <b>Passo 2: Gauss-Green in $(u,v)$.</b> $$\\oint_{\\partial D}P\\,du+Q\\,dv=\\iint_D(\\partial_uQ-\\partial_vP)\\,du\\,dv.$$ <b>Passo 3: cancellazione delle derivate seconde.</b> Con $J_F$ jacobiana di $F$, $\\partial_u(F\\cdot r_v)=(J_Fr_u)\\cdot r_v+F\\cdot r_{uv}$ e $\\partial_v(F\\cdot r_u)=(J_Fr_v)\\cdot r_u+F\\cdot r_{vu}$. Poiche $r_{uv}=r_{vu}$ i termini $F\\cdot r_{uv}$ si elidono, e resta la parte antisimmetrica $$\\partial_uQ-\\partial_vP=(J_Fr_u)\\cdot r_v-(J_Fr_v)\\cdot r_u=(\\operatorname{rot}F)\\cdot(r_u\\times r_v).$$ <b>Passo 4: ritorno alla superficie.</b> $$\\iint_D(\\operatorname{rot}F)\\cdot(r_u\\times r_v)\\,du\\,dv=\\iint_\\Sigma(\\operatorname{rot}F)\\cdot n\\,dS.$$ <b>Orientazione.</b> Il fatto che $\\partial D$ positivamente orientato mappi in $\\partial\\Sigma$ coerente con $n=(r_u\\times r_v)/|r_u\\times r_v|$ e esattamente la regola della mano destra: cambiare l'ordine $u,v$ inverte insieme $n$ e il verso del bordo, come deve essere."},

{type:6, topic:"Trappola: orientazione del bordo e segno",
 q:"Mostri con un conto come un'orientazione sbagliata del bordo fa cadere Gauss-Green.",
 prov:"Programma ufficiale del corso, blocco «teoremi integrali»",
 model:"<b>Dato.</b> $D$ disco unitario, $F=(-y,\\,x)$. Il termine di Gauss-Green e $\\partial_xF_2-\\partial_yF_1=1-(-1)=2$, quindi $$\\iint_D 2\\,dx\\,dy=2\\,\\text{Area}(D)=2\\pi.$$ <b>Bordo corretto (antiorario).</b> $\\gamma(t)=(\\cos t,\\sin t)$, $t\\in[0,2\\pi]$: $-y\\,dx+x\\,dy=(-\\sin t)(-\\sin t)\\,dt+(\\cos t)(\\cos t)\\,dt=dt$, e $\\oint=\\int_0^{2\\pi}dt=2\\pi$. Coincide: l'orientazione antioraria e quella positiva (dominio a sinistra). <b>Bordo sbagliato (orario).</b> Percorrendo $t:2\\pi\\to 0$ ottengo $\\oint=-2\\pi\\ne 2\\pi$. <b>Morale.</b> L'integrale doppio non cambia segno con l'orientazione, quello di linea si: percorrere il bordo nel verso sbagliato falsa il risultato di un segno. All'orale: prima di applicare il teorema, verificare sempre che il bordo lasci il dominio <i>a sinistra</i>. Nota di passaggio: qui $\\oint(x\\,dy-y\\,dx)=2\\,\\text{Area}$, il germe della formula d'area."},

{type:6, topic:"Trappola: dominio con un buco, bordo interno invertito",
 q:"Su una corona circolare, come vanno orientati i due bordi? Faccia il conto.",
 prov:"Programma ufficiale del corso, blocco «teoremi integrali»",
 model:"<b>Dato.</b> Corona $D=\\{1\\le x^2+y^2\\le 4\\}$, campo liscio $F=(-y,\\,x)$, con $\\partial_xF_2-\\partial_yF_1=2$. <b>Membro doppio.</b> $\\iint_D 2\\,dA=2(\\text{Area})=2(4\\pi-\\pi)=6\\pi.$ <b>Il bordo e fatto di due circonferenze.</b> Perche il dominio resti a sinistra, la esterna $C_2$ (raggio 2) va percorsa <b>in senso antiorario</b>, la interna $C_1$ (raggio 1) va percorsa <b>in senso orario</b>. Su una circonferenza di raggio $R$ antioraria, $\\oint(-y\\,dx+x\\,dy)=2\\pi R^2$. Dunque $$\\oint_{C_2}=2\\pi\\cdot 2^2=8\\pi,\\qquad \\oint_{C_1\\ \\text{orario}}=-2\\pi\\cdot 1^2=-2\\pi,$$ e $\\oint_{\\partial D}=8\\pi-2\\pi=6\\pi$, che eguaglia il membro doppio. <b>Se si sbaglia.</b> Percorrendo anche la interna in antiorario si avrebbe $8\\pi+2\\pi=10\\pi\\ne 6\\pi$. <b>Regola.</b> In un dominio con buchi ogni bordo interno va nel verso <i>opposto</i> al bordo esterno; solo cosi il dominio resta uniformemente a sinistra."},

{type:6, topic:"Controesempio: singolarita interna e campo del vortice",
 q:"Il campo del vortice ha rotore nullo ma circuitazione non nulla: perche Gauss-Green non si applica?",
 prov:"Programma ufficiale del corso, blocco «teoremi integrali»",
 model:"<b>Dato.</b> $F=\\Big(\\dfrac{-y}{x^2+y^2},\\ \\dfrac{x}{x^2+y^2}\\Big)$ su $\\mathbb{R}^2\\setminus\\{0\\}$. <b>Rotore.</b> $\\partial_xF_2=\\dfrac{y^2-x^2}{(x^2+y^2)^2}$ e $\\partial_yF_1=\\dfrac{y^2-x^2}{(x^2+y^2)^2}$, quindi $\\partial_xF_2-\\partial_yF_1=0$ ovunque il campo e definito: $F$ e <i>irrotazionale</i>. <b>Circuitazione.</b> Su una qualunque curva $C$ che gira una volta attorno all'origine, $\\oint_C F\\cdot dr=2\\pi\\ne 0$. <b>Il paradosso.</b> Gauss-Green darebbe $\\oint_{\\partial D}F\\cdot dr=\\iint_D 0=0$: falso. La ragione e che $F\\notin C^1$ nell'origine, che sta <i>dentro</i> $D$; l'ipotesi cade e il teorema non si applica. <b>Come si isola la singolarita.</b> Tolgo un dischetto $D_\\varepsilon$ centrato in $0$: sull'anello $D\\setminus D_\\varepsilon$ il campo e $C^1$ e $\\operatorname{rot}=0$, cosi Gauss-Green da $\\oint_{\\partial D}-\\oint_{C_\\varepsilon}=0$, cioe $$\\oint_{\\partial D}F\\cdot dr=\\oint_{C_\\varepsilon}F\\cdot dr=2\\pi\\quad\\text{per ogni }\\varepsilon.$$ Il valore non dipende da $\\varepsilon$: e il numero di avvolgimento. <b>Lettura.</b> $F$ e una forma <i>chiusa ma non esatta</i> sul piano bucato; l'ostruzione e topologica, non differenziale."},

{type:6, topic:"Esaminatore: regola della mano destra fra normale e bordo",
 q:"Spieghi la regola della mano destra che lega la normale al verso del bordo in Stokes.",
 prov:"Programma ufficiale del corso, blocco «teoremi integrali»",
 model:"<b>La regola.</b> Se le dita della mano destra si arrotolano nel verso di percorrenza di $\\partial\\Sigma$, il pollice indica la normale $n$. Equivalente cinematico: cammino lungo $\\partial\\Sigma$ con la testa nel verso di $n$; allora la superficie mi resta <b>a sinistra</b>. <b>Perche conta.</b> Stokes lega due grandezze con segno, $\\oint_{\\partial\\Sigma}F\\cdot dr$ e $\\iint_\\Sigma(\\operatorname{rot}F)\\cdot n\\,dS$; solo la coppia coerente rende vera l'uguaglianza. Rovesciando $n$ cambia segno il flusso a destra, e per compensare deve cambiare il verso del bordo a sinistra. <b>Caso piano.</b> Regione nel piano $xy$ con $n=\\hat z$ (verso l'alto): il bordo coerente e quello <i>antiorario</i>, ed e esattamente l'orientazione positiva di Gauss-Green. Con $n=-\\hat z$ il bordo diventa orario. <b>Coerenza con la parametrizzazione.</b> Se $n=(r_u\\times r_v)/|r_u\\times r_v|$, scambiare $u\\leftrightarrow v$ inverte insieme $n$ e il verso indotto sul bordo: la regola della mano destra e automatica nella scelta dell'ordine dei parametri."},

{type:6, topic:"Esaminatore: perche il flusso del rotore dipende solo dal bordo",
 q:"Perche il flusso del rotore attraverso una superficie dipende solo dal suo bordo? Che c'entra div rot = 0?",
 prov:"Programma ufficiale del corso, blocco «teoremi integrali»",
 model:"<b>Via Stokes.</b> Se $\\Sigma_1$ e $\\Sigma_2$ hanno lo <i>stesso</i> bordo $\\partial\\Sigma$ (coerentemente orientato), Stokes da per entrambe $\\iint_{\\Sigma_i}(\\operatorname{rot}F)\\cdot n\\,dS=\\oint_{\\partial\\Sigma}F\\cdot dr$: stesso valore, quindi i due flussi coincidono. <b>Via divergenza (piu profonda).</b> Incollo $\\Sigma_1$ con $\\Sigma_2$ rovesciata: $S=\\Sigma_1\\cup(-\\Sigma_2)$ e una superficie <i>chiusa</i> che racchiude un volume $V$. Per il teorema della divergenza $$\\iint_{S}(\\operatorname{rot}F)\\cdot n\\,dS=\\iiint_V\\operatorname{div}(\\operatorname{rot}F)\\,dV.$$ <b>Il fatto chiave.</b> $\\operatorname{div}\\operatorname{rot}F\\equiv 0$ identicamente: $$\\operatorname{div}\\operatorname{rot}F=\\partial_x(\\partial_yF_3-\\partial_zF_2)+\\partial_y(\\partial_zF_1-\\partial_xF_3)+\\partial_z(\\partial_xF_2-\\partial_yF_1)=0,$$ perche le derivate miste si cancellano a coppie (teorema di Schwarz, $F\\in C^2$). Dunque il flusso su $S$ e nullo, cioe $\\iint_{\\Sigma_1}=\\iint_{\\Sigma_2}$. <b>Morale.</b> Il flusso del rotore e un invariante del bordo perche $\\operatorname{rot}F$ e un campo a divergenza nulla (solenoidale); le due superfici sono deformabili l'una nell'altra senza cambiare il conto, purche non attraversino singolarita di $F$."},

{type:6, topic:"Esaminatore: area con Gauss-Green e legame coi campi conservativi",
 q:"Come si calcola un'area con Gauss-Green e perche funziona? Che legame c'e coi campi conservativi?",
 prov:"Programma ufficiale del corso, blocco «teoremi integrali»",
 model:"<b>Formula d'area.</b> Scelgo un campo con $\\partial_xF_2-\\partial_yF_1=1$: allora Gauss-Green da $\\text{Area}(D)=\\iint_D 1\\,dx\\,dy=\\oint_{\\partial D}F\\cdot dr$. Tre scelte comuni: $$\\text{Area}=\\oint_{\\partial D}x\\,dy=-\\oint_{\\partial D}y\\,dx=\\tfrac{1}{2}\\oint_{\\partial D}(x\\,dy-y\\,dx).$$ La terza (simmetrica) e la formula del geometra / shoelace. <b>Perche funziona.</b> Non e magia: il termine di Gauss-Green e stato tarato a $1$, cosi l'integrale doppio conta l'area e l'informazione si legge tutta sul bordo. <b>Legame coi conservativi.</b> Su un dominio semplicemente connesso, $F$ e conservativo ($F=\\nabla f$) se e solo se e irrotazionale, $\\partial_xF_2-\\partial_yF_1=0$; allora Gauss-Green da $\\oint_{\\partial D}F\\cdot dr=\\iint_D 0=0$, coerente con $\\oint\\nabla f\\cdot dr=0$ su ogni curva chiusa. <b>Dove si apre il divario.</b> Il vortice $\\big(\\tfrac{-y}{r^2},\\tfrac{x}{r^2}\\big)$ e irrotazionale ma <i>non</i> conservativo, perche il dominio (piano bucato) non e semplicemente connesso: forma chiusa ma non esatta, $\\oint=2\\pi$. Gauss-Green e Stokes sono il ponte quantitativo fra <i>irrotazionale</i> e <i>conservativo</i>, e la topologia del dominio misura esattamente lo scarto fra i due."}

];
