/* frags-teoria/serie.js — teoria per l'orale: successioni e serie di funzioni, serie di potenze */
LAV.serie = [

{type:6, topic:"Puntuale vs uniforme: i quantificatori",
 q:"Dia le definizioni di convergenza puntuale e uniforme di $f_n\\to f$ su $E$. Dove sta esattamente la differenza?",
 prov:"Programma ufficiale del corso, blocco «successioni e serie di funzioni»",
 model:"<b>Puntuale.</b> $f_n\\to f$ puntualmente su $E$ se per ogni $x\\in E$ e ogni $\\varepsilon>0$ esiste $N=N(\\varepsilon,x)$ tale che $n\\ge N\\Rightarrow|f_n(x)-f(x)|<\\varepsilon$. In simboli $$\\forall x\\,\\forall\\varepsilon\\,\\exists N(\\varepsilon,x)\\,\\forall n\\ge N:\\;|f_n(x)-f(x)|<\\varepsilon.$$ <b>Uniforme.</b> $f_n\\to f$ uniformemente se $$\\forall\\varepsilon\\,\\exists N(\\varepsilon)\\,\\forall x\\,\\forall n\\ge N:\\;|f_n(x)-f(x)|<\\varepsilon,$$ cioe' lo stesso $N$ funziona per tutti gli $x$ insieme. <b>Dove sta la differenza.</b> Nell'ordine dei quantificatori: nella puntuale $N$ viene DOPO $x$ e puo' dipendere da $x$; nell'uniforme $N$ viene PRIMA di $x$, e' uno solo. Geometricamente: da un certo $n$ in poi il grafo di $f_n$ sta tutto dentro il tubo $[f-\\varepsilon,f+\\varepsilon]$. <b>Da esaminatore.</b> Uniforme $\\Rightarrow$ puntuale sempre; il viceversa e' falso, ed e' proprio quando $\\sup_x N(\\varepsilon,x)=+\\infty$ che la puntuale non si solleva a uniforme."},

{type:6, topic:"Criterio del sup",
 q:"Enunci e dimostri: $f_n\\to f$ uniformemente su $E$ se e solo se $\\sup_E|f_n-f|\\to 0$. Come lo si usa?",
 prov:"Programma ufficiale del corso, blocco «successioni e serie di funzioni»",
 model:"<b>Enunciato.</b> Posto $M_n=\\sup_{x\\in E}|f_n(x)-f(x)|$, si ha $f_n\\to f$ uniformemente $\\iff M_n\\to 0$. <b>Dimostrazione.</b> ($\\Leftarrow$) Se $M_n\\to0$, dato $\\varepsilon>0$ esiste $N$ con $M_n<\\varepsilon$ per $n\\ge N$; allora per ogni $x$, $|f_n(x)-f(x)|\\le M_n<\\varepsilon$: e' la definizione di uniforme. ($\\Rightarrow$) Se la convergenza e' uniforme, dato $\\varepsilon>0$ esiste $N$ con $|f_n(x)-f(x)|<\\varepsilon/2$ per ogni $x$ e $n\\ge N$; passando al $\\sup$ su $x$, $M_n\\le\\varepsilon/2<\\varepsilon$, dunque $M_n\\to0$. $\\;\\boxed{\\text{c.v.d.}}$ <b>Come si usa in pratica.</b> Si calcola la funzione scarto $g_n(x)=|f_n(x)-f(x)|$, se ne cerca il massimo su $E$ annullando $g_n'$, e si guarda se quel massimo tende a $0$. E' l'unico metodo operativo: la definizione con i quantificatori non si maneggia, il $\\sup$ si calcola col calcolo differenziale. <b>Attenzione.</b> Il $\\sup$ va preso sull'insieme giusto: su $[0,1]$ puo' non tendere a zero, su $[0,a]$ con $a<1$ si'."},

{type:6, topic:"Dimostrazione: continuita' del limite",
 q:"Se $f_n$ sono continue e $f_n\\to f$ uniformemente, dimostri che $f$ e' continua. Dove usa l'uniformita'?",
 prov:"Programma ufficiale del corso, blocco «successioni e serie di funzioni»",
 model:"<b>Tesi.</b> $f$ continua in ogni $x_0\\in E$. <b>Argomento dei tre $\\varepsilon/3$.</b> Fisso $x_0$ e $\\varepsilon>0$. Per l'uniformita' esiste $N$ tale che $\\sup_E|f_N-f|<\\varepsilon/3$; in particolare per ogni $x$: $$|f(x)-f_N(x)|<\\tfrac{\\varepsilon}{3}.$$ Per la continuita' di $f_N$ in $x_0$ esiste $\\delta>0$ tale che $|x-x_0|<\\delta\\Rightarrow|f_N(x)-f_N(x_0)|<\\varepsilon/3$. Allora, per $|x-x_0|<\\delta$: $$|f(x)-f(x_0)|\\le|f(x)-f_N(x)|+|f_N(x)-f_N(x_0)|+|f_N(x_0)-f(x_0)|<\\tfrac{\\varepsilon}{3}+\\tfrac{\\varepsilon}{3}+\\tfrac{\\varepsilon}{3}=\\varepsilon.$$ Quindi $f$ e' continua in $x_0$. $\\;\\boxed{\\text{c.v.d.}}$ <b>Dove morde l'uniformita'.</b> Il primo e il terzo pezzo: servono lo STESSO $N$ valido in $x$ e in $x_0$ contemporaneamente. Con la sola puntuale $N$ dipenderebbe dal punto e non si potrebbe fissare un unico $f_N$ vicino a $f$ sia in $x$ che in $x_0$. <b>Da esaminatore.</b> L'ipotesi e' sufficiente, non necessaria: il limite puo' essere continuo anche senza uniformita' (Dini da' un parziale viceversa con monotonia e compattezza)."},

{type:6, topic:"Controesempio: $x^n$ su $[0,1]$",
 q:"Studi $f_n(x)=x^n$ su $[0,1]$: limite puntuale, uniformita', e cosa cambia su $[0,a]$ con $a<1$.",
 prov:"Programma ufficiale del corso, blocco «successioni e serie di funzioni»",
 model:"<b>Limite puntuale.</b> Per $0\\le x<1$, $x^n\\to0$; per $x=1$, $1^n\\to1$. Dunque $$f(x)=\\begin{cases}0 & 0\\le x<1\\\\ 1 & x=1\\end{cases},$$ discontinua in $x=1$. <b>Non uniforme su $[0,1]$.</b> Lo scarto e' $|f_n(x)-f(x)|=x^n$ su $[0,1)$, e $$\\sup_{[0,1)}x^n=1\\;\\;(\\text{limite per }x\\to1^-)\\not\\to0.$$ Il sup vale sempre $1$, non tende a zero: niente uniforme. E' coerente col teorema del blocco precedente — $f_n$ continue, limite discontinuo, quindi la convergenza NON poteva essere uniforme (contronominale). <b>Su $[0,a]$, $a<1$.</b> Qui $\\sup_{[0,a]}x^n=a^n\\to0$ perche' $a<1$: la convergenza e' uniforme e infatti il limite (la funzione nulla) e' continuo. <b>Morale.</b> L'uniformita' e' una proprieta' dell'INSIEME, non solo delle funzioni: si rompe solo avvicinandosi al punto $x=1$ dove il grafo si impenna verso $1$ senza mai stabilizzarsi."},

{type:6, topic:"Limite sotto integrale e sotto derivata",
 q:"Enunci i teoremi di passaggio al limite sotto integrale e sotto derivata. Perche' la derivata chiede di piu'?",
 prov:"Programma ufficiale del corso, blocco «successioni e serie di funzioni»",
 model:"<b>Integrale.</b> Se $f_n\\to f$ uniformemente su $[a,b]$ e ogni $f_n$ e' continua (o Riemann-integrabile), allora $$\\lim_n\\int_a^b f_n=\\int_a^b\\lim_n f_n=\\int_a^b f.$$ Perche': $\\left|\\int_a^b(f_n-f)\\right|\\le(b-a)\\sup|f_n-f|\\to0$. Basta l'uniformita' delle funzioni. <b>Derivata.</b> Se $f_n\\in C^1$, la successione delle DERIVATE $f_n'\\to g$ uniformemente, e $f_n(x_0)$ converge in ALMENO un punto $x_0$, allora $f_n\\to f$ (uniformemente sui compatti), $f\\in C^1$ e $$f'=g=\\lim_n f_n'.$$ <b>Perche' la derivata chiede di piu'.</b> L'uniformita' di $f_n$ NON controlla le pendenze: si puo' stare vicino in altezza e oscillare selvaggiamente in derivata. Il teorema si dimostra applicando il teorema dell'integrale a $f_n'$ e il fondamentale del calcolo $f_n(x)=f_n(x_0)+\\int_{x_0}^x f_n'$: e' la derivata che deve convergere bene, la funzione la si ricostruisce integrando. <b>Controesempio.</b> $f_n(x)=\\frac{\\sin(nx)}{\\sqrt n}$: $\\sup|f_n|=\\frac1{\\sqrt n}\\to0$, quindi $f_n\\to0$ uniformemente; ma $f_n'(x)=\\sqrt n\\cos(nx)$ non converge (in $x=0$ vale $\\sqrt n\\to+\\infty$). Limite delle derivate $\\ne$ derivata del limite $=0$."},

{type:6, topic:"Serie di funzioni: le quattro convergenze",
 q:"Definisca puntuale, assoluta, uniforme e totale per $\\sum f_n$. Faccia lo schema completo delle implicazioni.",
 prov:"Programma ufficiale del corso, blocco «successioni e serie di funzioni»",
 model:"Sia $s_N=\\sum_{n=1}^N f_n$ la ridotta. <b>Puntuale.</b> $\\sum f_n(x)$ converge per ogni $x\\in E$, cioe' $s_N(x)$ ha limite finito puntualmente. <b>Assoluta.</b> $\\sum|f_n(x)|$ converge per ogni $x$. <b>Uniforme.</b> $s_N\\to s$ uniformemente, cioe' $\\sup_E|s-s_N|\\to0$. <b>Totale.</b> Esiste $M_n\\ge\\sup_E|f_n|$ con $\\sum M_n<\\infty$ (esiste una maggiorante numerica sommabile). <b>Schema delle implicazioni.</b> $$\\text{totale}\\Rightarrow\\begin{cases}\\text{assoluta}\\\\ \\text{uniforme}\\end{cases}\\Rightarrow\\text{puntuale}.$$ La totale e' la piu' forte e implica sia l'assoluta (perche' $\\sum|f_n(x)|\\le\\sum M_n<\\infty$) sia l'uniforme (e' il Weierstrass). <b>Cosa NON vale.</b> Assoluta e uniforme sono INDIPENDENTI: nessuna implica l'altra. $\\sum(-1)^n/(n+x^2)$ e' uniforme ma non assoluta (ne' totale); una serie puo' essere assoluta puntualmente ma non uniforme. <b>Da esaminatore.</b> La totale e' comoda perche' e' un criterio NUMERICO (si controlla una serie di numeri $\\sum M_n$), ma proprio per questo e' troppo forte: butta via il segno, quindi manca tutte le convergenze uniformi che vivono di cancellazione (Leibniz)."},

{type:6, topic:"Dimostrazione: M-test di Weierstrass",
 q:"Enunci e dimostri il criterio di Weierstrass. Perche' da' anche la convergenza assoluta?",
 prov:"Programma ufficiale del corso, blocco «successioni e serie di funzioni»",
 model:"<b>Enunciato.</b> Se $|f_n(x)|\\le M_n$ per ogni $x\\in E$ e $\\sum M_n<\\infty$, allora $\\sum f_n$ converge totalmente, quindi uniformemente e assolutamente su $E$. <b>Dimostrazione via Cauchy uniforme.</b> La serie numerica $\\sum M_n$ converge, dunque soddisfa Cauchy: $\\forall\\varepsilon\\,\\exists N\\,\\forall q>p\\ge N:\\;\\sum_{n=p+1}^{q}M_n<\\varepsilon$. Allora per ogni $x\\in E$ e ogni $q>p\\ge N$: $$|s_q(x)-s_p(x)|=\\Big|\\sum_{n=p+1}^{q}f_n(x)\\Big|\\le\\sum_{n=p+1}^{q}|f_n(x)|\\le\\sum_{n=p+1}^{q}M_n<\\varepsilon.$$ La stima e' UNIFORME in $x$ (l'$N$ non dipende da $x$). Quindi $(s_N)$ e' di Cauchy uniforme; nello spazio completo delle funzioni limitate con la norma del sup converge uniformemente. $\\;\\boxed{\\text{c.v.d.}}$ <b>Perche' anche assoluta.</b> La stessa catena $\\sum_{p+1}^{q}|f_n(x)|\\le\\sum_{p+1}^{q}M_n$ dice che $\\sum|f_n(x)|$ e' di Cauchy per ogni $x$: converge, cioe' assoluta. <b>Dove si spende l'ipotesi.</b> Tutto poggia sul maggiorare $|f_n(x)|$ con un $M_n$ INDIPENDENTE da $x$: e' quello che rende l'$N$ uniforme."},

{type:6, topic:"Controesempio: uniforme non totale",
 q:"Mostri una serie uniformemente ma non totalmente convergente. Faccia i conti della coda e degli estremi superiori.",
 prov:"Programma ufficiale del corso, blocco «successioni e serie di funzioni»",
 model:"<b>La serie.</b> $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{(-1)^n}{n+x^2}$ su $\\mathbb{R}$. <b>Uniforme (Leibniz + stima della coda).</b> A $x$ fissato i termini $a_n(x)=\\frac1{n+x^2}$ sono positivi, decrescenti in $n$ e $\\to0$: la serie converge per Leibniz. La stima del resto di Leibniz e' che la coda e' maggiorata dal primo termine trascurato: $$\\Big|\\sum_{n=N+1}^{\\infty}\\frac{(-1)^n}{n+x^2}\\Big|\\le\\frac{1}{(N+1)+x^2}\\le\\frac{1}{N+1}.$$ L'ultima maggiorazione e' INDIPENDENTE da $x$ e tende a $0$: quindi $\\sup_x|\\text{resto}_N|\\le\\frac1{N+1}\\to0$, la convergenza e' uniforme. <b>Non totale (estremi superiori).</b> $$M_n=\\sup_{x\\in\\mathbb{R}}\\Big|\\frac{(-1)^n}{n+x^2}\\Big|=\\sup_x\\frac{1}{n+x^2}=\\frac1n\\quad(\\text{massimo in }x=0).$$ Ma $\\sum M_n=\\sum\\frac1n=+\\infty$: la serie NON e' totale. <b>Perche' non contraddice nulla.</b> La totale implica l'uniforme, non il viceversa: l'uniformita' qui nasce dalla cancellazione dei segni $(-1)^n$ (Leibniz), che il criterio totale ignora prendendo i moduli. E' l'esempio-tipo che separa uniforme e totale."},

{type:6, topic:"Cauchy-Hadamard: raggio di convergenza",
 q:"Enunci Cauchy-Hadamard per $\\sum a_n(x-x_0)^n$ e dimostri i due casi $|x-x_0|<R$ e $|x-x_0|>R$.",
 prov:"Programma ufficiale del corso, blocco «successioni e serie di funzioni»",
 model:"<b>Enunciato.</b> Per la serie di potenze $\\sum a_n(x-x_0)^n$ poniamo $$\\frac1R=\\limsup_{n\\to\\infty}\\sqrt[n]{|a_n|}\\quad(R\\in[0,+\\infty]).$$ Allora la serie converge assolutamente per $|x-x_0|<R$ e diverge per $|x-x_0|>R$. <b>Caso $|x-x_0|<R$ (converge).</b> Sia $r=|x-x_0|<R$, cioe' $\\frac{r}{R}<1$. Scelto $\\rho$ con $r<\\rho<R$ si ha $\\frac1\\rho>\\frac1R=\\limsup\\sqrt[n]{|a_n|}$, quindi definitivamente $\\sqrt[n]{|a_n|}<\\frac1\\rho$, ossia $|a_n|<\\rho^{-n}$. Allora $$|a_n(x-x_0)^n|=|a_n|r^n<\\Big(\\frac{r}{\\rho}\\Big)^n$$ con $\\frac r\\rho<1$: e' maggiorata da una geometrica convergente, quindi per confronto la serie converge assolutamente. <b>Caso $|x-x_0|>R$ (diverge).</b> Sia $r=|x-x_0|>R$, cioe' $\\frac1r<\\frac1R=\\limsup\\sqrt[n]{|a_n|}$. Per definizione di limsup, $\\sqrt[n]{|a_n|}>\\frac1r$ per infiniti $n$, cioe' $|a_n|r^n>1$ infinite volte: il termine generale non tende a $0$, quindi la serie diverge (condizione necessaria violata). $\\;\\boxed{\\text{c.v.d.}}$ <b>Da esaminatore.</b> Il limsup, non il lim, perche' esiste sempre e cattura il comportamento peggiore dei coefficienti; sul bordo $|x-x_0|=R$ il criterio TACE."},

{type:6, topic:"Abel, compatti e il bordo",
 q:"Enunci il lemma di Abel e la convergenza totale sui compatti nel disco. Cosa non si puo' dire agli estremi?",
 prov:"Programma ufficiale del corso, blocco «successioni e serie di funzioni»",
 model:"<b>Lemma di Abel.</b> Se $\\sum a_n(x-x_0)^n$ converge in un punto $x_1$, allora converge assolutamente in ogni $x$ con $|x-x_0|<|x_1-x_0|$. Perche': se converge in $x_1$ il termine generale e' limitato, $|a_n(x_1-x_0)^n|\\le C$, da cui $|a_n(x-x_0)^n|\\le C\\,q^n$ con $q=\\frac{|x-x_0|}{|x_1-x_0|}<1$: geometrica. <b>Totale sui compatti.</b> Su ogni $\\overline{B}(x_0,r)$ con $r<R$ vale $|a_n(x-x_0)^n|\\le|a_n|r^n=M_n$ e $\\sum M_n<\\infty$ (per Cauchy-Hadamard, $r<R$): Weierstrass da' la convergenza totale, quindi uniforme, su ogni compatto interno al disco. <b>Cosa NON si dice sul bordo.</b> Al bordo $|x-x_0|=R$ il criterio non decide, e i tre esempi con $R=1$, $x_0=0$ lo mostrano: $$\\sum x^n:\\;\\text{diverge in }x=\\pm1;\\qquad \\sum\\frac{x^n}{n}:\\;\\text{converge in }x=-1\\ (\\text{Leibniz}),\\ \\text{diverge in }x=1\\ (\\text{armonica});$$ $$\\sum\\frac{x^n}{n^2}:\\;\\text{converge in }x=\\pm1\\ (\\text{p-serie},\\ p=2).$$ Stesso raggio, tre comportamenti al bordo. <b>Morale.</b> Il raggio governa l'interno; il bordo e' terra di nessuno, va studiato punto per punto con i criteri per serie numeriche."},

{type:6, topic:"Derivazione e integrazione termine a termine",
 q:"Perche' la serie derivata ha lo stesso raggio? Deduca che la somma e' $C^\\infty$ e la relazione con Taylor.",
 prov:"Programma ufficiale del corso, blocco «successioni e serie di funzioni»",
 model:"<b>Stesso raggio.</b> La serie derivata formale e' $\\sum n\\,a_n(x-x_0)^{n-1}$. Il suo raggio si legge da $\\limsup\\sqrt[n]{n|a_n|}=\\limsup\\big(\\sqrt[n]{n}\\cdot\\sqrt[n]{|a_n|}\\big)$; poiche' $\\sqrt[n]{n}\\to1$, il limsup non cambia: $$\\frac{1}{R'}=\\limsup\\sqrt[n]{n|a_n|}=\\limsup\\sqrt[n]{|a_n|}=\\frac1R.$$ Stesso $R$. <b>Derivazione lecita.</b> Su ogni compatto interno la serie derivata converge uniformemente (punto precedente), e la serie converge in almeno un punto: sono le ipotesi del teorema di derivazione termine a termine. Quindi $f(x)=\\sum a_n(x-x_0)^n$ e' derivabile nell'aperto $|x-x_0|<R$ con $f'(x)=\\sum n a_n(x-x_0)^{n-1}$. <b>$C^\\infty$.</b> Il passo si itera: $f'$ e' di nuovo una serie di potenze con lo stesso raggio, derivabile, e cosi' via. Dunque $f\\in C^\\infty$ nell'intervallo aperto di convergenza. <b>Relazione con Taylor.</b> Derivando $k$ volte e valutando in $x_0$ sopravvive solo il termine $n=k$: $$f^{(k)}(x_0)=k!\\,a_k\\;\\Rightarrow\\;a_k=\\frac{f^{(k)}(x_0)}{k!}.$$ Cioe' una serie di potenze coincide con la propria serie di Taylor: i coefficienti sono UNIVOCAMENTE determinati dalla somma (principio di identita' delle serie di potenze). <b>Nota.</b> L'integrazione termine a termine e' l'analoga: stesso raggio, si integra dentro la serie."},

{type:6, topic:"Da esaminatore: perche' la puntuale non basta mai",
 q:"Perche' la convergenza puntuale «non basta mai»? Dove si rompono continuita', integrale, derivata, e qual e' la ragione strutturale?",
 prov:"Programma ufficiale del corso, blocco «successioni e serie di funzioni»",
 model:"<b>La tesi.</b> La puntuale conserva l'esistenza del limite punto per punto ma NON commuta con le operazioni analitiche (limite, integrale, derivata). L'uniforme si', ed e' per questo che e' lei la nozione buona. <b>Continuita'.</b> Si rompe: $x^n\\to$ funzione con salto in $1$. La continuita' e' $\\lim_{x\\to x_0}\\lim_n=\\lim_n\\lim_{x\\to x_0}$, uno scambio di limiti; la puntuale non autorizza lo scambio. <b>Integrale.</b> Si rompe: esistono $f_n\\to0$ puntualmente con $\\int f_n\\not\\to0$ (una gobba di area fissa che scivola e si assottiglia). Manca il controllo uniforme dell'altezza. <b>Derivata.</b> Si rompe due volte: $\\frac{\\sin(nx)}{\\sqrt n}\\to0$ ma le derivate esplodono; le pendenze non sono controllate dalla vicinanza in altezza. <b>Ragione strutturale.</b> La convergenza uniforme E' la convergenza nella norma del sup $\\|g\\|_\\infty=\\sup_E|g|$: $f_n\\to f$ uniformemente $\\iff\\|f_n-f\\|_\\infty\\to0$. Lo spazio $\\big(C(E),\\|\\cdot\\|_\\infty\\big)$ e' COMPLETO (Banach), e continuita' e integrale sono operatori CONTINUI per questa norma — perche' controllano $\\sup$ e area con $\\sup$. La puntuale invece e' convergenza in uno spazio senza una norma che renda continue quelle operazioni: nessuna metrica la governa uniformemente, quindi nessuna garanzia di scambio. <b>Aggancio fisico.</b> E' questa la ragione, taciuta, per cui in teoria dei campi si scambiano tranquillamente $\\int$ e $\\lim$ (o $\\sum$): dietro c'e' sempre un'ipotesi di convergenza uniforme/totale che rende gli scambi leciti."}

];
