// Lavagne di teoria per l'orale di Analisi Vettoriale — blocco «superfici, area, flusso»
LAV.superfici = [

{type:6, topic:"Enunciato: superficie regolare in forma parametrica",
 q:"Enunci la definizione di superficie regolare in forma parametrica. A cosa serve ciascuna ipotesi, e quali casi ricadono nella definizione?",
 prov:"Programma ufficiale del corso, blocco «superfici, area, flusso»",
 model:"<b>Definizione.</b> Una superficie regolare e' un'applicazione $\\sigma:A\\subset\\mathbb{R}^2\\to\\mathbb{R}^3$, $A$ aperto connesso, con $\\sigma\\in C^1(A)$, iniettiva su $A$, tale che in ogni punto $$\\sigma_u\\times\\sigma_v\\neq 0.$$ Il <b>sostegno</b> e' l'immagine $\\sigma(A)$: l'oggetto geometrico, distinto dalla mappa che lo descrive. <b>Dove morde ciascuna ipotesi.</b> $C^1$ esclude spigoli e permette di derivare per costruire il tangente. L'<b>iniettivita'</b> esclude autointersezioni: senza di essa il sostegno si sovrappone e area e flusso vengono contati due volte. La condizione $\\sigma_u\\times\\sigma_v\\neq0$ e' la <b>regolarita'</b> vera e propria: garantisce che i due vettori tangenti siano indipendenti, cioe' che esista un piano tangente e non un punto di collasso. <b>Casi particolari.</b> La superficie <b>cartesiana</b> $z=f(x,y)$ e' il caso $\\sigma(x,y)=(x,y,f(x,y))$: automaticamente iniettiva e con $\\sigma_x\\times\\sigma_y=(-f_x,-f_y,1)\\neq0$ sempre. La <b>superficie di livello</b> $\\{F=0\\}$ e' regolare dove $\\nabla F\\neq0$, per il teorema di Dini che la rende localmente un grafico. <b>Sottolineatura d'orale.</b> Iniettivita' e non annullamento del prodotto vettore sono ipotesi indipendenti: il nastro di Moebius viola la prima come oggetto globale, il vertice del cono la seconda in un punto."},

{type:6, topic:"Dimostrazione: piano tangente e versore normale",
 q:"Costruisca il piano tangente a una superficie regolare e ne ricavi il versore normale. Perche' la condizione $\\sigma_u\\times\\sigma_v\\neq0$ e' esattamente cio' che garantisce l'esistenza del piano?",
 prov:"Programma ufficiale del corso, blocco «superfici, area, flusso»",
 model:"<b>Passo 1: le curve coordinate.</b> Fissato $(u_0,v_0)$, le mappe $u\\mapsto\\sigma(u,v_0)$ e $v\\mapsto\\sigma(u_0,v)$ sono due curve sul sostegno che si incrociano nel punto. I loro vettori velocita' sono $\\sigma_u$ e $\\sigma_v$, tangenti alla superficie. <b>Passo 2: lo spazio tangente.</b> Ogni curva $t\\mapsto\\sigma(u(t),v(t))$ ha velocita' $\\sigma_u\\,u'+\\sigma_v\\,v'$ per la regola della catena: ogni vettore tangente e' combinazione lineare di $\\sigma_u,\\sigma_v$. Se questi sono indipendenti generano un piano, il <b>piano tangente</b>. <b>Passo 3: dove morde l'ipotesi.</b> Due vettori di $\\mathbb{R}^3$ sono linearmente indipendenti se e solo se il loro prodotto vettore e' non nullo: $$\\sigma_u\\times\\sigma_v\\neq0 \\iff \\{\\sigma_u,\\sigma_v\\}\\ \\text{indipendenti}.$$ Dunque la condizione di regolarita' e' precisamente l'esistenza del piano tangente. <b>Passo 4: la normale.</b> Il prodotto vettore e' ortogonale a entrambi i generatori, quindi al piano; normalizzando, $$\\mathbf{n}=\\frac{\\sigma_u\\times\\sigma_v}{|\\sigma_u\\times\\sigma_v|}.$$ <b>Caso cartesiano.</b> Con $\\sigma=(x,y,f)$ si ha $\\sigma_x=(1,0,f_x)$, $\\sigma_y=(0,1,f_y)$ e $$\\sigma_x\\times\\sigma_y=(-f_x,-f_y,1),$$ mai nullo: la terza componente vale $1$. La normale punta verso l'alto, coerente con l'intuizione del grafico. $\\boxed{\\text{c.v.d.}}$"},

{type:6, topic:"Controesempio: vertice del cono e poli della sfera",
 q:"Esibisca un punto in cui manca il piano tangente e distingua la singolarita' del sostegno dalla degenerazione della sola parametrizzazione. Che differenza c'e' fra il vertice del cono e i poli della sfera?",
 prov:"Programma ufficiale del corso, blocco «superfici, area, flusso»",
 model:"<b>Il cono.</b> $\\sigma(u,v)=(u\\cos v,u\\sin v,u)$, $u\\geq0$. Calcolo: $\\sigma_u=(\\cos v,\\sin v,1)$, $\\sigma_v=(-u\\sin v,u\\cos v,0)$. Il prodotto vettore e' $$\\sigma_u\\times\\sigma_v=(-u\\cos v,-u\\sin v,u),\\qquad |\\sigma_u\\times\\sigma_v|=u\\sqrt2.$$ In $u=0$ si annulla: niente piano tangente. E qui la singolarita' e' <b>vera</b>, del sostegno: il vertice e' uno spigolo geometrico, nessuna riparametrizzazione lo rende liscio (le rette del cono vi arrivano con direzioni diverse). <b>La sfera.</b> $\\sigma(\\theta,\\varphi)=R(\\sin\\theta\\cos\\varphi,\\sin\\theta\\sin\\varphi,\\cos\\theta)$. Si ottiene $|\\sigma_\\theta\\times\\sigma_\\varphi|=R^2\\sin\\theta$, che si annulla ai poli $\\theta=0,\\pi$. Ma il sostegno ai poli e' perfettamente liscio: e' la <b>parametrizzazione</b> a collassare, perche' tutto il meridiano $\\theta=0$ finisce in un solo punto e $\\varphi$ diventa una coordinata inutile. Con carte diverse (proiezione stereografica) i poli sono regolari. <b>La distinzione d'orale.</b> $\\sigma_u\\times\\sigma_v=0$ in un punto NON basta a concludere che la superficie e' singolare: e' condizione sulla mappa, non sull'oggetto. Si guarda se un'altra carta liscia il punto (sfera: si') oppure no (cono: no)."},

{type:6, topic:"Enunciato: area di una superficie ed elemento $dS$",
 q:"Enunci la formula per l'area di una superficie regolare e giustifichi geometricamente l'elemento d'area. Quali sono i casi notevoli?",
 prov:"Programma ufficiale del corso, blocco «superfici, area, flusso»",
 model:"<b>Formula.</b> Per $\\sigma:A\\to\\mathbb{R}^3$ regolare, $$\\text{Area}(\\Sigma)=\\iint_A|\\sigma_u\\times\\sigma_v|\\,du\\,dv,\\qquad dS=|\\sigma_u\\times\\sigma_v|\\,du\\,dv.$$ <b>Giustificazione.</b> Un rettangolino di lati $du,dv$ nel dominio dei parametri viene mandato da $\\sigma$, al primo ordine, nel parallelogramma di lati $\\sigma_u\\,du$ e $\\sigma_v\\,dv$ appoggiato al piano tangente. L'area di un parallelogramma generato da due vettori e' il modulo del loro prodotto vettore: $$|\\sigma_u\\,du\\times\\sigma_v\\,dv|=|\\sigma_u\\times\\sigma_v|\\,du\\,dv.$$ Sommando (integrando) questi elementi si ottiene l'area totale. Il fattore $|\\sigma_u\\times\\sigma_v|$ e' lo iacobiano di superficie: misura quanto la mappa dilata l'area passando dai parametri al sostegno. <b>Caso cartesiano.</b> Con $\\sigma_x\\times\\sigma_y=(-f_x,-f_y,1)$ si ha $$dS=\\sqrt{1+|\\nabla f|^2}\\,dx\\,dy,$$ e il termine $\\sqrt{1+|\\nabla f|^2}\\geq1$ dice che una superficie inclinata copre piu' area della sua ombra. <b>Superficie di rotazione.</b> Ruotando $(r(t),z(t))$ attorno all'asse $z$ si trova $dS=r(t)\\sqrt{r'^2+z'^2}\\,dt\\,d\\varphi$: il $2\\pi r$ del cerchio per l'elemento di lunghezza della curva."},

{type:6, topic:"Dimostrazione: invarianza dell'area per riparametrizzazione",
 q:"Dimostri che l'area non dipende dalla parametrizzazione scelta. In quale passaggio interviene il cambio di variabili, e cosa distingue l'area dall'orientazione?",
 prov:"Programma ufficiale del corso, blocco «superfici, area, flusso»",
 model:"<b>Ipotesi.</b> $\\Phi:B\\to A$ diffeomorfismo $C^1$ fra aperti, $(s,t)\\mapsto(u,v)$, e $\\tilde\\sigma=\\sigma\\circ\\Phi$ e' una seconda parametrizzazione dello stesso sostegno. <b>Passo 1: come si trasforma il prodotto vettore.</b> Per la regola della catena $\\tilde\\sigma_s=\\sigma_u u_s+\\sigma_v v_s$ e $\\tilde\\sigma_t=\\sigma_u u_t+\\sigma_v v_t$. Nel prodotto vettore i termini $\\sigma_u\\times\\sigma_u$ e $\\sigma_v\\times\\sigma_v$ si annullano e restano i misti: $$\\tilde\\sigma_s\\times\\tilde\\sigma_t=(u_s v_t-u_t v_s)\\,\\sigma_u\\times\\sigma_v=(\\det J_\\Phi)\\,\\sigma_u\\times\\sigma_v.$$ <b>Passo 2: prendo il modulo.</b> $|\\tilde\\sigma_s\\times\\tilde\\sigma_t|=|\\det J_\\Phi|\\,|\\sigma_u\\times\\sigma_v|$. <b>Passo 3: il cambio di variabili.</b> $$\\iint_B|\\tilde\\sigma_s\\times\\tilde\\sigma_t|\\,ds\\,dt=\\iint_B|\\sigma_u\\times\\sigma_v|\\big(\\Phi\\big)\\,|\\det J_\\Phi|\\,ds\\,dt=\\iint_A|\\sigma_u\\times\\sigma_v|\\,du\\,dv,$$ per la formula di cambio di variabili nell'integrale doppio, dove $|\\det J_\\Phi|$ e' esattamente il fattore che compare. Stesso numero: l'area e' invariante. <b>Passo 4: l'osservazione fine.</b> Il modulo cancella il segno di $\\det J_\\Phi$. Ma quel segno c'e': se $\\det J_\\Phi>0$ la normale $\\sigma_u\\times\\sigma_v$ conserva il verso, se $<0$ lo inverte. E' il segno, non il modulo, a portare l'<b>orientazione</b>. $\\boxed{\\text{c.v.d.}}$"},

{type:6, topic:"Enunciato: orientabilita' e orientazione del bordo",
 q:"Definisca la superficie orientabile e l'orientazione indotta sul bordo. Perche' l'orientazione e' il prezzo d'ingresso per Stokes e per la divergenza?",
 prov:"Programma ufficiale del corso, blocco «superfici, area, flusso»",
 model:"<b>Definizione.</b> Una superficie $\\Sigma$ e' <b>orientabile</b> se esiste un campo di versori normali $\\mathbf{n}:\\Sigma\\to\\mathbb{R}^3$ <b>continuo</b> su tutta $\\Sigma$. La scelta di uno dei due tali campi (l'altro e' $-\\mathbf{n}$) e' un'<b>orientazione</b>. La regolarita' garantisce che localmente $\\mathbf{n}$ esista sempre; l'orientabilita' e' la questione GLOBALE se le scelte locali si incollino con continuita'. <b>Bordo e regola della mano destra.</b> Per una superficie con bordo $\\partial\\Sigma$, fissata $\\mathbf{n}$, si orienta $\\partial\\Sigma$ col verso per cui, camminando lungo il bordo con la testa verso $\\mathbf{n}$, la superficie resta a sinistra: equivalentemente $\\mathbf{n}\\times(\\text{normale uscente nel piano tangente})$ da' il verso di percorrenza. <b>Superficie chiusa.</b> Se $\\Sigma$ borda un solido si sceglie convenzionalmente la <b>normale uscente</b>. <b>Perche' e' il prezzo d'ingresso.</b> Il teorema di Stokes $\\iint_\\Sigma(\\nabla\\times F)\\cdot\\mathbf{n}\\,dS=\\oint_{\\partial\\Sigma}F\\cdot d\\mathbf{r}$ lega due segni: quello di $\\mathbf{n}$ e quello del verso sul bordo. Se non esiste un $\\mathbf{n}$ continuo, il membro sinistro non e' nemmeno definito. Idem per la divergenza, che chiede la normale uscente coerente su tutta la frontiera chiusa. Senza orientazione i due grandi teoremi non hanno enunciato."},

{type:6, topic:"Controesempio: il nastro di Moebius",
 q:"Esibisca una superficie non orientabile e dimostri che non lo e' trasportando la normale. Quali conseguenze operative ha la non orientabilita'?",
 prov:"Programma ufficiale del corso, blocco «superfici, area, flusso»",
 model:"<b>L'oggetto.</b> Il nastro di Moebius $$\\sigma(u,v)=\\big((2+v\\cos\\tfrac{u}{2})\\cos u,\\;(2+v\\cos\\tfrac{u}{2})\\sin u,\\;v\\sin\\tfrac{u}{2}\\big),$$ $u\\in[0,2\\pi]$, $v\\in(-\\tfrac12,\\tfrac12)$. E' la striscia con una mezza torsione: la sezione $v$ ruota di $\\pi$ (mezzo giro, per via di $u/2$) mentre il centro gira di $2\\pi$. <b>Il trasporto della normale.</b> Sulla circonferenza mediana $v=0$ si ha $\\sigma(u,0)=(2\\cos u,2\\sin u,0)$. Calcolando $\\mathbf{n}(u)=\\sigma_u\\times\\sigma_v/|\\cdots|$ lungo $v=0$ e seguendola con continuita' da $u=0$ a $u=2\\pi$ si torna nello stesso punto geometrico ($\\sigma(0,0)=\\sigma(2\\pi,0)$) ma con $$\\mathbf{n}(2\\pi)=-\\mathbf{n}(0).$$ La mezza torsione ha ribaltato il verso. <b>La conclusione.</b> Nessun campo di normali continuo puo' esistere: un giro chiuso lo costringe a cambiare segno, contraddizione con la continuita'. Il nastro NON e' orientabile. <b>Conseguenze operative.</b> Il flusso $\\iint_\\Sigma F\\cdot\\mathbf{n}\\,dS$ non e' definito (nessun $\\mathbf{n}$ globale da mettere nell'integrale) e il teorema di Stokes non si applica: la superficie ha un solo «lato» e il suo bordo e' una singola circonferenza percorsa due volte, non due bordi. E' l'esempio canonico che l'orientabilita' e' proprieta' globale, non locale."},

{type:6, topic:"Enunciato: integrale di superficie scalare e flusso",
 q:"Enunci l'integrale di superficie di una funzione scalare e il flusso di un campo. Perche' il primo non dipende dall'orientazione e il secondo cambia segno?",
 prov:"Programma ufficiale del corso, blocco «superfici, area, flusso»",
 model:"<b>Integrale scalare.</b> Per $f$ continua sul sostegno, $$\\iint_\\Sigma f\\,dS=\\iint_A f(\\sigma(u,v))\\,|\\sigma_u\\times\\sigma_v|\\,du\\,dv.$$ Somma pesata dei valori di $f$ per l'elemento d'area; se $f\\equiv1$ restituisce l'area. <b>Flusso.</b> Per un campo $F$ e $\\Sigma$ orientata da $\\mathbf{n}$, $$\\iint_\\Sigma F\\cdot\\mathbf{n}\\,dS=\\iint_A F(\\sigma)\\cdot\\frac{\\sigma_u\\times\\sigma_v}{|\\sigma_u\\times\\sigma_v|}\\,|\\sigma_u\\times\\sigma_v|\\,du\\,dv=\\iint_A F(\\sigma)\\cdot(\\sigma_u\\times\\sigma_v)\\,du\\,dv.$$ Il modulo si semplifica: nella formula pratica compare direttamente il vettore $\\sigma_u\\times\\sigma_v$, non normalizzato. <b>Perche' l'uno e' invariante e l'altro no.</b> Nell'integrale scalare entra $|\\sigma_u\\times\\sigma_v|$: un modulo, sempre positivo, insensibile al verso. Nel flusso entra $\\sigma_u\\times\\sigma_v$ col suo verso: scambiare l'orientazione ($\\mathbf{n}\\to-\\mathbf{n}$, ottenuta scambiando i due parametri, $\\det J<0$) manda il flusso in $-$se stesso. <b>Significato fisico.</b> Il flusso misura quanto campo attraversa $\\Sigma$ nel verso di $\\mathbf{n}$: per un fluido, il volume netto per unita' di tempo che passa dal lato $-\\mathbf{n}$ al lato $+\\mathbf{n}$. Il segno e' la direzione dell'attraversamento, per questo l'orientazione e' essenziale."},

{type:6, topic:"Dimostrazione: flusso del campo radiale e divergenza nulla",
 q:"Calcoli il flusso di $F=\\mathbf{r}/|\\mathbf{r}|^3$ attraverso la sfera di raggio $R$ e spieghi perche' vale $4\\pi$ pur essendo $\\operatorname{div}F=0$. Che parallelo c'e' col campo angolare?",
 prov:"Programma ufficiale del corso, blocco «superfici, area, flusso»",
 model:"<b>Il conto.</b> Sulla sfera $\\Sigma_R$ di raggio $R$ la normale uscente e' $\\mathbf{n}=\\mathbf{r}/|\\mathbf{r}|$, e $|\\mathbf{r}|=R$. Dunque $$F\\cdot\\mathbf{n}=\\frac{\\mathbf{r}}{R^3}\\cdot\\frac{\\mathbf{r}}{R}=\\frac{|\\mathbf{r}|^2}{R^4}=\\frac{R^2}{R^4}=\\frac{1}{R^2},$$ costante sulla sfera. Quindi $$\\iint_{\\Sigma_R}F\\cdot\\mathbf{n}\\,dS=\\frac{1}{R^2}\\cdot\\text{Area}(\\Sigma_R)=\\frac{1}{R^2}\\cdot4\\pi R^2=4\\pi,$$ indipendente da $R$. <b>La divergenza.</b> Un conto diretto da' $\\operatorname{div}F=0$ ovunque tranne l'origine, dove $F$ non e' definito: $\\mathbb{R}^3\\setminus\\{0\\}$. <b>Perche' non e' una contraddizione.</b> Il teorema della divergenza chiede $F$ regolare su TUTTO il solido racchiuso. La palla contiene l'origine, dove $F$ esplode: il teorema non e' applicabile e non c'e' nulla da spiegare. Se invece prendo il guscio fra due sfere $R_1<R_2$, li' $F$ e' liscio, $\\operatorname{div}F=0$, e infatti il flusso entrante da una sfera esce dall'altra: $4\\pi-4\\pi=0$, coerente. <b>Il parallelo.</b> E' l'analogo tridimensionale del campo angolare $\\big(\\tfrac{-y}{x^2+y^2},\\tfrac{x}{x^2+y^2}\\big)$: irrotazionale ma con circuitazione $2\\pi$ attorno all'origine. Li' un buco di <b>codimensione 2</b> (un punto in $\\mathbb{R}^2$, una retta in $\\mathbb{R}^3$) ostruisce i cappi; qui un buco di <b>codimensione 3</b> (un punto in $\\mathbb{R}^3$) ostruisce le sfere. La topologia del dominio, non la formula locale, decide. $\\boxed{\\text{c.v.d.}}$"},

{type:6, topic:"Enunciato e dimostrazione: teorema di Guldino per l'area",
 q:"Enunci e dimostri il teorema di Guldino per l'area di una superficie di rotazione. Lo applichi al toro.",
 prov:"Programma ufficiale del corso, blocco «superfici, area, flusso»",
 model:"<b>Enunciato.</b> Sia $\\gamma$ una curva regolare nel semipiano $x\\geq0$ del piano $xz$, di lunghezza $L$, che non attraversa l'asse $z$; ruotandola attorno all'asse $z$ si genera una superficie di area $$A=2\\pi\\,d\\,L,$$ dove $d$ e' la distanza del baricentro di $\\gamma$ dall'asse. <b>Dimostrazione.</b> Parametrizzo $\\gamma$ come $(r(t),z(t))$, $t\\in[a,b]$, con $r>0$; la superficie di rotazione e' $$\\sigma(t,\\varphi)=(r(t)\\cos\\varphi,\\,r(t)\\sin\\varphi,\\,z(t)),\\quad\\varphi\\in[0,2\\pi].$$ Calcolo l'elemento d'area: $\\sigma_t=(r'\\cos\\varphi,r'\\sin\\varphi,z')$, $\\sigma_\\varphi=(-r\\sin\\varphi,r\\cos\\varphi,0)$, e $$|\\sigma_t\\times\\sigma_\\varphi|=r(t)\\sqrt{r'^2+z'^2}=r(t)\\,\\|\\gamma'(t)\\|.$$ Dunque $$A=\\int_0^{2\\pi}\\!\\!\\int_a^b r(t)\\|\\gamma'\\|\\,dt\\,d\\varphi=2\\pi\\int_a^b r(t)\\,\\|\\gamma'(t)\\|\\,dt.$$ Ora riconosco il baricentro: la coordinata $x$ del baricentro di $\\gamma$ (rispetto alla lunghezza d'arco) e' $$d=\\bar{x}=\\frac{1}{L}\\int_a^b r(t)\\|\\gamma'\\|\\,dt \\;\\Rightarrow\\; \\int_a^b r\\|\\gamma'\\|\\,dt=dL.$$ Sostituendo, $A=2\\pi\\,dL$. $\\boxed{\\text{c.v.d.}}$ <b>Il toro.</b> Cerchio generatore di raggio $r$ col centro a distanza $R>r$ dall'asse: $L=2\\pi r$ e $d=R$ (baricentro nel centro del cerchio). Quindi $A=2\\pi\\cdot R\\cdot2\\pi r=4\\pi^2 Rr$."},

{type:6, topic:"Da esaminatore: tre modi di dare una superficie",
 q:"Che differenza c'e' fra dare una superficie in forma cartesiana, parametrica e di livello, e come si passa dall'una all'altra? Qual e' la normale in ciascun caso e perche' per la superficie di livello e' $\\nabla F$?",
 prov:"Programma ufficiale del corso, blocco «superfici, area, flusso»",
 model:"<b>Le tre forme.</b> (1) <b>Cartesiana</b> $z=f(x,y)$: esplicita una coordinata in funzione delle altre. (2) <b>Parametrica</b> $\\sigma(u,v)$: mappa un dominio piano nello spazio. (3) <b>Di livello</b> $F(x,y,z)=0$: implicita, il luogo degli zeri. <b>Passaggi.</b> Cartesiana $\\to$ parametrica: $\\sigma(x,y)=(x,y,f(x,y))$. Cartesiana $\\to$ livello: $F=z-f(x,y)$. Le prime due sono sempre percorribili; livello $\\to$ cartesiana e' locale e non gratuito. <b>La normale in ciascun caso.</b> Cartesiana: $\\mathbf{n}\\propto(-f_x,-f_y,1)$. Parametrica: $\\mathbf{n}\\propto\\sigma_u\\times\\sigma_v$. Livello: $$\\mathbf{n}\\propto\\nabla F.$$ <b>Perche' e' $\\nabla F$.</b> Su $\\{F=0\\}$ prendo una qualsiasi curva $t\\mapsto\\mathbf{r}(t)$ che vi giace: $F(\\mathbf{r}(t))\\equiv0$. Derivo con la catena: $\\nabla F\\cdot\\mathbf{r}'=0$. Poiche' $\\mathbf{r}'$ e' un generico vettore tangente, $\\nabla F$ e' ortogonale a TUTTO il piano tangente: e' la normale. <b>Il legame con Dini.</b> Il teorema di Dini (funzione implicita in tre variabili) dice che se $F\\in C^1$ e $\\nabla F\\neq0$ in un punto — diciamo $F_z\\neq0$ — allora localmente $\\{F=0\\}$ si scrive come grafico $z=f(x,y)$. E' proprio $\\nabla F\\neq0$ a garantire che la superficie di livello sia regolare e riducibile alla forma cartesiana: la stessa ipotesi che rende $\\nabla F$ una normale non nulla."},

{type:6, topic:"Da esaminatore: l'area del toro nel dettaglio",
 q:"Calcoli l'area del toro dalla parametrizzazione, controlli con Guldino, e mi dica dove cade l'iniettivita' e perche' non compromette il risultato.",
 prov:"Programma ufficiale del corso, blocco «superfici, area, flusso»",
 model:"<b>Parametrizzazione.</b> Toro di raggi $R>r$: $$\\sigma(u,v)=\\big((R+r\\cos v)\\cos u,\\,(R+r\\cos v)\\sin u,\\,r\\sin v\\big),\\quad u,v\\in[0,2\\pi].$$ <b>Elemento d'area.</b> $\\sigma_u=(-(R+r\\cos v)\\sin u,(R+r\\cos v)\\cos u,0)$, $\\sigma_v=(-r\\sin v\\cos u,-r\\sin v\\sin u,r\\cos v)$. Il modulo del prodotto vettore vale $$|\\sigma_u\\times\\sigma_v|=r\\,(R+r\\cos v).$$ <b>Integrale.</b> $$A=\\int_0^{2\\pi}\\!\\!\\int_0^{2\\pi} r(R+r\\cos v)\\,du\\,dv=2\\pi r\\int_0^{2\\pi}(R+r\\cos v)\\,dv=2\\pi r\\,(2\\pi R)=4\\pi^2 Rr,$$ perche' $\\int_0^{2\\pi}\\cos v\\,dv=0$. <b>Controllo con Guldino.</b> Curva generatrice = cerchio di raggio $r$, $L=2\\pi r$; baricentro a distanza $d=R$ dall'asse. $A=2\\pi dL=2\\pi R\\cdot2\\pi r=4\\pi^2 Rr$: coincide. <b>Le insidie.</b> (1) <b>Iniettivita' sul bordo.</b> $\\sigma$ e' iniettiva sull'aperto $(0,2\\pi)^2$; sul bordo del rettangolo i lati $u=0$ e $u=2\\pi$ (e $v=0,2\\pi$) si identificano. Ma il bordo e' un insieme di misura nulla in $\\mathbb{R}^2$: l'integrale non lo vede e l'area e' corretta. La definizione infatti chiede iniettivita' all'interno. (2) <b>Degenerazione ai poli.</b> Nel toro $|\\sigma_u\\times\\sigma_v|=r(R+r\\cos v)\\geq r(R-r)>0$ ovunque: nessuna degenerazione. E' la <b>sfera</b> a degenerare ai poli, dove $|\\sigma_\\theta\\times\\sigma_\\varphi|=R^2\\sin\\theta=0$; anche li' un insieme di misura nulla, area salva. L'esaminatore cerca proprio questa distinzione fra ipotesi «all'interno» e comportamento sul bordo di misura nulla."}

];
